#!/usr/bin/env python3
"""
Load full 2026 schedules for all 16 Big 12 teams.
Parses schedule data from athletics websites and inserts into database.
"""

from pathlib import Path
import sqlite3
import re
from datetime import datetime

DB_PATH = "~/college-baseball-predictor/data/baseball.db"

# All 16 Big 12 teams with their standard IDs
BIG12_TEAMS = {
    'arizona': 'Arizona',
    'arizona-state': 'Arizona State',
    'byu': 'BYU',
    'baylor': 'Baylor',
    'cincinnati': 'Cincinnati',
    'colorado': 'Colorado',
    'houston': 'Houston',
    'iowa-state': 'Iowa State',
    'kansas': 'Kansas',
    'kansas-state': 'Kansas State',
    'oklahoma-state': 'Oklahoma State',
    'tcu': 'TCU',
    'texas-tech': 'Texas Tech',
    'ucf': 'UCF',
    'utah': 'Utah',
    'west-virginia': 'West Virginia'
}

# Team name to ID mapping (for parsing opponent names)
TEAM_NAME_MAP = {
    # Big 12 teams
    'arizona': 'arizona',
    'arizona wildcats': 'arizona',
    'wildcats': 'arizona',
    'arizona state': 'arizona-state',
    'asu': 'arizona-state',
    'sun devils': 'arizona-state',
    'byu': 'byu',
    'brigham young': 'byu',
    'cougars': 'byu',
    'baylor': 'baylor',
    'baylor bears': 'baylor',
    'bears': 'baylor',
    'cincinnati': 'cincinnati',
    'bearcats': 'cincinnati',
    'colorado': 'colorado',
    'buffaloes': 'colorado',
    'buffs': 'colorado',
    'houston': 'houston',
    'iowa state': 'iowa-state',
    'cyclones': 'iowa-state',
    'kansas': 'kansas',
    'jayhawks': 'kansas',
    'kansas state': 'kansas-state',
    'k-state': 'kansas-state',
    'wildcats': 'kansas-state',
    'oklahoma state': 'oklahoma-state',
    'ok state': 'oklahoma-state',
    'osu': 'oklahoma-state',
    'cowboys': 'oklahoma-state',
    'tcu': 'tcu',
    'horned frogs': 'tcu',
    'texas tech': 'texas-tech',
    'red raiders': 'texas-tech',
    'ucf': 'ucf',
    'central florida': 'ucf',
    'knights': 'ucf',
    'utah': 'utah',
    'utes': 'utah',
    'west virginia': 'west-virginia',
    'wvu': 'west-virginia',
    'mountaineers': 'west-virginia',
    
    # SEC teams
    'texas': 'texas',
    'oklahoma': 'oklahoma',
    'lsu': 'lsu',
    'florida': 'florida',
    'georgia': 'georgia',
    'alabama': 'alabama',
    'arkansas': 'arkansas',
    'tennessee': 'tennessee',
    'vanderbilt': 'vanderbilt',
    'ole miss': 'ole-miss',
    'mississippi state': 'mississippi-state',
    'auburn': 'auburn',
    'kentucky': 'kentucky',
    'missouri': 'missouri',
    'south carolina': 'south-carolina',
    'texas a&m': 'texas-am',
    
    # Other teams
    'siena': 'siena',
    'miami': 'miami-fl',
    'notre dame': 'notre-dame',
    'indiana': 'indiana',
    'south florida': 'usf',
    'usf': 'usf',
    'fgcu': 'fgcu',
    'florida gulf coast': 'fgcu',
    'murray state': 'murray-state',
    'columbia': 'columbia',
    'stetson': 'stetson',
    'penn state': 'penn-state',
    'jacksonville': 'jacksonville',
    'bethune-cookman': 'bethune-cookman',
    'florida atlantic': 'fau',
    'fau': 'fau',
    'omaha': 'omaha',
    'nebraska-omaha': 'omaha',
    'uconn': 'uconn',
    'connecticut': 'uconn',
    "st. john's": 'st-johns',
    'st johns': 'st-johns',
    'lmu': 'lmu',
    'loyola marymount': 'lmu',
    'grand canyon': 'gcu',
    'gcu': 'gcu',
    'grand canyon university': 'gcu',
    'unlv': 'unlv',
    'san diego state': 'san-diego-state',
    'sdsu': 'san-diego-state',
    'new mexico state': 'new-mexico-state',
    'ucsd': 'ucsd',
    'uc san diego': 'ucsd',
    'uc riverside': 'uc-riverside',
    'long beach state': 'long-beach-state',
    'washington state': 'washington-state',
    'cal baptist': 'cal-baptist',
    'utah tech': 'utah-tech',
    'utah valley': 'utah-valley',
    'lamar': 'lamar',
    'western kentucky': 'western-kentucky',
    'jacksonville state': 'jacksonville-state',
    'uab': 'uab',
    'bowling green': 'bowling-green',
    'austin peay': 'austin-peay',
    'uc san diego': 'ucsd',
    'evansville': 'evansville',
    'xavier': 'xavier',
    'wright state': 'wright-state',
    'oral roberts': 'oral-roberts',
    'iowa': 'iowa',
    'penn state': 'penn-state',
    'air force': 'air-force',
    'nebraska': 'nebraska',
    'michigan': 'michigan',
    'louisiana': 'louisiana',
    'mcneese state': 'mcneese',
    'mcneese': 'mcneese',
    'minnesota': 'minnesota',
    'utrgv': 'utrgv',
    'ut-rio grande valley': 'utrgv',
    'georgia southern': 'georgia-southern',
    'liberty': 'liberty',
    'canisius': 'canisius',
    'kennesaw state': 'kennesaw-state',
    'ucla': 'ucla',
    'ut arlington': 'ut-arlington',
}

def normalize_team_name(name):
    """Convert team name to standard ID."""
    if not name:
        return None
    
    name_lower = name.lower().strip()
    # Remove rankings like "#2" or "No. 14"
    name_lower = re.sub(r'^#?\d+\s+', '', name_lower)
    name_lower = re.sub(r'^no\.\s*\d+\s+', '', name_lower)
    name_lower = name_lower.strip()
    
    if name_lower in TEAM_NAME_MAP:
        return TEAM_NAME_MAP[name_lower]
    
    # Try to create an ID from the name
    team_id = re.sub(r'[^a-z0-9]+', '-', name_lower).strip('-')
    return team_id

def parse_date(date_str, year=2026):
    """Parse date string like 'Feb 13' or 'Mar 1' into ISO format."""
    date_str = date_str.strip()
    
    # Handle formats like "Feb 13 (Fri)" or "Fri. Feb 13"
    date_str = re.sub(r'\([^)]+\)', '', date_str)  # Remove day in parens
    date_str = re.sub(r'^(Mon|Tue|Wed|Thu|Fri|Sat|Sun)\.?\s*', '', date_str)  # Remove day prefix
    date_str = date_str.strip()
    
    month_map = {
        'jan': 1, 'feb': 2, 'mar': 3, 'apr': 4, 'may': 5, 'jun': 6,
        'jul': 7, 'aug': 8, 'sep': 9, 'oct': 10, 'nov': 11, 'dec': 12
    }
    
    # Try "Feb 13" format
    match = re.match(r'([A-Za-z]+)\.?\s+(\d+)', date_str)
    if match:
        month_str, day = match.groups()
        month = month_map.get(month_str.lower()[:3])
        if month:
            return f"{year}-{month:02d}-{int(day):02d}"
    
    return None

# Raw schedule data for each team (extracted from web fetches)
# Format: list of (date_str, opponent, is_home, time)
SCHEDULES = {
    'arizona': [
        # Non-conference
        ('Feb 13', 'Grand Canyon', True, '6:00 PM'),
        ('Feb 14', 'Grand Canyon', True, '6:00 PM'),
        ('Feb 15', 'Grand Canyon', True, '1:00 PM'),
        ('Feb 17', 'Grand Canyon', True, '6:00 PM'),
        ('Feb 20', 'Oregon', True, '6:00 PM'),  # Las Vegas Classic
        ('Feb 21', 'Vanderbilt', True, '6:00 PM'),
        ('Feb 22', 'Arizona State', True, '1:00 PM'),
        ('Feb 24', 'New Mexico', True, '6:00 PM'),
        ('Feb 27', 'Oregon State', True, '6:00 PM'),
        ('Feb 28', 'Oregon State', True, '6:00 PM'),
        ('Mar 1', 'Oregon State', True, '1:00 PM'),
        ('Mar 3', 'New Mexico State', True, '6:00 PM'),
        ('Mar 6', 'UC Irvine', True, '6:00 PM'),
        ('Mar 7', 'UC Irvine', True, '6:00 PM'),
        ('Mar 8', 'UC Irvine', True, '1:00 PM'),
        ('Mar 10', 'Arizona State', False, '6:35 PM'),
        # Conference play
        ('Mar 13', 'Utah', False, '5:00 PM'),
        ('Mar 14', 'Utah', False, '1:00 PM'),
        ('Mar 15', 'Utah', False, '12:00 PM'),
        ('Mar 17', 'New Mexico', True, '6:00 PM'),
        ('Mar 20', 'Kansas', True, '6:00 PM'),
        ('Mar 21', 'Kansas', True, '6:00 PM'),
        ('Mar 22', 'Kansas', True, '1:00 PM'),
        ('Mar 24', 'Arizona State', True, '6:00 PM'),
        ('Mar 27', 'UCF', False, '3:00 PM'),
        ('Mar 28', 'UCF', False, '3:00 PM'),
        ('Mar 29', 'UCF', False, '10:00 AM'),
        ('Mar 31', 'New Mexico State', True, '6:00 PM'),
        ('Apr 3', 'Arizona State', False, '6:00 PM'),
        ('Apr 4', 'Arizona State', False, '6:00 PM'),
        ('Apr 5', 'Arizona State', False, '6:00 PM'),
        ('Apr 7', 'Grand Canyon', True, '6:00 PM'),
        ('Apr 10', 'TCU', False, '4:00 PM'),
        ('Apr 11', 'TCU', False, '12:00 PM'),
        ('Apr 12', 'TCU', False, '12:30 PM'),
        ('Apr 13', 'Arizona State', False, '6:35 PM'),
        ('Apr 17', 'Texas Tech', True, '6:00 PM'),
        ('Apr 18', 'Texas Tech', True, '6:00 PM'),
        ('Apr 19', 'Texas Tech', True, '1:00 PM'),
        ('Apr 21', 'New Mexico State', True, '6:00 PM'),
        ('Apr 23', 'BYU', True, '7:00 PM'),
        ('Apr 24', 'BYU', True, '7:00 PM'),
        ('Apr 25', 'BYU', True, '1:00 PM'),
        ('Apr 28', 'Grand Canyon', False, '7:00 PM'),
        ('May 1', 'Kansas', False, '4:00 PM'),
        ('May 2', 'Kansas', False, '12:00 PM'),
        ('May 3', 'Kansas', False, '11:00 AM'),
        ('May 6', 'New Mexico', True, '6:00 PM'),
        ('May 8', 'Houston', True, '6:00 PM'),
        ('May 9', 'Houston', True, '6:00 PM'),
        ('May 10', 'Houston', True, '1:00 PM'),
        ('May 14', 'Oklahoma State', False, '4:00 PM'),
        ('May 15', 'Oklahoma State', False, '4:00 PM'),
        ('May 16', 'Oklahoma State', False, '10:00 AM'),
    ],
    'arizona-state': [
        ('Feb 13', 'Omaha', True, '6:35 PM'),
        ('Feb 14', 'Omaha', True, '1:05 PM'),
        ('Feb 15', 'Omaha', True, '1:05 PM'),
        ('Feb 17', 'UConn', True, '6:35 PM'),
        ('Feb 20', "St. John's", True, '6:35 PM'),
        ('Feb 21', "St. John's", True, '1:05 PM'),
        ('Feb 22', "St. John's", True, '1:05 PM'),
        ('Feb 24', 'Oklahoma', False, '4:00 PM'),
        ('Feb 25', 'Oklahoma', False, '4:00 PM'),
        ('Feb 27', 'Mississippi State', False, '10:00 AM'),  # Globe Life
        ('Feb 28', 'Tennessee', False, '10:00 AM'),
        ('Mar 1', 'Texas A&M', False, '5:30 PM'),
        ('Mar 6', 'LMU', True, '6:35 PM'),
        ('Mar 7', 'LMU', True, '6:35 PM'),
        ('Mar 8', 'LMU', True, '1:05 PM'),
        ('Mar 10', 'Arizona', True, '6:35 PM'),
        ('Mar 13', 'TCU', True, '6:35 PM'),
        ('Mar 14', 'TCU', True, '6:35 PM'),
        ('Mar 15', 'TCU', True, '1:05 PM'),
        ('Mar 17', 'Grand Canyon', True, '6:35 PM'),
        ('Mar 20', 'Kansas State', False, '4:00 PM'),
        ('Mar 21', 'Kansas State', False, '2:00 PM'),
        ('Mar 22', 'Kansas State', False, '11:00 AM'),
        ('Mar 23', 'UNLV', False, '6:05 PM'),
        ('Mar 25', 'New Mexico State', True, '6:35 PM'),
        ('Mar 27', 'West Virginia', True, '6:35 PM'),
        ('Mar 28', 'West Virginia', True, '6:35 PM'),
        ('Mar 29', 'West Virginia', True, '5:05 PM'),
        ('Mar 30', 'San Diego State', True, '6:35 PM'),
        ('Apr 2', 'Arizona', False, '6:05 PM'),
        ('Apr 3', 'Arizona', False, '6:05 PM'),
        ('Apr 4', 'Arizona', False, '6:05 PM'),
        ('Apr 7', 'Grand Canyon', False, '6:05 PM'),
        ('Apr 8', 'UNLV', True, '6:35 PM'),
        ('Apr 10', 'Utah', True, '6:35 PM'),
        ('Apr 11', 'Utah', True, '6:35 PM'),
        ('Apr 12', 'Utah', True, '1:05 PM'),
        ('Apr 13', 'Arizona', True, '6:35 PM'),
        ('Apr 16', 'BYU', False, '5:00 PM'),
        ('Apr 17', 'BYU', False, '5:00 PM'),
        ('Apr 18', 'BYU', False, '12:00 PM'),
        ('Apr 22', 'New Mexico State', True, '6:35 PM'),
        ('Apr 24', 'Baylor', True, '6:35 PM'),
        ('Apr 25', 'Baylor', True, '6:35 PM'),
        ('Apr 26', 'Baylor', True, '1:05 PM'),
        ('May 1', 'UCF', False, '3:00 PM'),
        ('May 2', 'UCF', False, '3:00 PM'),
        ('May 3', 'UCF', False, '10:00 AM'),
        ('May 5', 'Missouri', False, '10:00 AM'),
        ('May 8', 'Oklahoma State', True, '6:05 PM'),
        ('May 9', 'Oklahoma State', True, '6:05 PM'),
        ('May 10', 'Oklahoma State', True, '1:05 PM'),
        ('May 12', 'Grand Canyon', False, '6:05 PM'),
        ('May 14', 'Houston', False, '4:30 PM'),
        ('May 15', 'Houston', False, '4:30 PM'),
        ('May 16', 'Houston', False, '11:00 AM'),
    ],
    'byu': [
        ('Feb 13', 'Western Kentucky', False, '11:00 AM'),
        ('Feb 14', 'Western Kentucky', False, '12:00 PM'),
        ('Feb 16', 'Western Kentucky', False, '12:00 PM'),
        ('Feb 19', 'Nebraska-Omaha', True, '7:00 PM'),  # San Diego
        ('Feb 20', 'San Diego State', False, '7:00 PM'),
        ('Feb 21', 'UCSD', False, '7:00 PM'),
        ('Feb 23', 'UC Riverside', False, '2:00 PM'),
        ('Feb 25', 'Long Beach State', False, '2:00 PM'),
        ('Feb 26', 'Washington State', True, '2:05 PM'),
        ('Feb 27', 'Washington State', True, '2:05 PM'),
        ('Feb 28', 'Long Beach State', False, '2:00 PM'),
        ('Mar 5', 'Cal Baptist', True, '3:00 PM'),
        ('Mar 6', 'Cal Baptist', True, '3:00 PM'),
        ('Mar 7', 'Cal Baptist', True, '1:00 PM'),
        ('Mar 10', 'Utah Tech', True, '3:00 PM'),
        ('Mar 12', 'Cincinnati', True, '3:00 PM'),
        ('Mar 13', 'Cincinnati', True, '3:00 PM'),
        ('Mar 14', 'Cincinnati', True, '1:00 PM'),
        ('Mar 17', 'Utah Tech', False, '6:05 PM'),
        ('Mar 19', 'West Virginia', False, '4:30 PM'),
        ('Mar 20', 'West Virginia', False, '4:30 PM'),
        ('Mar 21', 'West Virginia', False, '11:00 AM'),
        ('Mar 24', 'Utah', False, '6:00 PM'),
        ('Mar 26', 'Oklahoma State', True, '6:00 PM'),
        ('Mar 27', 'Oklahoma State', True, '6:00 PM'),
        ('Mar 28', 'Oklahoma State', True, '1:00 PM'),
        ('Mar 31', 'Kansas State', True, '6:00 PM'),
        ('Apr 2', 'Baylor', False, '5:30 PM'),
        ('Apr 3', 'Baylor', False, '5:30 PM'),
        ('Apr 4', 'Baylor', False, '12:00 PM'),
        ('Apr 7', 'Utah Valley', False, '6:05 PM'),
        ('Apr 9', 'Houston', False, '5:30 PM'),
        ('Apr 10', 'Houston', False, '5:30 PM'),
        ('Apr 11', 'Houston', False, '12:00 PM'),
        ('Apr 13', 'Lamar', False, '5:00 PM'),
        ('Apr 16', 'Arizona State', True, '6:00 PM'),
        ('Apr 17', 'Arizona State', True, '6:00 PM'),
        ('Apr 18', 'Arizona State', True, '1:00 PM'),
        ('Apr 20', 'Utah Tech', True, '5:00 PM'),
        ('Apr 23', 'Arizona', False, '7:00 PM'),
        ('Apr 24', 'Arizona', False, '7:00 PM'),
        ('Apr 25', 'Arizona', False, '1:00 PM'),
        ('Apr 27', 'Grand Canyon', False, '2:00 PM'),
        ('Apr 30', 'Utah', True, '6:00 PM'),
        ('May 1', 'Utah', True, '6:00 PM'),
        ('May 2', 'Utah', True, '1:00 PM'),
        ('May 5', 'UNLV', False, '7:05 PM'),
        ('May 7', 'Texas Tech', False, '5:00 PM'),
        ('May 8', 'Texas Tech', False, '5:00 PM'),
        ('May 9', 'Texas Tech', False, '12:00 PM'),
        ('May 12', 'Utah Valley', True, '6:00 PM'),
        ('May 14', 'Kansas', True, '6:00 PM'),
        ('May 15', 'Kansas', True, '6:00 PM'),
        ('May 16', 'Kansas', True, '1:00 PM'),
    ],
    'cincinnati': [
        ('Feb 13', 'Jacksonville State', False, '5:00 PM'),
        ('Feb 14', 'Jacksonville State', False, '3:00 PM'),
        ('Feb 15', 'Jacksonville State', False, '2:00 PM'),
        ('Feb 17', 'Auburn', False, '7:00 PM'),
        ('Feb 19', 'UAB', False, '3:00 PM'),
        ('Feb 20', 'UAB', False, '3:00 PM'),
        ('Feb 21', 'UAB', False, '2:00 PM'),
        ('Feb 22', 'UAB', False, '2:00 PM'),
        ('Feb 24', 'Bowling Green', True, '4:00 PM'),
        ('Feb 27', 'Austin Peay', True, '4:00 PM'),
        ('Feb 28', 'Austin Peay', True, '2:00 PM'),
        ('Mar 1', 'Austin Peay', True, '1:00 PM'),
        ('Mar 3', 'Western Kentucky', True, '4:00 PM'),
        ('Mar 5', 'UC San Diego', True, '4:00 PM'),
        ('Mar 6', 'UC San Diego', True, '4:00 PM'),
        ('Mar 7', 'UC San Diego', True, '2:00 PM'),
        ('Mar 8', 'UC San Diego', True, '1:00 PM'),
        ('Mar 10', 'Evansville', True, '3:00 PM'),
        ('Mar 12', 'BYU', False, '5:00 PM'),
        ('Mar 13', 'BYU', False, '5:00 PM'),
        ('Mar 14', 'BYU', False, '3:00 PM'),
        ('Mar 16', 'Utah Valley', False, '7:35 PM'),
        ('Mar 17', 'Utah Valley', False, '1:05 PM'),
        ('Mar 20', 'Utah', True, '6:00 PM'),
        ('Mar 21', 'Utah', True, '3:00 PM'),
        ('Mar 22', 'Utah', True, '1:00 PM'),
        ('Mar 24', 'Xavier', False, '3:00 PM'),
        ('Mar 27', 'Kansas', True, '6:00 PM'),
        ('Mar 28', 'Kansas', True, '3:00 PM'),
        ('Mar 29', 'Kansas', True, '1:00 PM'),
        ('Mar 31', 'Wright State', True, '6:00 PM'),
        ('Apr 3', 'Oklahoma State', False, '7:00 PM'),
        ('Apr 4', 'Oklahoma State', False, '7:00 PM'),
        ('Apr 5', 'Oklahoma State', False, '2:00 PM'),
        ('Apr 7', 'Miami (Ohio)', True, 'TBA'),
        ('Apr 10', 'Baylor', True, '6:00 PM'),
        ('Apr 11', 'Baylor', True, '3:00 PM'),
        ('Apr 12', 'Baylor', True, '12:00 PM'),
        ('Apr 14', 'Xavier', True, '6:00 PM'),
        ('Apr 17', 'UCF', False, '6:00 PM'),
        ('Apr 18', 'UCF', False, '6:00 PM'),
        ('Apr 19', 'UCF', False, '1:00 PM'),
        ('Apr 21', 'Wright State', False, '3:00 PM'),
        ('Apr 24', 'West Virginia', True, '6:00 PM'),
        ('Apr 25', 'West Virginia', True, '3:00 PM'),
        ('Apr 26', 'West Virginia', True, '1:00 PM'),
        ('May 1', 'Houston', False, '7:30 PM'),
        ('May 2', 'Houston', False, '7:30 PM'),
        ('May 3', 'Houston', False, '2:00 PM'),
        ('May 5', 'Oral Roberts', False, '7:00 PM'),
        ('May 8', 'Kansas State', False, '7:00 PM'),
        ('May 9', 'Kansas State', False, '5:00 PM'),
        ('May 10', 'Kansas State', False, '12:00 PM'),
        ('May 14', 'Texas Tech', True, '6:00 PM'),
        ('May 15', 'Texas Tech', True, '6:00 PM'),
        ('May 16', 'Texas Tech', True, '1:00 PM'),
    ],
    'ucf': [
        ('Feb 13', 'Siena', True, '6:00 PM'),
        ('Feb 14', 'Siena', True, '1:00 PM'),
        ('Feb 15', 'Siena', True, '1:00 PM'),
        ('Feb 17', 'Miami', False, '6:00 PM'),
        ('Feb 20', 'Notre Dame', True, '6:00 PM'),  # Jacksonville
        ('Feb 21', 'Indiana', True, '4:00 PM'),
        ('Feb 22', 'LSU', True, '3:00 PM'),
        ('Feb 24', 'Jacksonville', False, '6:00 PM'),
        ('Feb 27', 'South Florida', True, '6:00 PM'),
        ('Feb 28', 'South Florida', True, '1:00 PM'),
        ('Mar 1', 'South Florida', True, '1:00 PM'),
        ('Mar 4', 'FGCU', True, '6:00 PM'),
        ('Mar 6', 'Murray State', True, '6:00 PM'),
        ('Mar 7', 'Murray State', True, '6:00 PM'),
        ('Mar 8', 'Murray State', True, '1:00 PM'),
        ('Mar 11', 'Miami', True, '6:00 PM'),
        ('Mar 13', 'Oklahoma State', True, '6:00 PM'),
        ('Mar 14', 'Oklahoma State', True, '6:00 PM'),
        ('Mar 15', 'Oklahoma State', True, '12:00 PM'),
        ('Mar 17', 'Columbia', True, '6:00 PM'),
        ('Mar 20', 'TCU', False, '7:00 PM'),
        ('Mar 21', 'TCU', False, '3:00 PM'),
        ('Mar 22', 'TCU', False, '2:00 PM'),
        ('Mar 24', 'Stetson', False, '6:30 PM'),
        ('Mar 27', 'Arizona', True, '6:00 PM'),
        ('Mar 28', 'Arizona', True, '6:00 PM'),
        ('Mar 29', 'Arizona', True, '1:00 PM'),
        ('Apr 1', 'Penn State', False, '5:30 PM'),
        ('Apr 3', 'West Virginia', False, '6:30 PM'),
        ('Apr 4', 'West Virginia', False, '4:00 PM'),
        ('Apr 5', 'West Virginia', False, '1:00 PM'),
        ('Apr 7', 'Stetson', True, '6:00 PM'),
        ('Apr 10', 'Kansas', False, '7:00 PM'),
        ('Apr 11', 'Kansas', False, '3:00 PM'),
        ('Apr 12', 'Kansas', False, '2:00 PM'),
        ('Apr 14', 'Jacksonville', True, '6:00 PM'),
        ('Apr 17', 'Cincinnati', True, '6:00 PM'),
        ('Apr 18', 'Cincinnati', True, '6:00 PM'),
        ('Apr 19', 'Cincinnati', True, '1:00 PM'),
        ('Apr 21', 'Bethune-Cookman', False, '6:00 PM'),
        ('Apr 24', 'Utah', False, '8:00 PM'),
        ('Apr 25', 'Utah', False, '4:00 PM'),
        ('Apr 26', 'Utah', False, '3:00 PM'),
        ('Apr 29', 'Stetson', True, 'TBA'),
        ('May 1', 'Arizona State', True, '6:00 PM'),
        ('May 2', 'Arizona State', True, '6:00 PM'),
        ('May 3', 'Arizona State', True, '1:00 PM'),
        ('May 5', 'Florida Atlantic', False, '6:00 PM'),
        ('May 8', 'Baylor', False, '7:30 PM'),
        ('May 9', 'Baylor', False, '3:00 PM'),
        ('May 10', 'Baylor', False, '2:00 PM'),
        ('May 12', 'Bethune-Cookman', True, '6:00 PM'),
        ('May 14', 'Kansas State', True, '6:00 PM'),
        ('May 15', 'Kansas State', True, '6:00 PM'),
        ('May 16', 'Kansas State', True, '1:00 PM'),
    ],
    'kansas': [
        ('Feb 13', 'UTRGV', False, '6:30 PM'),
        ('Feb 14', 'UTRGV', False, '6:30 PM'),
        ('Feb 15', 'UTRGV', False, '1:00 PM'),
        ('Feb 18', 'Lamar', False, '6:00 PM'),
        ('Feb 20', 'McNeese State', False, '6:00 PM'),
        ('Feb 21', 'McNeese State', False, '1:00 PM'),
        ('Feb 22', 'McNeese State', False, '11:00 AM'),
        ('Feb 25', 'Minnesota', False, '6:00 PM'),
        ('Feb 27', 'Minnesota', False, '6:00 PM'),
        ('Feb 28', 'Minnesota', False, '3:00 PM'),
        ('Mar 3', 'Southeast Missouri', True, '3:00 PM'),
        ('Mar 6', 'New Mexico', True, '3:00 PM'),
        ('Mar 7', 'New Mexico', True, '1:00 PM'),
        ('Mar 8', 'New Mexico', True, '1:00 PM'),
        ('Mar 10', 'Illinois', True, '3:00 PM'),
        ('Mar 13', 'Kansas State', False, '6:00 PM'),
        ('Mar 14', 'Kansas State', False, '2:00 PM'),
        ('Mar 15', 'Kansas State', False, '1:00 PM'),
        ('Mar 17', 'Missouri', True, '6:00 PM'),
        ('Mar 20', 'Arizona', False, '6:00 PM'),
        ('Mar 21', 'Arizona', False, '6:00 PM'),
        ('Mar 22', 'Arizona', False, '1:00 PM'),
        ('Mar 24', 'Wichita State', True, '6:00 PM'),
        ('Mar 27', 'Cincinnati', False, '6:00 PM'),
        ('Mar 28', 'Cincinnati', False, '3:00 PM'),
        ('Mar 29', 'Cincinnati', False, '1:00 PM'),
        ('Mar 31', 'Missouri', False, '7:00 PM'),
        ('Apr 3', 'Texas Tech', True, '6:00 PM'),
        ('Apr 4', 'Texas Tech', True, '2:00 PM'),
        ('Apr 5', 'Texas Tech', True, '1:00 PM'),
        ('Apr 7', 'Wichita State', False, '6:00 PM'),
        ('Apr 10', 'UCF', True, '7:00 PM'),
        ('Apr 11', 'UCF', True, '3:00 PM'),
        ('Apr 12', 'UCF', True, '2:00 PM'),
        ('Apr 14', 'Nebraska', True, '6:00 PM'),
        ('Apr 17', 'Houston', False, '6:30 PM'),
        ('Apr 18', 'Houston', False, '2:00 PM'),
        ('Apr 19', 'Houston', False, '1:00 PM'),
        ('Apr 21', 'Nebraska', False, '6:30 PM'),
        ('Apr 24', 'Oklahoma State', True, '6:00 PM'),
        ('Apr 25', 'Oklahoma State', True, '2:00 PM'),
        ('Apr 26', 'Oklahoma State', True, '1:00 PM'),
        ('Apr 28', 'Omaha', True, '6:00 PM'),
        ('May 1', 'Arizona', True, '4:00 PM'),
        ('May 2', 'Arizona', True, '12:00 PM'),
        ('May 3', 'Arizona', True, '11:00 AM'),
        ('May 5', 'Omaha', False, '6:00 PM'),
        ('May 8', 'West Virginia', False, '6:00 PM'),
        ('May 9', 'West Virginia', False, '2:00 PM'),
        ('May 10', 'West Virginia', False, '1:00 PM'),
        ('May 12', 'Wichita State', True, '6:00 PM'),
        ('May 14', 'BYU', False, '6:00 PM'),
        ('May 15', 'BYU', False, '6:00 PM'),
        ('May 16', 'BYU', False, '1:00 PM'),
    ],
    'kansas-state': [
        ('Feb 13', 'Iowa', True, '2:00 PM'),  # Scottsdale
        ('Feb 14', 'UConn', True, '6:00 PM'),
        ('Feb 15', 'Penn State', True, '1:00 PM'),
        ('Feb 16', 'Air Force', True, '2:00 PM'),
        ('Feb 20', 'Auburn', True, '7:00 PM'),  # Arlington
        ('Feb 21', 'Nebraska', True, '7:00 PM'),
        ('Feb 22', 'Michigan', True, '6:30 PM'),
        ('Feb 24', 'Louisiana', False, '6:00 PM'),
        ('Feb 27', 'Maryland', True, '3:00 PM'),
        ('Feb 28', 'Maryland', True, '1:00 PM'),
        ('Mar 1', 'Maryland', True, '1:00 PM'),
        ('Mar 6', 'Rice', True, '3:00 PM'),
        ('Mar 7', 'Rice', True, '1:00 PM'),
        ('Mar 8', 'Rice', True, '1:00 PM'),
        ('Mar 10', 'Missouri State', True, '3:00 PM'),
        ('Mar 13', 'Kansas', True, '6:00 PM'),
        ('Mar 14', 'Kansas', True, '2:00 PM'),
        ('Mar 15', 'Kansas', True, '1:00 PM'),
        ('Mar 17', 'Sam Houston', True, '3:00 PM'),
        ('Mar 20', 'Arizona State', True, '6:00 PM'),
        ('Mar 21', 'Arizona State', True, '4:00 PM'),
        ('Mar 22', 'Arizona State', True, '1:00 PM'),
        ('Mar 24', 'Wichita State', True, '6:00 PM'),
        ('Mar 27', 'West Virginia', False, '6:00 PM'),
        ('Mar 28', 'West Virginia', False, '2:00 PM'),
        ('Mar 29', 'West Virginia', False, '1:00 PM'),
        ('Mar 31', 'BYU', False, '6:00 PM'),
        ('Apr 3', 'Utah', True, '6:00 PM'),
        ('Apr 4', 'Utah', True, '2:00 PM'),
        ('Apr 5', 'Utah', True, '1:00 PM'),
        ('Apr 7', 'Wichita State', False, '6:00 PM'),
        ('Apr 10', 'Texas Tech', False, '6:30 PM'),
        ('Apr 11', 'Texas Tech', False, '2:00 PM'),
        ('Apr 12', 'Texas Tech', False, '1:00 PM'),
        ('Apr 14', 'Nebraska', False, '6:30 PM'),
        ('Apr 17', 'Oklahoma State', True, '6:00 PM'),
        ('Apr 18', 'Oklahoma State', True, '2:00 PM'),
        ('Apr 19', 'Oklahoma State', True, '1:00 PM'),
        ('Apr 21', 'Nebraska', True, '6:00 PM'),
        ('Apr 24', 'Houston', True, '6:00 PM'),
        ('Apr 25', 'Houston', True, '2:00 PM'),
        ('Apr 26', 'Houston', True, '1:00 PM'),
        ('Apr 29', 'Missouri State', False, '6:30 PM'),
        ('May 1', 'TCU', False, '6:30 PM'),
        ('May 2', 'TCU', False, '2:00 PM'),
        ('May 3', 'TCU', False, '1:00 PM'),
        ('May 5', 'Omaha', True, '6:00 PM'),
        ('May 8', 'Cincinnati', True, '7:00 PM'),
        ('May 9', 'Cincinnati', True, '5:00 PM'),
        ('May 10', 'Cincinnati', True, '12:00 PM'),
        ('May 14', 'UCF', False, '6:00 PM'),
        ('May 15', 'UCF', False, '6:00 PM'),
        ('May 16', 'UCF', False, '1:00 PM'),
    ],
    'oklahoma-state': [
        ('Feb 13', 'Arkansas', True, '7:00 PM'),  # Arlington
        ('Feb 14', 'Vanderbilt', True, '3:00 PM'),
        ('Feb 15', 'TCU', True, '10:30 AM'),
        ('Feb 17', 'New Mexico', True, '6:00 PM'),
        ('Feb 20', 'Washington', True, '6:00 PM'),
        ('Feb 21', 'Washington', True, '2:00 PM'),
        ('Feb 22', 'Washington', True, '1:00 PM'),
        ('Feb 24', 'Oral Roberts', True, '6:00 PM'),
        ('Feb 27', 'Georgia Tech', True, '6:00 PM'),
        ('Feb 28', 'Georgia Tech', True, '2:00 PM'),
        ('Mar 1', 'Georgia Tech', True, '1:00 PM'),
        ('Mar 3', 'Arkansas-Pine Bluff', True, '6:00 PM'),
        ('Mar 6', 'California', True, '6:00 PM'),
        ('Mar 7', 'California', True, '2:00 PM'),
        ('Mar 8', 'California', True, '1:00 PM'),
        ('Mar 10', 'Dallas Baptist', True, '6:00 PM'),
        ('Mar 13', 'UCF', False, '6:00 PM'),
        ('Mar 14', 'UCF', False, '6:00 PM'),
        ('Mar 15', 'UCF', False, '12:00 PM'),
        ('Mar 17', 'North Dakota State', True, '6:00 PM'),
        ('Mar 20', 'Houston', True, '6:00 PM'),
        ('Mar 21', 'Houston', True, '2:00 PM'),
        ('Mar 22', 'Houston', True, '1:00 PM'),
        ('Mar 24', 'Dallas Baptist', False, '6:30 PM'),
        ('Mar 26', 'BYU', False, '6:00 PM'),
        ('Mar 27', 'BYU', False, '6:00 PM'),
        ('Mar 28', 'BYU', False, '1:00 PM'),
        ('Mar 31', 'Oral Roberts', False, '6:00 PM'),
        ('Apr 3', 'Cincinnati', True, '7:00 PM'),
        ('Apr 4', 'Cincinnati', True, '7:00 PM'),
        ('Apr 5', 'Cincinnati', True, '2:00 PM'),
        ('Apr 7', 'Arkansas-Pine Bluff', True, '6:00 PM'),
        ('Apr 10', 'Baylor', False, '6:30 PM'),
        ('Apr 11', 'Baylor', False, '2:00 PM'),
        ('Apr 12', 'Baylor', False, '1:00 PM'),
        ('Apr 14', 'Dallas Baptist', True, '6:00 PM'),
        ('Apr 17', 'Kansas State', False, '6:00 PM'),
        ('Apr 18', 'Kansas State', False, '2:00 PM'),
        ('Apr 19', 'Kansas State', False, '1:00 PM'),
        ('Apr 22', 'Tulsa', True, '6:00 PM'),
        ('Apr 24', 'Kansas', False, '6:00 PM'),
        ('Apr 25', 'Kansas', False, '2:00 PM'),
        ('Apr 26', 'Kansas', False, '1:00 PM'),
        ('Apr 28', 'Tulsa', False, '6:00 PM'),
        ('May 1', 'West Virginia', True, '6:00 PM'),
        ('May 2', 'West Virginia', True, '2:00 PM'),
        ('May 3', 'West Virginia', True, '1:00 PM'),
        ('May 5', 'Oral Roberts', True, '6:00 PM'),
        ('May 8', 'Arizona State', False, '6:05 PM'),
        ('May 9', 'Arizona State', False, '6:05 PM'),
        ('May 10', 'Arizona State', False, '1:05 PM'),
        ('May 12', 'Tulsa', True, '6:00 PM'),
        ('May 14', 'Arizona', True, '4:00 PM'),
        ('May 15', 'Arizona', True, '4:00 PM'),
        ('May 16', 'Arizona', True, '10:00 AM'),
    ],
    'tcu': [
        ('Feb 13', 'Vanderbilt', True, '3:00 PM'),  # Arlington
        ('Feb 14', 'Arkansas', True, '7:00 PM'),
        ('Feb 15', 'Oklahoma', True, '6:30 PM'),
        ('Feb 17', 'UT Arlington', True, '7:00 PM'),
        ('Feb 20', 'UCLA', False, '7:00 PM'),
        ('Feb 21', 'UCLA', False, '4:00 PM'),
        ('Feb 22', 'UCLA', False, '3:00 PM'),
        ('Feb 23', 'Loyola Marymount', False, '3:00 PM'),
        ('Feb 27', 'Stanford', True, '6:30 PM'),
        ('Feb 28', 'Stanford', True, '2:00 PM'),
        ('Mar 1', 'Stanford', True, '1:00 PM'),
        ('Mar 3', 'Lamar', True, '6:30 PM'),
        ('Mar 6', 'Louisiana Tech', True, '6:30 PM'),
        ('Mar 7', 'Louisiana Tech', True, '2:00 PM'),
        ('Mar 8', 'Louisiana Tech', True, '1:00 PM'),
        ('Mar 10', 'Dallas Baptist', True, '6:30 PM'),
        ('Mar 13', 'Arizona State', False, '6:35 PM'),
        ('Mar 14', 'Arizona State', False, '6:35 PM'),
        ('Mar 15', 'Arizona State', False, '1:05 PM'),
        ('Mar 17', 'UT Arlington', False, '6:00 PM'),
        ('Mar 20', 'UCF', True, '7:00 PM'),
        ('Mar 21', 'UCF', True, '3:00 PM'),
        ('Mar 22', 'UCF', True, '2:00 PM'),
        ('Mar 24', 'Sam Houston', True, '6:30 PM'),
        ('Mar 27', 'Baylor', False, '6:30 PM'),
        ('Mar 28', 'Baylor', False, '2:00 PM'),
        ('Mar 29', 'Baylor', False, '1:00 PM'),
        ('Mar 31', 'Texas State', True, '6:30 PM'),
        ('Apr 3', 'West Virginia', True, '6:30 PM'),
        ('Apr 4', 'West Virginia', True, '2:00 PM'),
        ('Apr 5', 'West Virginia', True, '1:00 PM'),
        ('Apr 7', 'Dallas Baptist', False, '6:30 PM'),
        ('Apr 10', 'Arizona', True, '6:00 PM'),
        ('Apr 11', 'Arizona', True, '2:00 PM'),
        ('Apr 12', 'Arizona', True, '2:30 PM'),
        ('Apr 14', 'Texas State', False, '6:00 PM'),
        ('Apr 17', 'Utah', False, '6:00 PM'),
        ('Apr 18', 'Utah', False, '2:00 PM'),
        ('Apr 19', 'Utah', False, '1:00 PM'),
        ('Apr 22', 'Sam Houston', False, '6:30 PM'),
        ('Apr 24', 'Texas Tech', True, '6:30 PM'),
        ('Apr 25', 'Texas Tech', True, '2:00 PM'),
        ('Apr 26', 'Texas Tech', True, '1:00 PM'),
        ('Apr 29', 'Lamar', False, '6:30 PM'),
        ('May 1', 'Kansas State', True, '6:30 PM'),
        ('May 2', 'Kansas State', True, '2:00 PM'),
        ('May 3', 'Kansas State', True, '1:00 PM'),
        ('May 5', 'UT Arlington', True, '6:30 PM'),
        ('May 8', 'Houston', False, '6:30 PM'),
        ('May 9', 'Houston', False, '2:00 PM'),
        ('May 10', 'Houston', False, '1:00 PM'),
        ('May 14', 'Baylor', True, '6:30 PM'),
        ('May 15', 'Baylor', True, '6:30 PM'),
        ('May 16', 'Baylor', True, '1:00 PM'),
    ],
    'texas-tech': [
        ('Feb 13', 'Tennessee', True, '6:00 PM'),  # Arlington
        ('Feb 14', 'Vanderbilt', True, '11:00 AM'),
        ('Feb 15', 'Oklahoma State', True, '3:00 PM'),
        ('Feb 17', 'New Mexico State', True, '6:00 PM'),
        ('Feb 20', 'UC Santa Barbara', True, '6:00 PM'),
        ('Feb 21', 'UC Santa Barbara', True, '2:00 PM'),
        ('Feb 22', 'UC Santa Barbara', True, '1:00 PM'),
        ('Feb 24', 'UT Arlington', True, '3:00 PM'),
        ('Feb 27', 'Gonzaga', True, '6:00 PM'),
        ('Feb 28', 'Gonzaga', True, '2:00 PM'),
        ('Mar 1', 'Gonzaga', True, '1:00 PM'),
        ('Mar 3', 'New Mexico', True, '6:00 PM'),
        ('Mar 6', 'Kent State', True, '6:00 PM'),
        ('Mar 7', 'Kent State', True, '2:00 PM'),
        ('Mar 8', 'Kent State', True, '1:00 PM'),
        ('Mar 10', 'New Mexico', True, '6:00 PM'),
        ('Mar 13', 'Houston', False, '6:30 PM'),
        ('Mar 14', 'Houston', False, '2:00 PM'),
        ('Mar 15', 'Houston', False, '1:00 PM'),
        ('Mar 17', 'New Mexico State', True, '6:00 PM'),
        ('Mar 20', 'Utah', True, '6:00 PM'),
        ('Mar 21', 'Utah', True, '2:00 PM'),
        ('Mar 22', 'Utah', True, '1:00 PM'),
        ('Mar 24', 'UT Arlington', False, '6:00 PM'),
        ('Mar 27', 'Houston', True, '6:00 PM'),
        ('Mar 28', 'Houston', True, '2:00 PM'),
        ('Mar 29', 'Houston', True, '1:00 PM'),
        ('Mar 31', 'UT San Antonio', True, '6:00 PM'),
        ('Apr 3', 'Kansas', False, '6:00 PM'),
        ('Apr 4', 'Kansas', False, '2:00 PM'),
        ('Apr 5', 'Kansas', False, '1:00 PM'),
        ('Apr 7', 'UT San Antonio', False, '6:30 PM'),
        ('Apr 10', 'Kansas State', True, '6:30 PM'),
        ('Apr 11', 'Kansas State', True, '2:00 PM'),
        ('Apr 12', 'Kansas State', True, '1:00 PM'),
        ('Apr 14', 'UT Arlington', True, '6:00 PM'),
        ('Apr 17', 'Arizona', False, '6:00 PM'),
        ('Apr 18', 'Arizona', False, '6:00 PM'),
        ('Apr 19', 'Arizona', False, '1:00 PM'),
        ('Apr 21', 'New Mexico', False, '6:00 PM'),
        ('Apr 24', 'TCU', False, '6:30 PM'),
        ('Apr 25', 'TCU', False, '2:00 PM'),
        ('Apr 26', 'TCU', False, '1:00 PM'),
        ('Apr 28', 'New Mexico', True, '6:00 PM'),
        ('May 1', 'Baylor', True, '6:00 PM'),
        ('May 2', 'Baylor', True, '2:00 PM'),
        ('May 3', 'Baylor', True, '1:00 PM'),
        ('May 5', 'Dallas Baptist', True, '6:00 PM'),
        ('May 7', 'BYU', True, '6:00 PM'),
        ('May 8', 'BYU', True, '6:00 PM'),
        ('May 9', 'BYU', True, '1:00 PM'),
        ('May 12', 'Dallas Baptist', False, '6:00 PM'),
        ('May 14', 'Cincinnati', False, '6:00 PM'),
        ('May 15', 'Cincinnati', False, '6:00 PM'),
        ('May 16', 'Cincinnati', False, '1:00 PM'),
    ],
    'houston': [
        ('Feb 13', 'Illinois', True, '6:30 PM'),
        ('Feb 14', 'Illinois', True, '2:00 PM'),
        ('Feb 15', 'Illinois', True, '1:00 PM'),
        ('Feb 17', 'Sam Houston', True, '6:30 PM'),
        ('Feb 20', 'McNeese', True, '6:30 PM'),
        ('Feb 21', 'McNeese', True, '2:00 PM'),
        ('Feb 22', 'McNeese', True, '1:00 PM'),
        ('Feb 24', 'Texas State', True, '6:30 PM'),
        ('Feb 27', 'Stephen F. Austin', True, '6:30 PM'),
        ('Feb 28', 'Stephen F. Austin', True, '2:00 PM'),
        ('Mar 1', 'Stephen F. Austin', True, '1:00 PM'),
        ('Mar 3', 'Rice', True, '6:30 PM'),
        ('Mar 6', 'Purdue', True, '6:30 PM'),
        ('Mar 7', 'Purdue', True, '2:00 PM'),
        ('Mar 8', 'Purdue', True, '1:00 PM'),
        ('Mar 10', 'Texas State', False, '6:00 PM'),
        ('Mar 13', 'Texas Tech', True, '6:30 PM'),
        ('Mar 14', 'Texas Tech', True, '2:00 PM'),
        ('Mar 15', 'Texas Tech', True, '1:00 PM'),
        ('Mar 17', 'Lamar', True, '6:30 PM'),
        ('Mar 20', 'Oklahoma State', False, '6:00 PM'),
        ('Mar 21', 'Oklahoma State', False, '2:00 PM'),
        ('Mar 22', 'Oklahoma State', False, '1:00 PM'),
        ('Mar 24', 'Rice', False, '6:30 PM'),
        ('Mar 27', 'Texas Tech', False, '6:00 PM'),
        ('Mar 28', 'Texas Tech', False, '2:00 PM'),
        ('Mar 29', 'Texas Tech', False, '1:00 PM'),
        ('Mar 31', 'Dallas Baptist', True, '6:30 PM'),
        ('Apr 3', 'Utah', False, '6:00 PM'),
        ('Apr 4', 'Utah', False, '2:00 PM'),
        ('Apr 5', 'Utah', False, '1:00 PM'),
        ('Apr 7', 'Dallas Baptist', False, '6:30 PM'),
        ('Apr 9', 'BYU', True, '6:30 PM'),
        ('Apr 10', 'BYU', True, '6:30 PM'),
        ('Apr 11', 'BYU', True, '1:00 PM'),
        ('Apr 14', 'Lamar', False, '6:30 PM'),
        ('Apr 17', 'Kansas', True, '6:30 PM'),
        ('Apr 18', 'Kansas', True, '2:00 PM'),
        ('Apr 19', 'Kansas', True, '1:00 PM'),
        ('Apr 21', 'Sam Houston', False, '6:30 PM'),
        ('Apr 24', 'Kansas State', False, '6:00 PM'),
        ('Apr 25', 'Kansas State', False, '2:00 PM'),
        ('Apr 26', 'Kansas State', False, '1:00 PM'),
        ('Apr 28', 'Rice', True, '6:30 PM'),
        ('May 1', 'Cincinnati', True, '7:30 PM'),
        ('May 2', 'Cincinnati', True, '7:30 PM'),
        ('May 3', 'Cincinnati', True, '2:00 PM'),
        ('May 5', 'UT San Antonio', True, '6:30 PM'),
        ('May 8', 'TCU', True, '6:30 PM'),
        ('May 9', 'TCU', True, '2:00 PM'),
        ('May 10', 'TCU', True, '1:00 PM'),
        ('May 14', 'Arizona State', True, '6:30 PM'),
        ('May 15', 'Arizona State', True, '6:30 PM'),
        ('May 16', 'Arizona State', True, '1:00 PM'),
    ],
    'utah': [
        ('Feb 13', 'San Diego', True, '7:00 PM'),  # Tony Gwynn Legacy
        ('Feb 14', 'Utah Valley', True, '3:00 PM'),
        ('Feb 15', 'San Jose State', True, '3:00 PM'),
        ('Feb 19', 'Southern Utah', True, '3:00 PM'),
        ('Feb 20', 'UC Irvine', True, '3:00 PM'),
        ('Feb 21', 'San Diego State', True, '3:00 PM'),
        ('Feb 27', 'Stanford', True, '3:00 PM'),
        ('Feb 28', 'Stanford', True, '1:00 PM'),
        ('Mar 1', 'Stanford', True, '1:00 PM'),
        ('Mar 6', 'New Mexico', True, '3:00 PM'),
        ('Mar 7', 'New Mexico', True, '1:00 PM'),
        ('Mar 8', 'New Mexico', True, '1:00 PM'),
        ('Mar 10', 'Utah Valley', True, '3:00 PM'),
        ('Mar 13', 'Arizona', True, '5:00 PM'),
        ('Mar 14', 'Arizona', True, '1:00 PM'),
        ('Mar 15', 'Arizona', True, '12:00 PM'),
        ('Mar 17', 'Weber State', True, '3:00 PM'),
        ('Mar 20', 'Cincinnati', False, '6:00 PM'),
        ('Mar 21', 'Cincinnati', False, '3:00 PM'),
        ('Mar 22', 'Cincinnati', False, '1:00 PM'),
        ('Mar 24', 'BYU', True, '6:00 PM'),
        ('Mar 27', 'West Virginia', True, '6:00 PM'),
        ('Mar 28', 'West Virginia', True, '2:00 PM'),
        ('Mar 29', 'West Virginia', True, '1:00 PM'),
        ('Mar 31', 'Utah Valley', False, '6:00 PM'),
        ('Apr 3', 'Kansas State', False, '6:00 PM'),
        ('Apr 4', 'Kansas State', False, '2:00 PM'),
        ('Apr 5', 'Kansas State', False, '1:00 PM'),
        ('Apr 7', 'Weber State', False, '6:00 PM'),
        ('Apr 10', 'Arizona State', False, '6:35 PM'),
        ('Apr 11', 'Arizona State', False, '6:35 PM'),
        ('Apr 12', 'Arizona State', False, '1:05 PM'),
        ('Apr 14', 'Utah Tech', True, '6:00 PM'),
        ('Apr 17', 'TCU', True, '6:00 PM'),
        ('Apr 18', 'TCU', True, '2:00 PM'),
        ('Apr 19', 'TCU', True, '1:00 PM'),
        ('Apr 21', 'Utah Tech', False, '6:00 PM'),
        ('Apr 24', 'UCF', True, '8:00 PM'),
        ('Apr 25', 'UCF', True, '4:00 PM'),
        ('Apr 26', 'UCF', True, '3:00 PM'),
        ('Apr 28', 'Southern Utah', False, '6:00 PM'),
        ('Apr 30', 'BYU', False, '6:00 PM'),
        ('May 1', 'BYU', False, '6:00 PM'),
        ('May 2', 'BYU', False, '1:00 PM'),
        ('May 5', 'Utah Valley', True, '6:00 PM'),
        ('May 8', 'Baylor', True, '6:00 PM'),
        ('May 9', 'Baylor', True, '2:00 PM'),
        ('May 10', 'Baylor', True, '1:00 PM'),
        ('May 14', 'Texas Tech', False, '6:00 PM'),
        ('May 15', 'Texas Tech', False, '6:00 PM'),
        ('May 16', 'Texas Tech', False, '1:00 PM'),
    ],
    'west-virginia': [
        ('Feb 13', 'Georgia Southern', False, '6:30 PM'),
        ('Feb 14', 'Georgia Southern', False, '2:00 PM'),
        ('Feb 14', 'Georgia Southern', False, '5:00 PM'),  # DH
        ('Feb 20', 'Liberty', False, '4:00 PM'),
        ('Feb 21', 'Liberty', False, '2:00 PM'),
        ('Feb 22', 'Liberty', False, '1:00 PM'),
        ('Feb 24', 'Canisius', True, '2:00 PM'),
        ('Feb 27', 'Kennesaw State', False, '4:00 PM'),
        ('Feb 28', 'Kennesaw State', False, '1:00 PM'),
        ('Mar 1', 'Kennesaw State', False, '1:00 PM'),
        ('Mar 6', 'James Madison', True, '3:00 PM'),
        ('Mar 7', 'James Madison', True, '1:00 PM'),
        ('Mar 8', 'James Madison', True, '1:00 PM'),
        ('Mar 10', 'Canisius', True, '3:00 PM'),
        ('Mar 13', 'Baylor', True, '6:00 PM'),
        ('Mar 14', 'Baylor', True, '2:00 PM'),
        ('Mar 15', 'Baylor', True, '1:00 PM'),
        ('Mar 17', 'Penn State', True, '3:00 PM'),
        ('Mar 19', 'BYU', True, '6:30 PM'),
        ('Mar 20', 'BYU', True, '6:30 PM'),
        ('Mar 21', 'BYU', True, '1:00 PM'),
        ('Mar 24', 'Pitt', True, '6:00 PM'),
        ('Mar 27', 'Kansas State', True, '6:00 PM'),
        ('Mar 28', 'Kansas State', True, '2:00 PM'),
        ('Mar 29', 'Kansas State', True, '1:00 PM'),
        ('Mar 31', 'Penn State', False, '6:00 PM'),
        ('Apr 3', 'TCU', False, '6:30 PM'),
        ('Apr 4', 'TCU', False, '2:00 PM'),
        ('Apr 5', 'TCU', False, '1:00 PM'),
        ('Apr 7', 'Marshall', True, '6:00 PM'),
        ('Apr 10', 'Baylor', False, '6:30 PM'),
        ('Apr 11', 'Baylor', False, '2:00 PM'),
        ('Apr 12', 'Baylor', False, '1:00 PM'),
        ('Apr 14', 'Pitt', False, '6:00 PM'),
        ('Apr 17', 'Arizona State', False, '6:35 PM'),
        ('Apr 18', 'Arizona State', False, '6:35 PM'),
        ('Apr 19', 'Arizona State', False, '5:05 PM'),
        ('Apr 21', 'Marshall', False, '6:00 PM'),
        ('Apr 24', 'Cincinnati', False, '6:00 PM'),
        ('Apr 25', 'Cincinnati', False, '3:00 PM'),
        ('Apr 26', 'Cincinnati', False, '1:00 PM'),
        ('Apr 28', 'Youngstown State', True, '6:00 PM'),
        ('May 1', 'Oklahoma State', False, '6:00 PM'),
        ('May 2', 'Oklahoma State', False, '2:00 PM'),
        ('May 3', 'Oklahoma State', False, '1:00 PM'),
        ('May 5', 'Youngstown State', True, '6:00 PM'),
        ('May 8', 'Kansas', True, '6:00 PM'),
        ('May 9', 'Kansas', True, '2:00 PM'),
        ('May 10', 'Kansas', True, '1:00 PM'),
        ('May 14', 'Utah', False, '6:00 PM'),
        ('May 15', 'Utah', False, '2:00 PM'),
        ('May 16', 'Utah', False, '1:00 PM'),
    ],
    'baylor': [
        ('Feb 13', 'Central Arkansas', True, '6:30 PM'),
        ('Feb 14', 'Central Arkansas', True, '2:00 PM'),
        ('Feb 15', 'Central Arkansas', True, '1:00 PM'),
        ('Feb 17', 'UT Arlington', True, '6:30 PM'),
        ('Feb 20', 'Cal State Fullerton', True, '6:30 PM'),
        ('Feb 21', 'Cal State Fullerton', True, '2:00 PM'),
        ('Feb 22', 'Cal State Fullerton', True, '1:00 PM'),
        ('Feb 24', 'Texas State', True, '6:30 PM'),
        ('Feb 27', 'Wichita State', True, '6:30 PM'),
        ('Feb 28', 'Wichita State', True, '2:00 PM'),
        ('Mar 1', 'Wichita State', True, '1:00 PM'),
        ('Mar 3', 'UT San Antonio', True, '6:30 PM'),
        ('Mar 6', 'Western Illinois', True, '6:30 PM'),
        ('Mar 7', 'Western Illinois', True, '2:00 PM'),
        ('Mar 8', 'Western Illinois', True, '1:00 PM'),
        ('Mar 10', 'Dallas Baptist', True, '6:30 PM'),
        ('Mar 13', 'West Virginia', False, '6:00 PM'),
        ('Mar 14', 'West Virginia', False, '2:00 PM'),
        ('Mar 15', 'West Virginia', False, '1:00 PM'),
        ('Mar 17', 'Abilene Christian', True, '6:30 PM'),
        ('Mar 20', 'TCU', True, '6:30 PM'),
        ('Mar 21', 'TCU', True, '2:00 PM'),
        ('Mar 22', 'TCU', True, '1:00 PM'),
        ('Mar 24', 'Texas State', False, '6:00 PM'),
        ('Mar 27', 'TCU', True, '6:30 PM'),
        ('Mar 28', 'TCU', True, '2:00 PM'),
        ('Mar 29', 'TCU', True, '1:00 PM'),
        ('Mar 31', 'UT San Antonio', False, '6:30 PM'),
        ('Apr 2', 'BYU', True, '6:30 PM'),
        ('Apr 3', 'BYU', True, '6:30 PM'),
        ('Apr 4', 'BYU', True, '1:00 PM'),
        ('Apr 7', 'Dallas Baptist', False, '6:30 PM'),
        ('Apr 10', 'Cincinnati', False, '6:00 PM'),
        ('Apr 11', 'Cincinnati', False, '3:00 PM'),
        ('Apr 12', 'Cincinnati', False, '12:00 PM'),
        ('Apr 14', 'Abilene Christian', False, '6:30 PM'),
        ('Apr 17', 'West Virginia', True, '6:30 PM'),
        ('Apr 18', 'West Virginia', True, '2:00 PM'),
        ('Apr 19', 'West Virginia', True, '1:00 PM'),
        ('Apr 21', 'Sam Houston', True, '6:30 PM'),
        ('Apr 24', 'Arizona State', False, '6:35 PM'),
        ('Apr 25', 'Arizona State', False, '6:35 PM'),
        ('Apr 26', 'Arizona State', False, '1:05 PM'),
        ('Apr 28', 'Sam Houston', False, '6:30 PM'),
        ('May 1', 'Texas Tech', False, '6:00 PM'),
        ('May 2', 'Texas Tech', False, '2:00 PM'),
        ('May 3', 'Texas Tech', False, '1:00 PM'),
        ('May 5', 'UT Arlington', False, '6:00 PM'),
        ('May 8', 'Utah', False, '6:00 PM'),
        ('May 9', 'Utah', False, '2:00 PM'),
        ('May 10', 'Utah', False, '1:00 PM'),
        ('May 14', 'TCU', False, '6:30 PM'),
        ('May 15', 'TCU', False, '6:30 PM'),
        ('May 16', 'TCU', False, '1:00 PM'),
    ],
}

# Note: Colorado and Iowa State don't have baseball programs yet
# Colorado is restarting their program in 2026
# Iowa State doesn't have a baseball program

def main():
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    # First, update all Big 12 teams to have conference='Big 12'
    print("Setting conference='Big 12' for all Big 12 teams...")
    for team_id, team_name in BIG12_TEAMS.items():
        cursor.execute("""
            INSERT INTO teams (id, name, conference) VALUES (?, ?, 'Big 12')
            ON CONFLICT(id) DO UPDATE SET conference = 'Big 12', name = ?
        """, (team_id, team_name, team_name))
    
    games_added = {}
    teams_added = set()
    
    # Process each team's schedule
    for team_id, games in SCHEDULES.items():
        team_games = 0
        for game in games:
            date_str, opponent_name, is_home, time = game
            
            date = parse_date(date_str)
            if not date:
                print(f"  Warning: Could not parse date '{date_str}' for {team_id}")
                continue
            
            opponent_id = normalize_team_name(opponent_name)
            if not opponent_id:
                print(f"  Warning: Could not normalize opponent '{opponent_name}'")
                continue
            
            # Ensure opponent team exists
            cursor.execute("SELECT id FROM teams WHERE id = ?", (opponent_id,))
            if not cursor.fetchone():
                teams_added.add(opponent_id)
                cursor.execute("""
                    INSERT OR IGNORE INTO teams (id, name) VALUES (?, ?)
                """, (opponent_id, opponent_name))
            
            # Determine home/away
            if is_home:
                home_team_id = team_id
                away_team_id = opponent_id
            else:
                home_team_id = opponent_id
                away_team_id = team_id
            
            # Create game ID
            game_id = f"{date}_{away_team_id}_{home_team_id}"
            
            # Check if it's a conference game (both teams in Big 12)
            is_conference = 1 if opponent_id in BIG12_TEAMS else 0
            
            # Insert game (INSERT OR IGNORE to avoid duplicates)
            try:
                cursor.execute("""
                    INSERT OR IGNORE INTO games 
                    (id, date, time, home_team_id, away_team_id, is_conference_game, status)
                    VALUES (?, ?, ?, ?, ?, ?, 'scheduled')
                """, (game_id, date, time, home_team_id, away_team_id, is_conference))
                
                if cursor.rowcount > 0:
                    team_games += 1
            except sqlite3.IntegrityError:
                pass  # Game already exists
        
        games_added[team_id] = team_games
        print(f"  {BIG12_TEAMS.get(team_id, team_id)}: {team_games} games added")
    
    conn.commit()
    
    # Summary
    total_new = sum(games_added.values())
    print(f"\n=== SUMMARY ===")
    print(f"Teams with new games: {len([k for k,v in games_added.items() if v > 0])}")
    print(f"Total new games added: {total_new}")
    print(f"New opponent teams added: {len(teams_added)}")
    
    # Count total games now
    cursor.execute("SELECT COUNT(*) FROM games")
    total_games = cursor.fetchone()[0]
    print(f"Total games in database: {total_games}")
    
    # Count Big 12 teams with games
    cursor.execute("""
        SELECT t.name, COUNT(DISTINCT g.id) as game_count
        FROM teams t
        LEFT JOIN games g ON t.id = g.home_team_id OR t.id = g.away_team_id
        WHERE t.conference = 'Big 12'
        GROUP BY t.id
        ORDER BY game_count DESC
    """)
    print("\nGames per Big 12 team:")
    for row in cursor.fetchall():
        print(f"  {row[0]}: {row[1]} games")
    
    conn.close()


if __name__ == "__main__":
    main()
