#!/usr/bin/env python3
"""Build a minimal Bootstrap Icons subset used by templates.

Outputs:
- web/static/fonts/bootstrap-icons-subset.woff
- web/static/css/bootstrap-icons-subset.css

This trims icon CSS + font payload from full upstream package to only icons
referenced in templates (`class="bi bi-..."`).
"""

from __future__ import annotations

import re
import subprocess
import tempfile
from pathlib import Path

import requests

BOOTSTRAP_ICONS_VERSION = "1.11.1"
CSS_URL = f"https://cdn.jsdelivr.net/npm/bootstrap-icons@{BOOTSTRAP_ICONS_VERSION}/font/bootstrap-icons.css"
WOFF_URL = f"https://cdn.jsdelivr.net/npm/bootstrap-icons@{BOOTSTRAP_ICONS_VERSION}/font/fonts/bootstrap-icons.woff"

ROOT = Path(__file__).resolve().parents[2]
TEMPLATES_DIR = ROOT / "web" / "templates"
OUT_FONT = ROOT / "web" / "static" / "fonts" / "bootstrap-icons-subset.woff"
OUT_CSS = ROOT / "web" / "static" / "css" / "bootstrap-icons-subset.css"

ICON_CLASS_RE = re.compile(r"\bbi\s+bi-([a-z0-9-]+)")
ICON_MAP_RE = re.compile(r"\.bi-([a-z0-9-]+)::before\s*\{\s*content:\s*\"\\([0-9a-fA-F]+)\";\s*\}")


def collect_used_icons() -> set[str]:
    icons: set[str] = set()
    for html in sorted(TEMPLATES_DIR.glob("*.html")):
        text = html.read_text(encoding="utf-8")
        icons.update(ICON_CLASS_RE.findall(text))
    return icons


def fetch_upstream_assets() -> tuple[str, bytes]:
    css_resp = requests.get(CSS_URL, timeout=30)
    css_resp.raise_for_status()

    font_resp = requests.get(WOFF_URL, timeout=30)
    font_resp.raise_for_status()

    return css_resp.text, font_resp.content


def parse_icon_mapping(css_text: str) -> dict[str, str]:
    return {m.group(1): m.group(2).lower() for m in ICON_MAP_RE.finditer(css_text)}


def build_subset_font(full_woff_bytes: bytes, unicodes: list[str]) -> bytes:
    with tempfile.TemporaryDirectory(prefix="bi-subset-") as td:
        td_path = Path(td)
        full_path = td_path / "bootstrap-icons-full.woff"
        out_path = td_path / "bootstrap-icons-subset.woff"

        full_path.write_bytes(full_woff_bytes)

        unicode_arg = ",".join(f"U+{u.upper()}" for u in sorted(set(unicodes)))
        cmd = [
            "pyftsubset",
            str(full_path),
            f"--unicodes={unicode_arg}",
            "--flavor=woff",
            f"--output-file={out_path}",
            "--layout-features=*",
            "--glyph-names",
            "--symbol-cmap",
            "--legacy-cmap",
            "--notdef-glyph",
            "--notdef-outline",
            "--recommended-glyphs",
        ]
        subprocess.check_call(cmd)
        return out_path.read_bytes()


def build_subset_css(icon_names: list[str], icon_map: dict[str, str]) -> str:
    lines: list[str] = []
    lines.append("/* Auto-generated by scripts/ops/build_bootstrap_icon_subset.py */")
    lines.append("@font-face {")
    lines.append("  font-display: swap;")
    lines.append("  font-family: \"bootstrap-icons\";")
    lines.append("  src: url(\"/static/fonts/bootstrap-icons-subset.woff\") format(\"woff\");")
    lines.append("}")
    lines.append("")
    lines.append(".bi::before,")
    lines.append("[class^=\"bi-\"]::before,")
    lines.append("[class*=\" bi-\"]::before {")
    lines.append("  display: inline-block;")
    lines.append("  font-family: bootstrap-icons !important;")
    lines.append("  font-style: normal;")
    lines.append("  font-weight: normal !important;")
    lines.append("  font-variant: normal;")
    lines.append("  text-transform: none;")
    lines.append("  line-height: 1;")
    lines.append("  vertical-align: -.125em;")
    lines.append("  -webkit-font-smoothing: antialiased;")
    lines.append("  -moz-osx-font-smoothing: grayscale;")
    lines.append("}")
    lines.append("")

    for name in sorted(icon_names):
        lines.append(f".bi-{name}::before {{ content: \"\\{icon_map[name]}\"; }}")

    return "\n".join(lines) + "\n"


def main() -> int:
    icons = collect_used_icons()
    if not icons:
        raise RuntimeError("No icon classes found in templates")

    css_text, full_woff = fetch_upstream_assets()
    icon_map = parse_icon_mapping(css_text)

    missing = sorted(icon for icon in icons if icon not in icon_map)
    if missing:
        raise RuntimeError(
            f"Missing {len(missing)} icon(s) in upstream bootstrap-icons@{BOOTSTRAP_ICONS_VERSION}: {missing}"
        )

    subset_font = build_subset_font(full_woff, [icon_map[i] for i in icons])
    subset_css = build_subset_css(sorted(icons), icon_map)

    OUT_FONT.parent.mkdir(parents=True, exist_ok=True)
    OUT_CSS.parent.mkdir(parents=True, exist_ok=True)

    OUT_FONT.write_bytes(subset_font)
    OUT_CSS.write_text(subset_css, encoding="utf-8")

    print(
        f"Built icon subset: {len(icons)} icons | "
        f"font {len(subset_font)} bytes -> {OUT_FONT} | css {len(subset_css.encode('utf-8'))} bytes -> {OUT_CSS}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
