"""Bet selection v2 modules with backwards-compatible re-exports."""

from .cli import main, print_analysis
from .record import DB_PATH, build_parlay, record_bets
from .risk import (
    BASE_BET,
    RISK_BANKROLL,
    RISK_BANKROLL_PEAK,
    RISK_CALIBRATION_PROXY_DEFAULT,
    RISK_CORRELATION_CAP_ENABLED,
    RISK_COVERAGE_PROXY_DEFAULT,
    RISK_DRAWDOWN_FRACTION_MULTIPLIER,
    RISK_DRAWDOWN_THRESHOLD,
    RISK_ENGINE_MODE,
    RISK_FIXED_STAKE,
    RISK_KELLY_FRACTION,
    RISK_MAX_EXPOSURE_PER_CONFERENCE,
    RISK_MAX_EXPOSURE_PER_DAY,
    RISK_MAX_EXPOSURE_PER_TEAM,
    RISK_MAX_STAKE,
    RISK_MIN_STAKE,
    RISK_WEIGHT_CALIBRATION,
    RISK_WEIGHT_CONSENSUS,
    RISK_WEIGHT_COVERAGE,
    american_to_prob,
    apply_correlation_caps,
    bet_exposure_clusters,
    clamp01,
    consensus_strength_score,
    drawdown_kelly_multiplier,
    edge_quality_score,
    get_drawdown_pct,
    kelly_fraction,
    proxy_calibration_confidence,
    proxy_feature_coverage,
    raw_kelly_fraction,
    suggest_stake_for_bet,
)
from .selection import (
    API_URL,
    MAX_CONSENSUS_PER_DAY,
    MAX_EV_PER_DAY,
    MAX_TOTALS_PER_DAY,
    ML_CONSENSUS_MIN,
    ML_EDGE_THRESHOLD,
    ML_EDGE_UNDERDOG,
    ML_MAX_FAVORITE,
    ML_MAX_FAVORITE_CONSENSUS,
    ML_MAX_MODEL_PROB,
    ML_MIN_MODEL_PROB,
    ML_MIN_UNDERDOG,
    SPREADS_ENABLED,
    TOTALS_EDGE_THRESHOLD,
    TOTALS_MIN_CONFIDENCE,
    analyze_games,
)

