#!/usr/bin/env python3
"""
Load full 2026 schedules for all 17 ACC teams.
Schedule data is embedded for reliability (similar to SEC loader).

ACC Teams: Boston College, California, Clemson, Duke, Florida State, Georgia Tech,
Louisville, Miami, NC State, North Carolina, Notre Dame, Pittsburgh, SMU, Stanford,
Syracuse, Virginia, Wake Forest
"""

import sqlite3
import re
import sys
from datetime import datetime
from pathlib import Path

_scripts_dir = Path(__file__).parent
# sys.path.insert(0, str(_scripts_dir))  # Removed by cleanup

from scripts.database import get_connection, add_team

DB_PATH = "~/college-baseball-predictor/data/baseball.db"

# All 17 ACC teams with their standard IDs
ACC_TEAMS = {
    'boston-college': 'Boston College',
    'california': 'California',
    'clemson': 'Clemson',
    'duke': 'Duke',
    'florida-state': 'Florida State',
    'georgia-tech': 'Georgia Tech',
    'louisville': 'Louisville',
    'miami-fl': 'Miami',
    'nc-state': 'NC State',
    'north-carolina': 'North Carolina',
    'notre-dame': 'Notre Dame',
    'pittsburgh': 'Pittsburgh',
    'smu': 'SMU',
    'stanford': 'Stanford',
    'syracuse': 'Syracuse',
    'virginia': 'Virginia',
    'wake-forest': 'Wake Forest'
}

# Team name to ID mapping
TEAM_NAME_MAP = {
    # ACC teams
    'boston college': 'boston-college',
    'bc': 'boston-college',
    'california': 'california',
    'cal': 'california',
    'clemson': 'clemson',
    'duke': 'duke',
    'florida state': 'florida-state',
    'fsu': 'florida-state',
    'georgia tech': 'georgia-tech',
    'louisville': 'louisville',
    'miami': 'miami-fl',
    'nc state': 'nc-state',
    'north carolina': 'north-carolina',
    'unc': 'north-carolina',
    'notre dame': 'notre-dame',
    'pittsburgh': 'pittsburgh',
    'pitt': 'pittsburgh',
    'smu': 'smu',
    'stanford': 'stanford',
    'syracuse': 'syracuse',
    'virginia': 'virginia',
    'uva': 'virginia',
    'wake forest': 'wake-forest',
    
    # SEC teams  
    'alabama': 'alabama',
    'arkansas': 'arkansas',
    'auburn': 'auburn',
    'florida': 'florida',
    'georgia': 'georgia',
    'kentucky': 'kentucky',
    'lsu': 'lsu',
    'mississippi state': 'mississippi-state',
    'missouri': 'missouri',
    'oklahoma': 'oklahoma',
    'ole miss': 'ole-miss',
    'south carolina': 'south-carolina',
    'tennessee': 'tennessee',
    'texas': 'texas',
    'texas a&m': 'texas-am',
    'vanderbilt': 'vanderbilt',
    
    # Common opponents
    'army': 'army',
    'army west point': 'army',
    'charlotte': 'charlotte',
    'bryant': 'bryant',
    'presbyterian': 'presbyterian',
    'east carolina': 'east-carolina',
    'james madison': 'james-madison',
    'jacksonville': 'jacksonville',
    'citadel': 'citadel',
    'the citadel': 'citadel',
    'mercer': 'mercer',
    'indiana': 'indiana',
    'longwood': 'longwood',
    'michigan': 'michigan',
    'michigan state': 'michigan-state',
    'nebraska': 'nebraska',
    'texas tech': 'texas-tech',
    'oklahoma state': 'oklahoma-state',
    'tcu': 'tcu',
    'rutgers': 'rutgers',
    'etsu': 'etsu',
    'vcu': 'vcu',
    'marshall': 'marshall',
    'radford': 'radford',
    'liberty': 'liberty',
    'uncg': 'uncg',
    'bethune-cookman': 'bethune-cookman',
    'stetson': 'stetson',
    'usf': 'usf',
    'florida atlantic': 'fau',
    'fau': 'fau',
    'lehigh': 'lehigh',
    'delaware': 'delaware',
    'william & mary': 'william-mary',
    'william and mary': 'william-mary',
    'virginia tech': 'virginia-tech',
    'old dominion': 'old-dominion',
    'coastal carolina': 'coastal-carolina',
    'high point': 'high-point',
    'elon': 'elon',
    'wofford': 'wofford',
    'appalachian state': 'appalachian-state',
    'western carolina': 'western-carolina',
    'furman': 'furman',
    'towson': 'towson',
    'maine': 'maine',
    'hartford': 'hartford',
    'uconn': 'uconn',
    'connecticut': 'uconn',
    'rhode island': 'rhode-island',
    'st. johns': 'st-johns',
    'iona': 'iona',
    'fordham': 'fordham',
    'quinnipiac': 'quinnipiac',
    'penn': 'penn',
    'penn state': 'penn-state',
    'maryland': 'maryland',
    'kent state': 'kent-state',
    'wright state': 'wright-state',
    'ohio': 'ohio',
    'ohio state': 'ohio-state',
    'toledo': 'toledo',
    'bowling green': 'bowling-green',
    'xavier': 'xavier',
    'dayton': 'dayton',
    'illinois': 'illinois',
    'northwestern': 'northwestern',
    'uic': 'uic',
    'san diego': 'san-diego',
    'san diego state': 'san-diego-state',
    'san jose state': 'san-jose-state',
    'fresno state': 'fresno-state',
    'oregon': 'oregon',
    'oregon state': 'oregon-state',
    'washington': 'washington',
    'washington state': 'washington-state',
    'ucla': 'ucla',
    'usc': 'usc',
    'arizona': 'arizona',
    'arizona state': 'arizona-state',
    'byu': 'byu',
    'utah': 'utah',
    'rice': 'rice',
    'houston': 'houston',
    'tulane': 'tulane',
    'lemoyne': 'lemoyne',
    'le moyne': 'lemoyne',
    'columbia': 'columbia',
    'harvard': 'harvard',
    'yale': 'yale',
    'dartmouth': 'dartmouth',
    'brown': 'brown',
    'cornell': 'cornell',
    'princeton': 'princeton',
    'cincinnati': 'cincinnati',
    'minnesota': 'minnesota',
    'iowa': 'iowa',
    'unc wilmington': 'uncw',
    'uncw': 'uncw',
}


def normalize_team_name(name):
    """Convert team name to standard ID."""
    if not name:
        return None
    
    name_lower = name.lower().strip()
    name_lower = re.sub(r'^#?\d+\s+', '', name_lower)
    name_lower = re.sub(r'^no\.\s*\d+\s+', '', name_lower)
    name_lower = name_lower.strip()
    
    if name_lower in TEAM_NAME_MAP:
        return TEAM_NAME_MAP[name_lower]
    
    team_id = re.sub(r'[^a-z0-9]+', '-', name_lower).strip('-')
    return team_id


def parse_date(date_str, year=2026):
    """Parse date string like 'Feb 13' into ISO format."""
    date_str = date_str.strip()
    date_str = re.sub(r'\([^)]+\)', '', date_str)
    date_str = re.sub(r'^(Mon|Tue|Wed|Thu|Fri|Sat|Sun)(day)?,?\s*\.?\s*', '', date_str, flags=re.IGNORECASE)
    date_str = date_str.strip()
    
    month_map = {
        'jan': 1, 'feb': 2, 'mar': 3, 'apr': 4, 'may': 5, 'jun': 6,
        'jul': 7, 'aug': 8, 'sep': 9, 'oct': 10, 'nov': 11, 'dec': 12
    }
    
    match = re.match(r'([A-Za-z]+)\.?\s+(\d+)', date_str)
    if match:
        month_str, day = match.groups()
        month = month_map.get(month_str.lower()[:3])
        if month:
            return f"{year}-{month:02d}-{int(day):02d}"
    
    return None


# ACC 2026 Schedule Data
# Format: list of (date_str, opponent, is_home, time)
SCHEDULES = {
    'clemson': [
        ('Feb 13', 'Army', True, '4:00 PM'),
        ('Feb 14', 'Army', True, '2:00 PM'),
        ('Feb 14', 'Army', True, '5:00 PM'),
        ('Feb 17', 'Charlotte', True, '4:00 PM'),
        ('Feb 20', 'Bryant', True, '4:00 PM'),
        ('Feb 21', 'Bryant', True, '2:00 PM'),
        ('Feb 22', 'Bryant', True, '1:00 PM'),
        ('Feb 24', 'Presbyterian', True, '4:00 PM'),
        ('Feb 27', 'South Carolina', False, '7:00 PM'),
        ('Feb 28', 'South Carolina', False, '3:00 PM'),
        ('Mar 1', 'South Carolina', False, '3:00 PM'),
        ('Mar 3', 'Wofford', True, '4:00 PM'),
        ('Mar 6', 'Virginia', True, '6:00 PM'),
        ('Mar 7', 'Virginia', True, '2:00 PM'),
        ('Mar 8', 'Virginia', True, '1:00 PM'),
        ('Mar 10', 'Georgia', True, '6:00 PM'),
        ('Mar 13', 'Boston College', False, '3:00 PM'),
        ('Mar 14', 'Boston College', False, '12:00 PM'),
        ('Mar 15', 'Boston College', False, '1:00 PM'),
        ('Mar 17', 'Furman', True, '6:00 PM'),
        ('Mar 20', 'NC State', True, '6:00 PM'),
        ('Mar 21', 'NC State', True, '3:00 PM'),
        ('Mar 22', 'NC State', True, '1:00 PM'),
        ('Mar 24', 'Coastal Carolina', False, '6:00 PM'),
        ('Mar 27', 'Wake Forest', False, '6:00 PM'),
        ('Mar 28', 'Wake Forest', False, '3:00 PM'),
        ('Mar 29', 'Wake Forest', False, '1:00 PM'),
        ('Mar 31', 'Western Carolina', True, '6:00 PM'),
        ('Apr 3', 'Duke', True, '6:00 PM'),
        ('Apr 4', 'Duke', True, '3:00 PM'),
        ('Apr 5', 'Duke', True, '1:00 PM'),
        ('Apr 7', 'Georgia Southern', True, '6:00 PM'),
        ('Apr 10', 'North Carolina', False, '6:00 PM'),
        ('Apr 11', 'North Carolina', False, '2:00 PM'),
        ('Apr 12', 'North Carolina', False, '12:30 PM'),
        ('Apr 14', 'College of Charleston', True, '6:00 PM'),
        ('Apr 17', 'Georgia Tech', True, '6:00 PM'),
        ('Apr 18', 'Georgia Tech', True, '3:00 PM'),
        ('Apr 19', 'Georgia Tech', True, '1:00 PM'),
        ('Apr 22', 'Western Carolina', False, '6:00 PM'),
        ('Apr 24', 'Florida State', False, '6:00 PM'),
        ('Apr 25', 'Florida State', False, '4:00 PM'),
        ('Apr 26', 'Florida State', False, '1:00 PM'),
        ('Apr 28', 'Coastal Carolina', True, '6:00 PM'),
        ('May 1', 'Louisville', True, '6:00 PM'),
        ('May 2', 'Louisville', True, '3:00 PM'),
        ('May 3', 'Louisville', True, '1:00 PM'),
        ('May 5', 'College of Charleston', False, '6:00 PM'),
        ('May 8', 'Notre Dame', False, '6:00 PM'),
        ('May 9', 'Notre Dame', False, '3:00 PM'),
        ('May 10', 'Notre Dame', False, '1:00 PM'),
        ('May 14', 'Virginia Tech', True, '6:00 PM'),
        ('May 15', 'Virginia Tech', True, '3:00 PM'),
        ('May 16', 'Virginia Tech', True, '1:00 PM'),
    ],
    'florida-state': [
        ('Feb 13', 'James Madison', True, '6:00 PM'),
        ('Feb 14', 'James Madison', True, '2:00 PM'),
        ('Feb 15', 'James Madison', True, '1:00 PM'),
        ('Feb 17', 'Jacksonville', False, '6:00 PM'),
        ('Feb 20', 'Michigan', False, '12:00 PM'),  # Arlington
        ('Feb 21', 'Auburn', False, '4:00 PM'),
        ('Feb 22', 'Nebraska', False, '3:30 PM'),
        ('Feb 27', 'Citadel', True, '12:00 PM'),
        ('Feb 28', 'Citadel', True, '2:00 PM'),
        ('Mar 1', 'Citadel', True, '1:00 PM'),
        ('Mar 3', 'Jacksonville', True, '5:00 PM'),
        ('Mar 4', 'Mercer', True, '5:00 PM'),
        ('Mar 6', 'Virginia Tech', True, '6:00 PM'),
        ('Mar 7', 'Virginia Tech', True, '4:00 PM'),
        ('Mar 8', 'Virginia Tech', True, '1:00 PM'),
        ('Mar 10', 'Florida', False, '6:30 PM'),
        ('Mar 13', 'Wake Forest', False, '6:00 PM'),
        ('Mar 14', 'Wake Forest', False, '4:00 PM'),
        ('Mar 15', 'Wake Forest', False, '3:00 PM'),
        ('Mar 17', 'Bethune-Cookman', True, '6:00 PM'),
        ('Mar 20', 'Miami', True, '6:00 PM'),
        ('Mar 21', 'Miami', True, '4:00 PM'),
        ('Mar 22', 'Miami', True, '1:00 PM'),
        ('Mar 24', 'Stetson', True, '6:00 PM'),
        ('Mar 27', 'NC State', True, '6:00 PM'),
        ('Mar 28', 'NC State', True, '4:00 PM'),
        ('Mar 29', 'NC State', True, '1:00 PM'),
        ('Mar 31', 'Florida', True, '6:00 PM'),
        ('Apr 3', 'Georgia Tech', False, '6:00 PM'),
        ('Apr 4', 'Georgia Tech', False, '2:00 PM'),
        ('Apr 5', 'Georgia Tech', False, '1:00 PM'),
        ('Apr 7', 'Florida', True, '7:00 PM'),
        ('Apr 10', 'Duke', True, '6:00 PM'),
        ('Apr 11', 'Duke', True, '4:00 PM'),
        ('Apr 12', 'Duke', True, '1:00 PM'),
        ('Apr 14', 'Stetson', True, '6:00 PM'),
        ('Apr 17', 'Stanford', False, '9:00 PM'),
        ('Apr 18', 'Stanford', False, '6:00 PM'),
        ('Apr 19', 'Stanford', False, '4:00 PM'),
        ('Apr 21', 'Jacksonville', True, '6:00 PM'),
        ('Apr 24', 'Clemson', True, '6:00 PM'),
        ('Apr 25', 'Clemson', True, '4:00 PM'),
        ('Apr 26', 'Clemson', True, '1:00 PM'),
        ('Apr 29', 'USF', True, '4:00 PM'),
        ('May 1', 'Pittsburgh', True, '6:00 PM'),
        ('May 2', 'Pittsburgh', True, '4:00 PM'),
        ('May 3', 'Pittsburgh', True, '1:00 PM'),
        ('May 5', 'Jacksonville', True, '6:00 PM'),
        ('May 8', 'Louisville', False, '6:00 PM'),
        ('May 9', 'Louisville', False, '3:00 PM'),
        ('May 10', 'Louisville', False, '1:00 PM'),
        ('May 14', 'North Carolina', True, '6:00 PM'),
        ('May 15', 'North Carolina', True, '6:00 PM'),
        ('May 16', 'North Carolina', True, '1:00 PM'),
    ],
    'north-carolina': [
        ('Feb 13', 'Indiana', True, '4:00 PM'),
        ('Feb 14', 'Indiana', True, '12:00 PM'),
        ('Feb 14', 'Indiana', True, '4:00 PM'),
        ('Feb 17', 'Longwood', True, '4:00 PM'),
        ('Feb 18', 'Longwood', True, '4:00 PM'),
        ('Feb 20', 'East Carolina', False, '5:00 PM'),
        ('Feb 21', 'Duke', False, '2:00 PM'),  # Durham
        ('Feb 22', 'NC State', True, '1:00 PM'),
        ('Feb 24', 'VCU', True, '4:00 PM'),
        ('Feb 25', 'VCU', True, '4:00 PM'),
        ('Feb 27', 'Le Moyne', True, '4:00 PM'),
        ('Feb 28', 'Le Moyne', True, '2:00 PM'),
        ('Mar 1', 'Le Moyne', True, '1:00 PM'),
        ('Mar 3', 'Campbell', True, '4:00 PM'),
        ('Mar 6', 'Virginia', True, '6:00 PM'),
        ('Mar 7', 'Virginia', True, '2:00 PM'),
        ('Mar 8', 'Virginia', True, '1:00 PM'),
        ('Mar 10', 'Elon', True, '4:00 PM'),
        ('Mar 13', 'Pittsburgh', False, '6:00 PM'),
        ('Mar 14', 'Pittsburgh', False, '2:00 PM'),
        ('Mar 15', 'Pittsburgh', False, '1:00 PM'),
        ('Mar 17', 'High Point', True, '4:00 PM'),
        ('Mar 20', 'Georgia Tech', True, '6:00 PM'),
        ('Mar 21', 'Georgia Tech', True, '2:00 PM'),
        ('Mar 22', 'Georgia Tech', True, '1:00 PM'),
        ('Mar 24', 'South Carolina', False, '6:30 PM'),  # Charlotte
        ('Mar 27', 'Notre Dame', False, '6:30 PM'),
        ('Mar 28', 'Notre Dame', False, '3:00 PM'),
        ('Mar 29', 'Notre Dame', False, '1:00 PM'),
        ('Mar 31', 'East Carolina', True, '6:00 PM'),
        ('Apr 3', 'Boston College', True, '6:00 PM'),
        ('Apr 4', 'Boston College', True, '2:00 PM'),
        ('Apr 5', 'Boston College', True, '1:00 PM'),
        ('Apr 7', 'Appalachian State', True, '6:00 PM'),
        ('Apr 10', 'Clemson', True, '6:00 PM'),
        ('Apr 11', 'Clemson', True, '2:00 PM'),
        ('Apr 12', 'Clemson', True, '12:30 PM'),
        ('Apr 14', 'Campbell', False, '6:00 PM'),
        ('Apr 17', 'Wake Forest', False, '6:00 PM'),
        ('Apr 18', 'Wake Forest', False, '3:00 PM'),
        ('Apr 19', 'Wake Forest', False, '1:00 PM'),
        ('Apr 21', 'Charlotte', True, '6:00 PM'),
        ('Apr 23', 'Duke', True, '7:00 PM'),
        ('Apr 25', 'Virginia', False, '3:00 PM'),
        ('Apr 26', 'Virginia', False, '1:00 PM'),
        ('Apr 28', 'Western Carolina', True, '6:00 PM'),
        ('May 1', 'Duke', False, '6:00 PM'),
        ('May 2', 'Duke', False, '3:00 PM'),
        ('May 3', 'Duke', False, '1:00 PM'),
        ('May 5', 'UNC Asheville', True, '6:00 PM'),
        ('May 8', 'NC State', False, '6:00 PM'),
        ('May 9', 'NC State', False, '2:00 PM'),
        ('May 10', 'NC State', False, '1:00 PM'),
        ('May 12', 'UNC Wilmington', False, '6:00 PM'),
        ('May 14', 'Florida State', False, '6:00 PM'),
        ('May 15', 'Florida State', False, '6:00 PM'),
        ('May 16', 'Florida State', False, '1:00 PM'),
    ],
    'duke': [
        ('Feb 13', 'Lehigh', True, '3:00 PM'),
        ('Feb 14', 'Lehigh', True, '12:00 PM'),
        ('Feb 15', 'Lehigh', True, '1:00 PM'),
        ('Feb 17', 'UNC Asheville', True, '4:00 PM'),
        ('Feb 20', 'Towson', True, '4:00 PM'),
        ('Feb 21', 'North Carolina', True, '2:00 PM'),  # Durham rivalry
        ('Feb 22', 'Towson', True, '1:00 PM'),
        ('Feb 27', 'Columbia', True, '4:00 PM'),
        ('Feb 28', 'Columbia', True, '2:00 PM'),
        ('Mar 1', 'Columbia', True, '1:00 PM'),
        ('Mar 3', 'Elon', True, '4:00 PM'),
        ('Mar 6', 'NC State', True, '6:00 PM'),
        ('Mar 7', 'NC State', True, '2:00 PM'),
        ('Mar 8', 'NC State', True, '1:00 PM'),
        ('Mar 10', 'High Point', True, '4:00 PM'),
        ('Mar 13', 'Wake Forest', True, '6:00 PM'),
        ('Mar 14', 'Wake Forest', True, '2:00 PM'),
        ('Mar 15', 'Wake Forest', True, '1:00 PM'),
        ('Mar 17', 'Davidson', True, '4:00 PM'),
        ('Mar 20', 'Virginia Tech', False, '6:00 PM'),
        ('Mar 21', 'Virginia Tech', False, '3:00 PM'),
        ('Mar 22', 'Virginia Tech', False, '1:00 PM'),
        ('Mar 24', 'Coastal Carolina', True, '6:00 PM'),
        ('Mar 27', 'Stanford', True, '6:00 PM'),
        ('Mar 28', 'Stanford', True, '2:00 PM'),
        ('Mar 29', 'Stanford', True, '1:00 PM'),
        ('Mar 31', 'UNCW', True, '6:00 PM'),
        ('Apr 3', 'Clemson', False, '6:00 PM'),
        ('Apr 4', 'Clemson', False, '3:00 PM'),
        ('Apr 5', 'Clemson', False, '1:00 PM'),
        ('Apr 7', 'UNC Greensboro', True, '6:00 PM'),
        ('Apr 10', 'Florida State', False, '6:00 PM'),
        ('Apr 11', 'Florida State', False, '4:00 PM'),
        ('Apr 12', 'Florida State', False, '1:00 PM'),
        ('Apr 14', 'East Carolina', True, '6:00 PM'),
        ('Apr 17', 'Louisville', True, '6:00 PM'),
        ('Apr 18', 'Louisville', True, '2:00 PM'),
        ('Apr 19', 'Louisville', True, '1:00 PM'),
        ('Apr 23', 'North Carolina', False, '7:00 PM'),
        ('Apr 24', 'Virginia', True, '6:00 PM'),
        ('Apr 25', 'Virginia', True, '2:00 PM'),
        ('Apr 26', 'Virginia', True, '1:00 PM'),
        ('Apr 28', 'VCU', False, '6:00 PM'),
        ('May 1', 'North Carolina', True, '6:00 PM'),
        ('May 2', 'North Carolina', True, '3:00 PM'),
        ('May 3', 'North Carolina', True, '1:00 PM'),
        ('May 5', 'Campbell', True, '6:00 PM'),
        ('May 8', 'Miami', False, '7:00 PM'),
        ('May 9', 'Miami', False, '6:00 PM'),
        ('May 10', 'Miami', False, '1:00 PM'),
        ('May 14', 'Georgia Tech', True, '6:00 PM'),
        ('May 15', 'Georgia Tech', True, '3:00 PM'),
        ('May 16', 'Georgia Tech', True, '1:00 PM'),
    ],
    'louisville': [
        ('Feb 13', 'Michigan State', True, '2:00 PM'),
        ('Feb 14', 'Michigan State', True, '1:00 PM'),
        ('Feb 15', 'Michigan State', True, '12:00 PM'),
        ('Feb 17', 'Northern Kentucky', True, '3:00 PM'),
        ('Feb 20', 'Nebraska', False, '4:00 PM'),  # Arlington
        ('Feb 21', 'Michigan', False, '12:00 PM'),
        ('Feb 22', 'Auburn', False, '11:30 AM'),
        ('Feb 24', 'Eastern Kentucky', True, '3:00 PM'),
        ('Feb 27', 'Xavier', True, '3:00 PM'),
        ('Feb 28', 'Xavier', True, '1:00 PM'),
        ('Mar 1', 'Xavier', True, '1:00 PM'),
        ('Mar 3', 'Wright State', True, '3:00 PM'),
        ('Mar 6', 'Ohio', True, '3:00 PM'),
        ('Mar 7', 'Ohio', True, '1:00 PM'),
        ('Mar 8', 'Ohio', True, '1:00 PM'),
        ('Mar 10', 'Bowling Green', True, '3:00 PM'),
        ('Mar 13', 'Pittsburgh', True, '6:00 PM'),
        ('Mar 14', 'Pittsburgh', True, '2:00 PM'),
        ('Mar 15', 'Pittsburgh', True, '1:00 PM'),
        ('Mar 17', 'Indiana State', True, '3:00 PM'),
        ('Mar 20', 'Notre Dame', True, '6:00 PM'),
        ('Mar 21', 'Notre Dame', True, '2:00 PM'),
        ('Mar 22', 'Notre Dame', True, '1:00 PM'),
        ('Mar 24', 'Dayton', True, '3:00 PM'),
        ('Mar 27', 'Boston College', True, '6:00 PM'),
        ('Mar 28', 'Boston College', True, '2:00 PM'),
        ('Mar 29', 'Boston College', True, '1:00 PM'),
        ('Mar 31', 'Northwestern', True, '6:00 PM'),
        ('Apr 3', 'Virginia', False, '6:00 PM'),
        ('Apr 4', 'Virginia', False, '2:00 PM'),
        ('Apr 5', 'Virginia', False, '1:00 PM'),
        ('Apr 7', 'Kentucky', False, '5:30 PM'),
        ('Apr 10', 'SMU', True, '6:00 PM'),
        ('Apr 11', 'SMU', True, '2:00 PM'),
        ('Apr 12', 'SMU', True, '1:00 PM'),
        ('Apr 14', 'Cincinnati', True, '3:00 PM'),
        ('Apr 17', 'Duke', False, '6:00 PM'),
        ('Apr 18', 'Duke', False, '2:00 PM'),
        ('Apr 19', 'Duke', False, '1:00 PM'),
        ('Apr 21', 'Kentucky', True, '7:00 PM'),
        ('Apr 24', 'California', False, '9:00 PM'),
        ('Apr 25', 'California', False, '5:00 PM'),
        ('Apr 26', 'California', False, '4:00 PM'),
        ('Apr 28', 'Western Kentucky', True, '6:00 PM'),
        ('May 1', 'Clemson', False, '6:00 PM'),
        ('May 2', 'Clemson', False, '3:00 PM'),
        ('May 3', 'Clemson', False, '1:00 PM'),
        ('May 5', 'Vanderbilt', False, '8:00 PM'),
        ('May 7', 'Miami', False, '7:00 PM'),
        ('May 8', 'Miami', False, '7:00 PM'),
        ('May 9', 'Miami', False, '2:00 PM'),
        ('May 14', 'Wake Forest', True, '6:00 PM'),
        ('May 15', 'Wake Forest', True, '6:00 PM'),
        ('May 16', 'Wake Forest', True, '1:00 PM'),
    ],
    'miami-fl': [
        ('Feb 13', 'FAU', True, '7:00 PM'),
        ('Feb 14', 'FAU', True, '6:00 PM'),
        ('Feb 15', 'FAU', True, '1:00 PM'),
        ('Feb 17', 'USF', True, '7:00 PM'),
        ('Feb 20', 'Stetson', True, '6:00 PM'),
        ('Feb 21', 'Stetson', True, '3:00 PM'),
        ('Feb 22', 'Stetson', True, '1:00 PM'),
        ('Feb 24', 'FIU', True, '6:00 PM'),
        ('Feb 27', 'UCF', True, '7:00 PM'),
        ('Feb 28', 'UCF', True, '6:00 PM'),
        ('Mar 1', 'UCF', True, '1:00 PM'),
        ('Mar 3', 'Florida', False, '6:00 PM'),
        ('Mar 6', 'Wake Forest', True, '7:00 PM'),
        ('Mar 7', 'Wake Forest', True, '6:00 PM'),
        ('Mar 8', 'Wake Forest', True, '1:00 PM'),
        ('Mar 10', 'Bethune-Cookman', True, '6:00 PM'),
        ('Mar 13', 'Syracuse', False, '3:00 PM'),  # Florida game
        ('Mar 14', 'Syracuse', False, '12:00 PM'),
        ('Mar 15', 'Syracuse', False, '1:00 PM'),
        ('Mar 17', 'Jacksonville', True, '6:00 PM'),
        ('Mar 20', 'Florida State', False, '6:00 PM'),
        ('Mar 21', 'Florida State', False, '4:00 PM'),
        ('Mar 22', 'Florida State', False, '1:00 PM'),
        ('Mar 24', 'FIU', False, '6:00 PM'),
        ('Mar 27', 'Pittsburgh', True, '7:00 PM'),
        ('Mar 28', 'Pittsburgh', True, '6:00 PM'),
        ('Mar 29', 'Pittsburgh', True, '1:00 PM'),
        ('Mar 31', 'USF', False, '6:30 PM'),
        ('Apr 3', 'Virginia Tech', True, '7:00 PM'),
        ('Apr 4', 'Virginia Tech', True, '6:00 PM'),
        ('Apr 5', 'Virginia Tech', True, '1:00 PM'),
        ('Apr 7', 'FAU', False, '6:30 PM'),
        ('Apr 10', 'Notre Dame', True, '7:00 PM'),
        ('Apr 11', 'Notre Dame', True, '6:00 PM'),
        ('Apr 12', 'Notre Dame', True, '1:00 PM'),
        ('Apr 14', 'UCF', False, '6:00 PM'),
        ('Apr 17', 'NC State', False, '6:30 PM'),
        ('Apr 18', 'NC State', False, '2:00 PM'),
        ('Apr 19', 'NC State', False, '1:00 PM'),
        ('Apr 22', 'FAU', True, '6:00 PM'),
        ('Apr 24', 'California', True, '7:00 PM'),
        ('Apr 25', 'California', True, '6:00 PM'),
        ('Apr 26', 'California', True, '1:00 PM'),
        ('Apr 28', 'FIU', True, '6:00 PM'),
        ('May 1', 'Boston College', False, '3:00 PM'),
        ('May 2', 'Boston College', False, '12:00 PM'),
        ('May 3', 'Boston College', False, '1:00 PM'),
        ('May 5', 'Florida', True, '6:00 PM'),
        ('May 7', 'Louisville', True, '7:00 PM'),
        ('May 8', 'Louisville', True, '7:00 PM'),
        ('May 9', 'Louisville', True, '2:00 PM'),
        ('May 14', 'Virginia', True, '7:00 PM'),
        ('May 15', 'Virginia', True, '6:00 PM'),
        ('May 16', 'Virginia', True, '1:00 PM'),
    ],
    'virginia': [
        ('Feb 13', 'Delaware', True, '3:00 PM'),
        ('Feb 14', 'Delaware', True, '1:00 PM'),
        ('Feb 15', 'Delaware', True, '1:00 PM'),
        ('Feb 17', 'VMI', True, '4:00 PM'),
        ('Feb 20', 'William & Mary', True, '3:00 PM'),
        ('Feb 21', 'William & Mary', True, '1:00 PM'),
        ('Feb 22', 'William & Mary', True, '1:00 PM'),
        ('Feb 24', 'VCU', True, '4:00 PM'),
        ('Feb 27', 'Liberty', True, '4:00 PM'),
        ('Feb 28', 'Liberty', True, '1:00 PM'),
        ('Mar 1', 'Liberty', True, '1:00 PM'),
        ('Mar 3', 'James Madison', True, '4:00 PM'),
        ('Mar 6', 'Clemson', False, '6:00 PM'),
        ('Mar 7', 'Clemson', False, '2:00 PM'),
        ('Mar 8', 'Clemson', False, '1:00 PM'),
        ('Mar 10', 'Radford', True, '4:00 PM'),
        ('Mar 13', 'Virginia Tech', True, '4:00 PM'),
        ('Mar 14', 'Virginia Tech', True, '1:00 PM'),
        ('Mar 15', 'Virginia Tech', True, '1:00 PM'),
        ('Mar 17', 'Richmond', True, '4:00 PM'),
        ('Mar 20', 'Boston College', False, '3:00 PM'),
        ('Mar 21', 'Boston College', False, '12:00 PM'),
        ('Mar 22', 'Boston College', False, '1:00 PM'),
        ('Mar 24', 'Old Dominion', True, '6:00 PM'),
        ('Mar 27', 'Georgia Tech', True, '6:00 PM'),
        ('Mar 28', 'Georgia Tech', True, '2:00 PM'),
        ('Mar 29', 'Georgia Tech', True, '1:00 PM'),
        ('Mar 31', 'VMI', False, '6:00 PM'),
        ('Apr 3', 'Louisville', True, '6:00 PM'),
        ('Apr 4', 'Louisville', True, '2:00 PM'),
        ('Apr 5', 'Louisville', True, '1:00 PM'),
        ('Apr 7', 'Longwood', True, '6:00 PM'),
        ('Apr 10', 'Wake Forest', False, '6:00 PM'),
        ('Apr 11', 'Wake Forest', False, '3:00 PM'),
        ('Apr 12', 'Wake Forest', False, '1:00 PM'),
        ('Apr 14', 'Richmond', False, '6:00 PM'),
        ('Apr 17', 'Syracuse', True, '6:00 PM'),
        ('Apr 18', 'Syracuse', True, '2:00 PM'),
        ('Apr 19', 'Syracuse', True, '1:00 PM'),
        ('Apr 21', 'VCU', False, '6:00 PM'),
        ('Apr 24', 'Duke', False, '6:00 PM'),
        ('Apr 25', 'North Carolina', True, '3:00 PM'),
        ('Apr 26', 'North Carolina', True, '1:00 PM'),
        ('Apr 28', 'Old Dominion', False, '6:00 PM'),
        ('May 1', 'NC State', True, '6:00 PM'),
        ('May 2', 'NC State', True, '2:00 PM'),
        ('May 3', 'NC State', True, '1:00 PM'),
        ('May 5', 'James Madison', False, '6:00 PM'),
        ('May 8', 'Pittsburgh', False, '6:00 PM'),
        ('May 9', 'Pittsburgh', False, '2:00 PM'),
        ('May 10', 'Pittsburgh', False, '1:00 PM'),
        ('May 14', 'Miami', False, '7:00 PM'),
        ('May 15', 'Miami', False, '6:00 PM'),
        ('May 16', 'Miami', False, '1:00 PM'),
    ],
    'wake-forest': [
        ('Feb 13', 'Rhode Island', True, '4:00 PM'),
        ('Feb 14', 'Rhode Island', True, '2:00 PM'),
        ('Feb 15', 'Rhode Island', True, '1:00 PM'),
        ('Feb 17', 'UNCG', True, '5:00 PM'),
        ('Feb 20', 'Ohio', True, '4:00 PM'),
        ('Feb 21', 'Ohio', True, '2:00 PM'),
        ('Feb 22', 'Ohio', True, '1:00 PM'),
        ('Feb 24', 'Appalachian State', True, '5:00 PM'),
        ('Feb 27', 'Iona', True, '4:00 PM'),
        ('Feb 28', 'Iona', True, '2:00 PM'),
        ('Mar 1', 'Iona', True, '1:00 PM'),
        ('Mar 3', 'High Point', True, '5:00 PM'),
        ('Mar 6', 'Miami', False, '7:00 PM'),
        ('Mar 7', 'Miami', False, '6:00 PM'),
        ('Mar 8', 'Miami', False, '1:00 PM'),
        ('Mar 10', 'Charlotte', True, '5:00 PM'),
        ('Mar 13', 'Duke', False, '6:00 PM'),
        ('Mar 14', 'Duke', False, '2:00 PM'),
        ('Mar 15', 'Duke', False, '1:00 PM'),
        ('Mar 17', 'Elon', True, '5:00 PM'),
        ('Mar 20', 'NC State', False, '6:30 PM'),
        ('Mar 21', 'NC State', False, '2:00 PM'),
        ('Mar 22', 'NC State', False, '1:00 PM'),
        ('Mar 24', 'Davidson', True, '6:00 PM'),
        ('Mar 27', 'Clemson', True, '6:00 PM'),
        ('Mar 28', 'Clemson', True, '3:00 PM'),
        ('Mar 29', 'Clemson', True, '1:00 PM'),
        ('Mar 31', 'Charlotte', False, '6:00 PM'),
        ('Apr 3', 'Syracuse', True, '6:00 PM'),
        ('Apr 4', 'Syracuse', True, '2:00 PM'),
        ('Apr 5', 'Syracuse', True, '1:00 PM'),
        ('Apr 7', 'Elon', False, '6:00 PM'),
        ('Apr 10', 'Virginia', True, '6:00 PM'),
        ('Apr 11', 'Virginia', True, '3:00 PM'),
        ('Apr 12', 'Virginia', True, '1:00 PM'),
        ('Apr 14', 'Campbell', True, '6:00 PM'),
        ('Apr 17', 'North Carolina', True, '6:00 PM'),
        ('Apr 18', 'North Carolina', True, '3:00 PM'),
        ('Apr 19', 'North Carolina', True, '1:00 PM'),
        ('Apr 21', 'Davidson', False, '6:00 PM'),
        ('Apr 24', 'Boston College', False, '3:00 PM'),
        ('Apr 25', 'Boston College', False, '12:00 PM'),
        ('Apr 26', 'Boston College', False, '1:00 PM'),
        ('Apr 28', 'UNCG', False, '6:00 PM'),
        ('May 1', 'Georgia Tech', True, '6:00 PM'),
        ('May 2', 'Georgia Tech', True, '3:00 PM'),
        ('May 3', 'Georgia Tech', True, '1:00 PM'),
        ('May 5', 'Appalachian State', False, '6:00 PM'),
        ('May 8', 'Notre Dame', False, '6:30 PM'),
        ('May 9', 'Notre Dame', False, '3:00 PM'),
        ('May 10', 'Notre Dame', False, '1:00 PM'),
        ('May 14', 'Louisville', False, '6:00 PM'),
        ('May 15', 'Louisville', False, '6:00 PM'),
        ('May 16', 'Louisville', False, '1:00 PM'),
    ],
    'nc-state': [
        ('Feb 13', 'Quinnipiac', True, '3:00 PM'),
        ('Feb 14', 'Quinnipiac', True, '1:00 PM'),
        ('Feb 15', 'Quinnipiac', True, '1:00 PM'),
        ('Feb 17', 'UNC Greensboro', True, '4:00 PM'),
        ('Feb 20', 'Maryland', True, '3:00 PM'),
        ('Feb 21', 'Maryland', True, '1:00 PM'),
        ('Feb 22', 'North Carolina', False, '1:00 PM'),
        ('Feb 24', 'Campbell', True, '4:00 PM'),
        ('Feb 27', 'Fordham', True, '3:00 PM'),
        ('Feb 28', 'Fordham', True, '1:00 PM'),
        ('Mar 1', 'Fordham', True, '1:00 PM'),
        ('Mar 3', 'East Carolina', False, '6:00 PM'),
        ('Mar 6', 'Duke', False, '6:00 PM'),
        ('Mar 7', 'Duke', False, '2:00 PM'),
        ('Mar 8', 'Duke', False, '1:00 PM'),
        ('Mar 10', 'High Point', True, '4:00 PM'),
        ('Mar 13', 'California', True, '6:30 PM'),
        ('Mar 14', 'California', True, '2:00 PM'),
        ('Mar 15', 'California', True, '1:00 PM'),
        ('Mar 17', 'Coastal Carolina', True, '6:30 PM'),
        ('Mar 20', 'Clemson', False, '6:00 PM'),
        ('Mar 21', 'Clemson', False, '3:00 PM'),
        ('Mar 22', 'Clemson', False, '1:00 PM'),
        ('Mar 24', 'UNC Wilmington', True, '6:30 PM'),
        ('Mar 27', 'Florida State', False, '6:00 PM'),
        ('Mar 28', 'Florida State', False, '4:00 PM'),
        ('Mar 29', 'Florida State', False, '1:00 PM'),
        ('Mar 31', 'East Carolina', True, '6:30 PM'),
        ('Apr 3', 'Notre Dame', False, '6:30 PM'),
        ('Apr 4', 'Notre Dame', False, '3:00 PM'),
        ('Apr 5', 'Notre Dame', False, '1:00 PM'),
        ('Apr 7', 'Elon', True, '6:30 PM'),
        ('Apr 10', 'Stanford', True, '6:30 PM'),
        ('Apr 11', 'Stanford', True, '2:00 PM'),
        ('Apr 12', 'Stanford', True, '1:00 PM'),
        ('Apr 14', 'UNCW', False, '6:00 PM'),
        ('Apr 17', 'Miami', True, '6:30 PM'),
        ('Apr 18', 'Miami', True, '2:00 PM'),
        ('Apr 19', 'Miami', True, '1:00 PM'),
        ('Apr 21', 'Coastal Carolina', False, '6:00 PM'),
        ('Apr 24', 'Virginia Tech', False, '6:00 PM'),
        ('Apr 25', 'Virginia Tech', False, '3:00 PM'),
        ('Apr 26', 'Virginia Tech', False, '1:00 PM'),
        ('Apr 28', 'Campbell', False, '6:00 PM'),
        ('May 1', 'Virginia', False, '6:00 PM'),
        ('May 2', 'Virginia', False, '2:00 PM'),
        ('May 3', 'Virginia', False, '1:00 PM'),
        ('May 5', 'UNC Greensboro', False, '6:00 PM'),
        ('May 8', 'North Carolina', True, '6:00 PM'),
        ('May 9', 'North Carolina', True, '2:00 PM'),
        ('May 10', 'North Carolina', True, '1:00 PM'),
        ('May 14', 'Pittsburgh', True, '6:30 PM'),
        ('May 15', 'Pittsburgh', True, '6:30 PM'),
        ('May 16', 'Pittsburgh', True, '1:00 PM'),
    ],
    'georgia-tech': [
        ('Feb 13', 'Toledo', True, '4:00 PM'),
        ('Feb 14', 'Toledo', True, '2:00 PM'),
        ('Feb 15', 'Toledo', True, '1:00 PM'),
        ('Feb 17', 'Kennesaw State', True, '5:00 PM'),
        ('Feb 20', 'UIC', True, '4:00 PM'),
        ('Feb 21', 'UIC', True, '2:00 PM'),
        ('Feb 22', 'UIC', True, '1:00 PM'),
        ('Feb 24', 'Georgia State', True, '5:00 PM'),
        ('Feb 27', 'Minnesota', True, '4:00 PM'),
        ('Feb 28', 'Minnesota', True, '2:00 PM'),
        ('Mar 1', 'Minnesota', True, '1:00 PM'),
        ('Mar 3', 'Georgia', False, '5:00 PM'),
        ('Mar 6', 'Virginia Tech', True, '4:00 PM'),
        ('Mar 7', 'Virginia Tech', True, '2:00 PM'),
        ('Mar 8', 'Virginia Tech', True, '1:00 PM'),
        ('Mar 10', 'Georgia State', False, '6:00 PM'),
        ('Mar 13', 'Notre Dame', True, '6:00 PM'),
        ('Mar 14', 'Notre Dame', True, '2:00 PM'),
        ('Mar 15', 'Notre Dame', True, '1:00 PM'),
        ('Mar 17', 'Mercer', True, '6:00 PM'),
        ('Mar 20', 'North Carolina', False, '6:00 PM'),
        ('Mar 21', 'North Carolina', False, '2:00 PM'),
        ('Mar 22', 'North Carolina', False, '1:00 PM'),
        ('Mar 24', 'Georgia', True, '6:00 PM'),
        ('Mar 27', 'Virginia', False, '6:00 PM'),
        ('Mar 28', 'Virginia', False, '2:00 PM'),
        ('Mar 29', 'Virginia', False, '1:00 PM'),
        ('Mar 31', 'Auburn', True, '6:00 PM'),
        ('Apr 3', 'Florida State', True, '6:00 PM'),
        ('Apr 4', 'Florida State', True, '2:00 PM'),
        ('Apr 5', 'Florida State', True, '1:00 PM'),
        ('Apr 7', 'Mercer', False, '6:00 PM'),
        ('Apr 10', 'Pittsburgh', False, '6:00 PM'),
        ('Apr 11', 'Pittsburgh', False, '2:00 PM'),
        ('Apr 12', 'Pittsburgh', False, '1:00 PM'),
        ('Apr 14', 'Alabama State', True, '6:00 PM'),
        ('Apr 17', 'Clemson', False, '6:00 PM'),
        ('Apr 18', 'Clemson', False, '3:00 PM'),
        ('Apr 19', 'Clemson', False, '1:00 PM'),
        ('Apr 21', 'Kennesaw State', False, '6:00 PM'),
        ('Apr 24', 'SMU', True, '6:00 PM'),
        ('Apr 25', 'SMU', True, '2:00 PM'),
        ('Apr 26', 'SMU', True, '1:00 PM'),
        ('Apr 28', 'Georgia Southern', True, '6:00 PM'),
        ('May 1', 'Wake Forest', False, '6:00 PM'),
        ('May 2', 'Wake Forest', False, '3:00 PM'),
        ('May 3', 'Wake Forest', False, '1:00 PM'),
        ('May 5', 'Georgia Southern', False, '6:00 PM'),
        ('May 8', 'California', True, '6:00 PM'),
        ('May 9', 'California', True, '2:00 PM'),
        ('May 10', 'California', True, '1:00 PM'),
        ('May 14', 'Duke', False, '6:00 PM'),
        ('May 15', 'Duke', False, '3:00 PM'),
        ('May 16', 'Duke', False, '1:00 PM'),
    ],
    'notre-dame': [
        ('Feb 13', 'Hartford', True, '4:00 PM'),
        ('Feb 14', 'Hartford', True, '2:00 PM'),
        ('Feb 15', 'Hartford', True, '12:00 PM'),
        ('Feb 20', 'Indiana', False, '1:00 PM'),  # Jacksonville
        ('Feb 21', 'LSU', False, '11:00 AM'),
        ('Feb 22', 'UCF', False, '2:00 PM'),
        ('Feb 27', 'Iowa', True, '4:00 PM'),
        ('Feb 28', 'Iowa', True, '2:00 PM'),
        ('Mar 1', 'Iowa', True, '1:00 PM'),
        ('Mar 3', 'Toledo', True, '4:00 PM'),
        ('Mar 6', 'California', True, '5:00 PM'),
        ('Mar 7', 'California', True, '2:00 PM'),
        ('Mar 8', 'California', True, '1:00 PM'),
        ('Mar 10', 'Central Michigan', True, '4:00 PM'),
        ('Mar 13', 'Georgia Tech', False, '6:00 PM'),
        ('Mar 14', 'Georgia Tech', False, '2:00 PM'),
        ('Mar 15', 'Georgia Tech', False, '1:00 PM'),
        ('Mar 17', 'Valparaiso', True, '4:00 PM'),
        ('Mar 20', 'Louisville', False, '6:00 PM'),
        ('Mar 21', 'Louisville', False, '2:00 PM'),
        ('Mar 22', 'Louisville', False, '1:00 PM'),
        ('Mar 24', 'Ball State', True, '4:00 PM'),
        ('Mar 27', 'North Carolina', True, '6:30 PM'),
        ('Mar 28', 'North Carolina', True, '3:00 PM'),
        ('Mar 29', 'North Carolina', True, '1:00 PM'),
        ('Mar 31', 'Michigan State', True, '4:00 PM'),
        ('Apr 3', 'NC State', True, '6:30 PM'),
        ('Apr 4', 'NC State', True, '3:00 PM'),
        ('Apr 5', 'NC State', True, '1:00 PM'),
        ('Apr 7', 'Indiana State', True, '4:00 PM'),
        ('Apr 10', 'Miami', False, '7:00 PM'),
        ('Apr 11', 'Miami', False, '6:00 PM'),
        ('Apr 12', 'Miami', False, '1:00 PM'),
        ('Apr 14', 'Western Michigan', True, '4:00 PM'),
        ('Apr 17', 'Boston College', True, '6:00 PM'),
        ('Apr 18', 'Boston College', True, '3:00 PM'),
        ('Apr 19', 'Boston College', True, '1:00 PM'),
        ('Apr 21', 'Purdue', True, '4:00 PM'),
        ('Apr 24', 'Stanford', True, '6:00 PM'),
        ('Apr 25', 'Stanford', True, '3:00 PM'),
        ('Apr 26', 'Stanford', True, '1:00 PM'),
        ('Apr 28', 'Northwestern', True, '4:00 PM'),
        ('May 1', 'Syracuse', False, '6:00 PM'),
        ('May 2', 'Syracuse', False, '2:00 PM'),
        ('May 3', 'Syracuse', False, '1:00 PM'),
        ('May 5', 'Ohio State', True, '4:00 PM'),
        ('May 8', 'Clemson', True, '6:00 PM'),
        ('May 9', 'Clemson', True, '3:00 PM'),
        ('May 10', 'Clemson', True, '1:00 PM'),
        ('May 14', 'Pittsburgh', True, '6:00 PM'),
        ('May 15', 'Pittsburgh', True, '3:00 PM'),
        ('May 16', 'Pittsburgh', True, '1:00 PM'),
    ],
    'pittsburgh': [
        ('Feb 13', 'Youngstown State', True, '1:00 PM'),
        ('Feb 14', 'Youngstown State', True, '1:00 PM'),
        ('Feb 15', 'Youngstown State', True, '12:00 PM'),
        ('Feb 20', 'Canisius', True, '1:00 PM'),
        ('Feb 21', 'Canisius', True, '1:00 PM'),
        ('Feb 22', 'Canisius', True, '12:00 PM'),
        ('Feb 24', 'West Virginia', False, '4:00 PM'),
        ('Feb 27', 'Kent State', True, '1:00 PM'),
        ('Feb 28', 'Kent State', True, '1:00 PM'),
        ('Mar 1', 'Kent State', True, '12:00 PM'),
        ('Mar 6', 'Syracuse', True, '3:00 PM'),
        ('Mar 7', 'Syracuse', True, '1:00 PM'),
        ('Mar 8', 'Syracuse', True, '12:00 PM'),
        ('Mar 10', 'Penn State', True, '3:00 PM'),
        ('Mar 13', 'North Carolina', True, '6:00 PM'),
        ('Mar 14', 'North Carolina', True, '2:00 PM'),
        ('Mar 15', 'North Carolina', True, '1:00 PM'),
        ('Mar 17', 'Duquesne', True, '3:00 PM'),
        ('Mar 20', 'SMU', False, '6:30 PM'),
        ('Mar 21', 'SMU', False, '3:00 PM'),
        ('Mar 22', 'SMU', False, '1:00 PM'),
        ('Mar 24', 'Penn State', False, '4:00 PM'),
        ('Mar 27', 'Miami', False, '7:00 PM'),
        ('Mar 28', 'Miami', False, '6:00 PM'),
        ('Mar 29', 'Miami', False, '1:00 PM'),
        ('Mar 31', 'West Virginia', True, '6:00 PM'),
        ('Apr 3', 'Stanford', True, '6:00 PM'),
        ('Apr 4', 'Stanford', True, '2:00 PM'),
        ('Apr 5', 'Stanford', True, '1:00 PM'),
        ('Apr 7', 'Duquesne', False, '6:00 PM'),
        ('Apr 10', 'Georgia Tech', True, '6:00 PM'),
        ('Apr 11', 'Georgia Tech', True, '2:00 PM'),
        ('Apr 12', 'Georgia Tech', True, '1:00 PM'),
        ('Apr 14', 'Marshall', True, '6:00 PM'),
        ('Apr 17', 'Virginia Tech', False, '6:00 PM'),
        ('Apr 18', 'Virginia Tech', False, '3:00 PM'),
        ('Apr 19', 'Virginia Tech', False, '1:00 PM'),
        ('Apr 21', 'Robert Morris', True, '6:00 PM'),
        ('Apr 24', 'Syracuse', False, '6:00 PM'),
        ('Apr 25', 'Syracuse', False, '2:00 PM'),
        ('Apr 26', 'Syracuse', False, '1:00 PM'),
        ('Apr 28', 'Marshall', False, '6:00 PM'),
        ('May 1', 'Florida State', False, '6:00 PM'),
        ('May 2', 'Florida State', False, '4:00 PM'),
        ('May 3', 'Florida State', False, '1:00 PM'),
        ('May 5', 'Xavier', True, '6:00 PM'),
        ('May 8', 'Virginia', True, '6:00 PM'),
        ('May 9', 'Virginia', True, '2:00 PM'),
        ('May 10', 'Virginia', True, '1:00 PM'),
        ('May 14', 'NC State', False, '6:30 PM'),
        ('May 15', 'NC State', False, '6:30 PM'),
        ('May 16', 'NC State', False, '1:00 PM'),
    ],
    'boston-college': [
        ('Feb 13', 'UMass', True, '12:00 PM'),
        ('Feb 14', 'UMass', True, '12:00 PM'),
        ('Feb 15', 'UMass', True, '12:00 PM'),
        ('Feb 20', 'NJIT', True, '12:00 PM'),
        ('Feb 21', 'NJIT', True, '12:00 PM'),
        ('Feb 22', 'NJIT', True, '12:00 PM'),
        ('Feb 24', 'Northeastern', False, '3:00 PM'),
        ('Feb 27', 'Maine', True, '3:00 PM'),
        ('Feb 28', 'Maine', True, '12:00 PM'),
        ('Mar 1', 'Maine', True, '1:00 PM'),
        ('Mar 3', 'Harvard', True, '3:00 PM'),
        ('Mar 6', 'SMU', True, '3:00 PM'),
        ('Mar 7', 'SMU', True, '12:00 PM'),
        ('Mar 8', 'SMU', True, '1:00 PM'),
        ('Mar 10', 'Holy Cross', True, '3:00 PM'),
        ('Mar 13', 'Clemson', True, '3:00 PM'),
        ('Mar 14', 'Clemson', True, '12:00 PM'),
        ('Mar 15', 'Clemson', True, '1:00 PM'),
        ('Mar 17', 'Northeastern', True, '3:00 PM'),
        ('Mar 20', 'Virginia', True, '3:00 PM'),
        ('Mar 21', 'Virginia', True, '12:00 PM'),
        ('Mar 22', 'Virginia', True, '1:00 PM'),
        ('Mar 24', 'Harvard', False, '4:00 PM'),
        ('Mar 27', 'Louisville', False, '6:00 PM'),
        ('Mar 28', 'Louisville', False, '2:00 PM'),
        ('Mar 29', 'Louisville', False, '1:00 PM'),
        ('Mar 31', 'Brown', True, '3:00 PM'),
        ('Apr 3', 'North Carolina', False, '6:00 PM'),
        ('Apr 4', 'North Carolina', False, '2:00 PM'),
        ('Apr 5', 'North Carolina', False, '1:00 PM'),
        ('Apr 7', 'Holy Cross', False, '3:00 PM'),
        ('Apr 10', 'Virginia Tech', True, '3:00 PM'),
        ('Apr 11', 'Virginia Tech', True, '12:00 PM'),
        ('Apr 12', 'Virginia Tech', True, '1:00 PM'),
        ('Apr 14', 'UConn', True, '3:00 PM'),
        ('Apr 17', 'Notre Dame', False, '6:00 PM'),
        ('Apr 18', 'Notre Dame', False, '3:00 PM'),
        ('Apr 19', 'Notre Dame', False, '1:00 PM'),
        ('Apr 21', 'UConn', False, '3:00 PM'),
        ('Apr 24', 'Wake Forest', True, '3:00 PM'),
        ('Apr 25', 'Wake Forest', True, '12:00 PM'),
        ('Apr 26', 'Wake Forest', True, '1:00 PM'),
        ('Apr 28', 'Brown', False, '4:00 PM'),
        ('May 1', 'Miami', True, '3:00 PM'),
        ('May 2', 'Miami', True, '12:00 PM'),
        ('May 3', 'Miami', True, '1:00 PM'),
        ('May 5', 'Rhode Island', True, '3:00 PM'),
        ('May 8', 'Syracuse', False, '6:00 PM'),
        ('May 9', 'Syracuse', False, '2:00 PM'),
        ('May 10', 'Syracuse', False, '1:00 PM'),
        ('May 14', 'California', True, '6:00 PM'),
        ('May 15', 'California', True, '3:00 PM'),
        ('May 16', 'California', True, '1:00 PM'),
    ],
    'california': [
        ('Feb 13', 'Utah', True, '2:00 PM'),
        ('Feb 14', 'Utah', True, '2:00 PM'),
        ('Feb 15', 'Utah', True, '1:00 PM'),
        ('Feb 17', 'Santa Clara', True, '3:00 PM'),
        ('Feb 20', 'BYU', True, '2:00 PM'),
        ('Feb 21', 'BYU', True, '2:00 PM'),
        ('Feb 22', 'BYU', True, '1:00 PM'),
        ('Feb 24', 'Saint Mary\'s', True, '3:00 PM'),
        ('Feb 27', 'Nevada', True, '2:00 PM'),
        ('Feb 28', 'Nevada', True, '2:00 PM'),
        ('Mar 1', 'Nevada', True, '1:00 PM'),
        ('Mar 3', 'San Jose State', True, '3:00 PM'),
        ('Mar 6', 'Notre Dame', False, '5:00 PM'),
        ('Mar 7', 'Notre Dame', False, '2:00 PM'),
        ('Mar 8', 'Notre Dame', False, '1:00 PM'),
        ('Mar 10', 'San Francisco', True, '3:00 PM'),
        ('Mar 13', 'NC State', False, '6:30 PM'),
        ('Mar 14', 'NC State', False, '2:00 PM'),
        ('Mar 15', 'NC State', False, '1:00 PM'),
        ('Mar 17', 'San Jose State', False, '6:00 PM'),
        ('Mar 20', 'Stanford', True, '6:00 PM'),
        ('Mar 21', 'Stanford', True, '2:00 PM'),
        ('Mar 22', 'Stanford', True, '1:00 PM'),
        ('Mar 24', 'Pacific', True, '3:00 PM'),
        ('Mar 27', 'Syracuse', True, '6:00 PM'),
        ('Mar 28', 'Syracuse', True, '2:00 PM'),
        ('Mar 29', 'Syracuse', True, '1:00 PM'),
        ('Mar 31', 'Sacramento State', True, '3:00 PM'),
        ('Apr 3', 'SMU', True, '6:00 PM'),
        ('Apr 4', 'SMU', True, '2:00 PM'),
        ('Apr 5', 'SMU', True, '1:00 PM'),
        ('Apr 7', 'Nevada', False, '6:00 PM'),
        ('Apr 10', 'Oregon State', False, '7:00 PM'),
        ('Apr 11', 'Oregon State', False, '5:00 PM'),
        ('Apr 12', 'Oregon State', False, '1:00 PM'),
        ('Apr 14', 'UC Davis', True, '3:00 PM'),
        ('Apr 17', 'Louisville', True, '9:00 PM'),
        ('Apr 18', 'Louisville', True, '5:00 PM'),
        ('Apr 19', 'Louisville', True, '4:00 PM'),
        ('Apr 21', 'Saint Mary\'s', False, '3:00 PM'),
        ('Apr 24', 'Miami', False, '7:00 PM'),
        ('Apr 25', 'Miami', False, '6:00 PM'),
        ('Apr 26', 'Miami', False, '1:00 PM'),
        ('Apr 28', 'Pacific', False, '6:00 PM'),
        ('May 1', 'Virginia Tech', True, '9:00 PM'),
        ('May 2', 'Virginia Tech', True, '5:00 PM'),
        ('May 3', 'Virginia Tech', True, '4:00 PM'),
        ('May 5', 'Santa Clara', False, '6:00 PM'),
        ('May 8', 'Georgia Tech', False, '6:00 PM'),
        ('May 9', 'Georgia Tech', False, '2:00 PM'),
        ('May 10', 'Georgia Tech', False, '1:00 PM'),
        ('May 14', 'Boston College', False, '6:00 PM'),
        ('May 15', 'Boston College', False, '3:00 PM'),
        ('May 16', 'Boston College', False, '1:00 PM'),
    ],
    'stanford': [
        ('Feb 13', 'Fresno State', True, '6:00 PM'),
        ('Feb 14', 'Fresno State', True, '2:00 PM'),
        ('Feb 15', 'Fresno State', True, '1:00 PM'),
        ('Feb 17', 'Santa Clara', False, '6:00 PM'),
        ('Feb 20', 'San Diego', True, '6:00 PM'),
        ('Feb 21', 'San Diego', True, '2:00 PM'),
        ('Feb 22', 'San Diego', True, '1:00 PM'),
        ('Feb 24', 'San Jose State', True, '6:00 PM'),
        ('Feb 27', 'Arizona State', True, '6:00 PM'),
        ('Feb 28', 'Arizona State', True, '2:00 PM'),
        ('Mar 1', 'Arizona State', True, '1:00 PM'),
        ('Mar 3', 'UC Davis', True, '6:00 PM'),
        ('Mar 6', 'SMU', False, '6:30 PM'),
        ('Mar 7', 'SMU', False, '3:00 PM'),
        ('Mar 8', 'SMU', False, '1:00 PM'),
        ('Mar 10', 'Pacific', True, '6:00 PM'),
        ('Mar 13', 'Syracuse', True, '6:00 PM'),
        ('Mar 14', 'Syracuse', True, '2:00 PM'),
        ('Mar 15', 'Syracuse', True, '1:00 PM'),
        ('Mar 17', 'Nevada', True, '6:00 PM'),
        ('Mar 20', 'California', False, '6:00 PM'),
        ('Mar 21', 'California', False, '2:00 PM'),
        ('Mar 22', 'California', False, '1:00 PM'),
        ('Mar 24', 'Santa Clara', True, '6:00 PM'),
        ('Mar 27', 'Duke', False, '6:00 PM'),
        ('Mar 28', 'Duke', False, '2:00 PM'),
        ('Mar 29', 'Duke', False, '1:00 PM'),
        ('Mar 31', 'San Francisco', True, '6:00 PM'),
        ('Apr 3', 'Pittsburgh', False, '6:00 PM'),
        ('Apr 4', 'Pittsburgh', False, '2:00 PM'),
        ('Apr 5', 'Pittsburgh', False, '1:00 PM'),
        ('Apr 7', 'Sacramento State', True, '6:00 PM'),
        ('Apr 10', 'NC State', False, '6:30 PM'),
        ('Apr 11', 'NC State', False, '2:00 PM'),
        ('Apr 12', 'NC State', False, '1:00 PM'),
        ('Apr 14', 'Saint Mary\'s', True, '6:00 PM'),
        ('Apr 17', 'Florida State', True, '9:00 PM'),
        ('Apr 18', 'Florida State', True, '6:00 PM'),
        ('Apr 19', 'Florida State', True, '4:00 PM'),
        ('Apr 21', 'San Jose State', False, '6:00 PM'),
        ('Apr 24', 'Notre Dame', False, '6:00 PM'),
        ('Apr 25', 'Notre Dame', False, '3:00 PM'),
        ('Apr 26', 'Notre Dame', False, '1:00 PM'),
        ('Apr 28', 'Oregon', False, '7:00 PM'),
        ('May 1', 'Virginia Tech', True, '6:00 PM'),
        ('May 2', 'Virginia Tech', True, '3:00 PM'),
        ('May 3', 'Virginia Tech', True, '1:00 PM'),
        ('May 5', 'UC Davis', False, '6:00 PM'),
        ('May 8', 'Washington', True, '6:00 PM'),
        ('May 9', 'Washington', True, '2:00 PM'),
        ('May 10', 'Washington', True, '1:00 PM'),
        ('May 14', 'SMU', True, '6:00 PM'),
        ('May 15', 'SMU', True, '3:00 PM'),
        ('May 16', 'SMU', True, '1:00 PM'),
    ],
    'smu': [
        ('Feb 13', 'Stephen F. Austin', True, '6:00 PM'),
        ('Feb 14', 'Stephen F. Austin', True, '2:00 PM'),
        ('Feb 15', 'Stephen F. Austin', True, '1:00 PM'),
        ('Feb 17', 'Texas State', True, '6:00 PM'),
        ('Feb 20', 'Nevada', True, '6:00 PM'),
        ('Feb 21', 'Nevada', True, '2:00 PM'),
        ('Feb 22', 'Nevada', True, '1:00 PM'),
        ('Feb 24', 'Dallas Baptist', True, '6:00 PM'),
        ('Feb 27', 'Rice', True, '6:30 PM'),
        ('Feb 28', 'Rice', True, '2:00 PM'),
        ('Mar 1', 'Rice', True, '1:00 PM'),
        ('Mar 3', 'Houston', False, '6:30 PM'),
        ('Mar 6', 'Boston College', False, '3:00 PM'),
        ('Mar 7', 'Boston College', False, '12:00 PM'),
        ('Mar 8', 'Boston College', False, '1:00 PM'),
        ('Mar 10', 'Texas State', False, '6:00 PM'),
        ('Mar 13', 'Virginia Tech', True, '6:30 PM'),
        ('Mar 14', 'Virginia Tech', True, '3:00 PM'),
        ('Mar 15', 'Virginia Tech', True, '1:00 PM'),
        ('Mar 17', 'UT Arlington', True, '6:30 PM'),
        ('Mar 20', 'Pittsburgh', True, '6:30 PM'),
        ('Mar 21', 'Pittsburgh', True, '3:00 PM'),
        ('Mar 22', 'Pittsburgh', True, '1:00 PM'),
        ('Mar 24', 'Houston', True, '6:30 PM'),
        ('Mar 27', 'Syracuse', False, '6:00 PM'),
        ('Mar 28', 'Syracuse', False, '2:00 PM'),
        ('Mar 29', 'Syracuse', False, '1:00 PM'),
        ('Mar 31', 'TCU', True, '6:30 PM'),
        ('Apr 3', 'California', False, '6:00 PM'),
        ('Apr 4', 'California', False, '2:00 PM'),
        ('Apr 5', 'California', False, '1:00 PM'),
        ('Apr 7', 'Dallas Baptist', False, '6:30 PM'),
        ('Apr 10', 'Louisville', False, '6:00 PM'),
        ('Apr 11', 'Louisville', False, '2:00 PM'),
        ('Apr 12', 'Louisville', False, '1:00 PM'),
        ('Apr 14', 'Oral Roberts', True, '6:30 PM'),
        ('Apr 17', 'Syracuse', True, '6:30 PM'),
        ('Apr 18', 'Syracuse', True, '3:00 PM'),
        ('Apr 19', 'Syracuse', True, '1:00 PM'),
        ('Apr 21', 'UT Arlington', False, '6:30 PM'),
        ('Apr 24', 'Georgia Tech', False, '6:00 PM'),
        ('Apr 25', 'Georgia Tech', False, '2:00 PM'),
        ('Apr 26', 'Georgia Tech', False, '1:00 PM'),
        ('Apr 28', 'TCU', False, '6:30 PM'),
        ('May 1', 'Virginia Tech', False, '6:00 PM'),
        ('May 2', 'Virginia Tech', False, '3:00 PM'),
        ('May 3', 'Virginia Tech', False, '1:00 PM'),
        ('May 5', 'Oral Roberts', False, '6:30 PM'),
        ('May 8', 'Oregon State', True, '7:00 PM'),
        ('May 9', 'Oregon State', True, '3:00 PM'),
        ('May 10', 'Oregon State', True, '1:00 PM'),
        ('May 14', 'Stanford', False, '6:00 PM'),
        ('May 15', 'Stanford', False, '3:00 PM'),
        ('May 16', 'Stanford', False, '1:00 PM'),
    ],
    'syracuse': [
        ('Feb 13', 'Maine', True, '4:00 PM'),
        ('Feb 14', 'Maine', True, '12:00 PM'),
        ('Feb 15', 'Maine', True, '12:00 PM'),
        ('Feb 20', 'Bryant', True, '3:00 PM'),
        ('Feb 21', 'Bryant', True, '12:00 PM'),
        ('Feb 22', 'Bryant', True, '12:00 PM'),
        ('Feb 24', 'Cornell', True, '3:00 PM'),
        ('Feb 27', 'Hofstra', True, '3:00 PM'),
        ('Feb 28', 'Hofstra', True, '12:00 PM'),
        ('Mar 1', 'Hofstra', True, '12:00 PM'),
        ('Mar 3', 'Penn State', True, '3:00 PM'),
        ('Mar 6', 'Pittsburgh', False, '3:00 PM'),
        ('Mar 7', 'Pittsburgh', False, '1:00 PM'),
        ('Mar 8', 'Pittsburgh', False, '12:00 PM'),
        ('Mar 10', 'Army', True, '3:00 PM'),
        ('Mar 13', 'Miami', True, '3:00 PM'),  # Florida game
        ('Mar 14', 'Miami', True, '12:00 PM'),
        ('Mar 15', 'Miami', True, '1:00 PM'),
        ('Mar 17', 'Binghamton', True, '3:00 PM'),
        ('Mar 20', 'Stanford', False, '6:00 PM'),
        ('Mar 21', 'Stanford', False, '2:00 PM'),
        ('Mar 22', 'Stanford', False, '1:00 PM'),
        ('Mar 24', 'Army', False, '3:00 PM'),
        ('Mar 27', 'SMU', True, '6:00 PM'),
        ('Mar 28', 'SMU', True, '2:00 PM'),
        ('Mar 29', 'SMU', True, '1:00 PM'),
        ('Mar 31', 'Binghamton', False, '3:00 PM'),
        ('Apr 3', 'Wake Forest', False, '6:00 PM'),
        ('Apr 4', 'Wake Forest', False, '2:00 PM'),
        ('Apr 5', 'Wake Forest', False, '1:00 PM'),
        ('Apr 7', 'Cornell', False, '4:00 PM'),
        ('Apr 10', 'California', False, '6:00 PM'),
        ('Apr 11', 'California', False, '2:00 PM'),
        ('Apr 12', 'California', False, '1:00 PM'),
        ('Apr 14', 'Le Moyne', True, '6:00 PM'),
        ('Apr 17', 'Virginia', False, '6:00 PM'),
        ('Apr 18', 'Virginia', False, '2:00 PM'),
        ('Apr 19', 'Virginia', False, '1:00 PM'),
        ('Apr 21', 'Le Moyne', False, '6:00 PM'),
        ('Apr 24', 'Pittsburgh', True, '6:00 PM'),
        ('Apr 25', 'Pittsburgh', True, '2:00 PM'),
        ('Apr 26', 'Pittsburgh', True, '1:00 PM'),
        ('Apr 28', 'Colgate', True, '6:00 PM'),
        ('May 1', 'Notre Dame', True, '6:00 PM'),
        ('May 2', 'Notre Dame', True, '2:00 PM'),
        ('May 3', 'Notre Dame', True, '1:00 PM'),
        ('May 5', 'Penn State', False, '6:00 PM'),
        ('May 8', 'Boston College', True, '6:00 PM'),
        ('May 9', 'Boston College', True, '2:00 PM'),
        ('May 10', 'Boston College', True, '1:00 PM'),
        ('May 14', 'Virginia Tech', True, '6:00 PM'),
        ('May 15', 'Virginia Tech', True, '3:00 PM'),
        ('May 16', 'Virginia Tech', True, '1:00 PM'),
    ],
}


def main():
    print("\n" + "=" * 60)
    print("  ACC Schedule Loader - 2026 Season")
    print("=" * 60)
    
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    # First, add all ACC teams to database
    print("\n📋 Adding ACC teams to database...")
    for team_id, team_name in ACC_TEAMS.items():
        cursor.execute("""
            INSERT INTO teams (id, name, conference) VALUES (?, ?, 'ACC')
            ON CONFLICT(id) DO UPDATE SET conference = 'ACC', name = ?
        """, (team_id, team_name, team_name))
        print(f"  ✓ {team_name}")
    
    games_added = {}
    teams_added = set()
    
    # Process each team's schedule
    print(f"\n📅 Loading schedules for {len(SCHEDULES)} teams...")
    for team_id, games in SCHEDULES.items():
        team_games = 0
        for game in games:
            date_str, opponent_name, is_home, time = game
            
            date = parse_date(date_str)
            if not date:
                print(f"  Warning: Could not parse date '{date_str}' for {team_id}")
                continue
            
            opponent_id = normalize_team_name(opponent_name)
            if not opponent_id:
                print(f"  Warning: Could not normalize opponent '{opponent_name}'")
                continue
            
            # Ensure opponent team exists
            cursor.execute("SELECT id FROM teams WHERE id = ?", (opponent_id,))
            if not cursor.fetchone():
                teams_added.add(opponent_id)
                cursor.execute("""
                    INSERT OR IGNORE INTO teams (id, name) VALUES (?, ?)
                """, (opponent_id, opponent_name))
            
            # Determine home/away
            if is_home:
                home_team_id = team_id
                away_team_id = opponent_id
            else:
                home_team_id = opponent_id
                away_team_id = team_id
            
            # Create game ID
            game_id = f"{date}_{away_team_id}_{home_team_id}"
            
            # Check if it's a conference game (both teams in ACC)
            is_conference = 1 if opponent_id in ACC_TEAMS else 0
            
            # Insert game
            try:
                cursor.execute("""
                    INSERT OR IGNORE INTO games 
                    (id, date, time, home_team_id, away_team_id, is_conference_game, status)
                    VALUES (?, ?, ?, ?, ?, ?, 'scheduled')
                """, (game_id, date, time, home_team_id, away_team_id, is_conference))
                
                if cursor.rowcount > 0:
                    team_games += 1
            except sqlite3.IntegrityError:
                pass
        
        games_added[team_id] = team_games
        print(f"  {ACC_TEAMS.get(team_id, team_id)}: {team_games} games added")
    
    conn.commit()
    
    # Summary
    total_new = sum(games_added.values())
    print(f"\n=== SUMMARY ===")
    print(f"Teams with new games: {len([k for k,v in games_added.items() if v > 0])}")
    print(f"Total new games added: {total_new}")
    print(f"New opponent teams added: {len(teams_added)}")
    
    # Count total games now
    cursor.execute("SELECT COUNT(*) FROM games")
    total_games = cursor.fetchone()[0]
    print(f"Total games in database: {total_games}")
    
    # Count ACC teams with games
    cursor.execute("""
        SELECT t.name, COUNT(DISTINCT g.id) as game_count
        FROM teams t
        LEFT JOIN games g ON t.id = g.home_team_id OR t.id = g.away_team_id
        WHERE t.conference = 'ACC'
        GROUP BY t.id
        ORDER BY game_count DESC
    """)
    print("\nGames per ACC team:")
    for row in cursor.fetchall():
        print(f"  {row[0]}: {row[1]} games")
    
    conn.close()
    print("\n✓ ACC schedule loading complete!")


if __name__ == "__main__":
    main()
