#!/usr/bin/env python3
"""
Load full 2026 schedules for all 16 SEC teams.
Parses schedule data from athletics websites and inserts into database.
"""

import sqlite3
import re
from datetime import datetime

DB_PATH = "/home/sam/college-baseball-predictor/data/baseball.db"

# All 16 SEC teams with their standard IDs
SEC_TEAMS = {
    'alabama': 'Alabama',
    'arkansas': 'Arkansas', 
    'auburn': 'Auburn',
    'florida': 'Florida',
    'georgia': 'Georgia',
    'kentucky': 'Kentucky',
    'lsu': 'LSU',
    'mississippi-state': 'Mississippi State',
    'missouri': 'Missouri',
    'oklahoma': 'Oklahoma',
    'ole-miss': 'Ole Miss',
    'south-carolina': 'South Carolina',
    'tennessee': 'Tennessee',
    'texas': 'Texas',
    'texas-am': 'Texas A&M',
    'vanderbilt': 'Vanderbilt'
}

# Team name to ID mapping (for parsing opponent names)
TEAM_NAME_MAP = {
    # SEC teams
    'alabama': 'alabama',
    'arkansas': 'arkansas',
    'auburn': 'auburn',
    'florida': 'florida',
    'florida gators': 'florida',
    'georgia': 'georgia',
    'kentucky': 'kentucky',
    'lsu': 'lsu',
    'mississippi state': 'mississippi-state',
    'mississippi st.': 'mississippi-state',
    'miss. state': 'mississippi-state',
    'ms state': 'mississippi-state',
    'missouri': 'missouri',
    'mizzou': 'missouri',
    'oklahoma': 'oklahoma',
    'ole miss': 'ole-miss',
    'south carolina': 'south-carolina',
    'tennessee': 'tennessee',
    'texas': 'texas',
    'texas a&m': 'texas-am',
    'texas am': 'texas-am',
    'vanderbilt': 'vanderbilt',
    'vandy': 'vanderbilt',
    
    # Non-conference teams (common opponents)
    'hofstra': 'hofstra',
    'troy': 'troy',
    'alcorn state': 'alcorn-state',
    'delaware': 'delaware',
    'austin peay': 'austin-peay',
    'lipscomb': 'lipscomb',
    'jackson state': 'jackson-state',
    'southern miss': 'southern-miss',
    'georgia state': 'georgia-state',
    'uab': 'uab',
    'ucla': 'ucla',
    'samford': 'samford',
    'nebraska': 'nebraska',
    'kansas state': 'kansas-state',
    'florida state': 'florida-state',
    'louisville': 'louisville',
    'georgia tech': 'georgia-tech',
    'south alabama': 'south-alabama',
    'jacksonville state': 'jacksonville-state',
    'alabama state': 'alabama-state',
    'milwaukee': 'milwaukee',
    'kent state': 'kent-state',
    'nicholls': 'nicholls-state',
    'indiana': 'indiana',
    'notre dame': 'notre-dame',
    'central florida': 'ucf',
    'ucf': 'ucf',
    'mcneese': 'mcneese',
    'dartmouth': 'dartmouth',
    'northeastern': 'northeastern',
    'ul-lafayette': 'ul-lafayette',
    'louisiana-lafayette': 'ul-lafayette',
    'sacramento state': 'sacramento-state',
    'creighton': 'creighton',
    'grambling state': 'grambling-state',
    'louisiana tech': 'louisiana-tech',
    'southern': 'southern',
    'bethune-cookman': 'bethune-cookman',
    'northwestern state': 'northwestern-state',
    'new orleans': 'new-orleans',
    'southeastern louisiana': 'southeastern-la',
    'tulane': 'tulane',
    'uc davis': 'uc-davis',
    'lamar': 'lamar',
    'michigan state': 'michigan-state',
    'ut-rio grande valley': 'utrgv',
    'utrgv': 'utrgv',
    'hcu': 'houston-christian',
    'houston christian': 'houston-christian',
    'tarleton state': 'tarleton-state',
    'tarleton': 'tarleton-state',
    'texas state': 'texas-state',
    'incarnate word': 'incarnate-word',
    'texas a&m-corpus christi': 'tamucc',
    'air force': 'air-force',
    'sam houston': 'sam-houston',
    'utsa': 'utsa',
    'houston': 'houston',
    'prairie view a&m': 'prairie-view',
    'tennessee tech': 'tennessee-tech',
    'penn': 'penn',
    'oakland': 'oakland',
    'stephen f. austin': 'sfa',
    'sfa': 'sfa',
    'tcu': 'tcu',
    'texas tech': 'texas-tech',
    'oklahoma state': 'oklahoma-state',
    'eastern michigan': 'eastern-michigan',
    'marist': 'marist',
    'evansville': 'evansville',
    'uc irvine': 'uc-irvine',
    'arizona': 'arizona',
    'oregon': 'oregon',
    'central arkansas': 'central-arkansas',
    'north dakota state': 'north-dakota-state',
    'indiana state': 'indiana-state',
    'tennessee tech': 'tennessee-tech',
    'belmont': 'belmont',
    'eastern kentucky': 'eastern-kentucky',
    'xavier': 'xavier',
    'middle tennessee': 'middle-tennessee',
    'unc greensboro': 'unc-greensboro',
    'morehead state': 'morehead-state',
    'western kentucky': 'western-kentucky',
    'st. johns': 'st-johns',
    "st. john's": 'st-johns',
    'the citadel': 'citadel',
    'citadel': 'citadel',
    'ball state': 'ball-state',
    'marshall': 'marshall',
    'murray state': 'murray-state',
    'miami university': 'miami-oh',
    'nicholls state': 'nicholls-state',
    'wright state': 'wright-state',
    'upstate': 'usc-upstate',
    'usc upstate': 'usc-upstate',
    'queens': 'queens',
    'western carolina': 'western-carolina',
    'etsu': 'etsu',
    'east tennessee state': 'etsu',
    'presbyterian': 'presbyterian',
    'northern kentucky': 'northern-kentucky',
    'winthrop': 'winthrop',
    'mount st. marys': 'mount-st-marys',
    "mount st. mary's": 'mount-st-marys',
    'florida atlantic': 'fau',
    'new haven': 'new-haven',
    'arkansas-pine bluff': 'arkansas-pine-bluff',
    'arkansas - pine bluff': 'arkansas-pine-bluff',
    'uic': 'uic',
    'southern indiana': 'southern-indiana',
    'kansas': 'kansas',
    'lindenwood': 'lindenwood',
    'missouri state': 'missouri-state',
    'siu edwardsville': 'siue',
    'siue': 'siue',
    'southeast missouri state': 'semo',
    'semo': 'semo',
    'arizona state': 'arizona-state',
    'nicholls colonel': 'nicholls-state',
    'north carolina a&t': 'north-carolina-at',
    'wofford': 'wofford',
    'gardner-webb': 'gardner-webb',
    'army': 'army',
    'navy': 'navy',
    'clemson': 'clemson',
    'princeton': 'princeton',
    'charlotte': 'charlotte',
    'davidson': 'davidson',
    'college of charleston': 'charleston',
    'charleston southern': 'charleston-southern',
    'washington state': 'washington-state',
    'southern illinois': 'southern-illinois',
    'wichita state': 'wichita-state',
    'youngstown state': 'youngstown-state',
    'ualr': 'ualr',
    'san diego state': 'san-diego-state',
    'uconn': 'uconn',
    'connecticut': 'uconn',
    'uapb': 'arkansas-pine-bluff',
    'arkansas state': 'arkansas-state',
    'jacksonville': 'jacksonville',
    'cincinnati': 'cincinnati',
    'miami': 'miami-fl',
    'usf': 'usf',
    'florida a&m': 'florida-am',
    'oregon state': 'oregon-state',
    'cal state fullerton': 'cal-state-fullerton',
    'oru': 'oral-roberts',
    'oral roberts': 'oral-roberts',
    'long beach state': 'long-beach-state',
    'dallas baptist': 'dallas-baptist',
    'hawaii': 'hawaii',
    'tulsa': 'tulsa',
    'osu': 'oklahoma-state',
    'maryland': 'maryland',
    'east carolina': 'east-carolina',
    'ulm': 'ulm',
    'michigan': 'michigan',
    'memphis': 'memphis',
    'bryant': 'bryant',
    'unc-asheville': 'unc-asheville',
    'bellarmine': 'bellarmine',
    'west georgia': 'west-georgia',
    'kennesaw state': 'kennesaw-state',
    'north carolina a&t': 'nc-at',
}

def normalize_team_name(name):
    """Convert team name to standard ID."""
    if not name:
        return None
    
    name_lower = name.lower().strip()
    # Remove rankings like "#2" or "No. 14"
    name_lower = re.sub(r'^#?\d+\s+', '', name_lower)
    name_lower = re.sub(r'^no\.\s*\d+\s+', '', name_lower)
    name_lower = name_lower.strip()
    
    if name_lower in TEAM_NAME_MAP:
        return TEAM_NAME_MAP[name_lower]
    
    # Try to create an ID from the name
    team_id = re.sub(r'[^a-z0-9]+', '-', name_lower).strip('-')
    return team_id

def parse_date(date_str, year=2026):
    """Parse date string like 'Feb 13' or 'Mar 1' into ISO format."""
    date_str = date_str.strip()
    
    # Handle formats like "Feb 13 (Fri)" or "Fri. Feb 13"
    date_str = re.sub(r'\([^)]+\)', '', date_str)  # Remove day in parens
    date_str = re.sub(r'^(Mon|Tue|Wed|Thu|Fri|Sat|Sun)\.?\s*', '', date_str)  # Remove day prefix
    date_str = date_str.strip()
    
    month_map = {
        'jan': 1, 'feb': 2, 'mar': 3, 'apr': 4, 'may': 5, 'jun': 6,
        'jul': 7, 'aug': 8, 'sep': 9, 'oct': 10, 'nov': 11, 'dec': 12
    }
    
    # Try "Feb 13" format
    match = re.match(r'([A-Za-z]+)\.?\s+(\d+)', date_str)
    if match:
        month_str, day = match.groups()
        month = month_map.get(month_str.lower()[:3])
        if month:
            return f"{year}-{month:02d}-{int(day):02d}"
    
    return None

# Raw schedule data for each team (extracted from web fetches)
# Format: list of (date_str, opponent, is_home, time)
SCHEDULES = {
    'lsu': [
        ('Feb 13', 'Milwaukee', True, '2:00 PM'),
        ('Feb 14', 'Milwaukee', True, '1:00 PM'),
        ('Feb 15', 'Milwaukee', True, '1:00 PM'),
        ('Feb 16', 'Kent State', True, '3:00 PM'),
        ('Feb 18', 'Nicholls', True, '1:00 PM'),
        ('Feb 20', 'Indiana', False, '1:00 PM'),  # Jacksonville tournament
        ('Feb 21', 'Notre Dame', False, '11:00 AM'),
        ('Feb 22', 'UCF', False, '2:00 PM'),
        ('Feb 24', 'McNeese', True, '6:30 PM'),
        ('Feb 27', 'Dartmouth', True, '6:30 PM'),
        ('Feb 28', 'Northeastern', True, '2:00 PM'),
        ('Mar 1', 'Dartmouth', True, '1:00 PM'),
        ('Mar 2', 'Northeastern', True, '6:30 PM'),
        ('Mar 4', 'UL-Lafayette', False, '6:00 PM'),
        ('Mar 6', 'Sacramento State', True, '6:30 PM'),
        ('Mar 7', 'Sacramento State', True, '6:00 PM'),
        ('Mar 8', 'Sacramento State', True, '1:00 PM'),
        ('Mar 10', 'Creighton', True, '6:30 PM'),
        ('Mar 13', 'Vanderbilt', False, '6:00 PM'),
        ('Mar 14', 'Vanderbilt', False, '7:00 PM'),
        ('Mar 15', 'Vanderbilt', False, '3:00 PM'),
        ('Mar 17', 'Grambling State', True, '6:30 PM'),
        ('Mar 19', 'Oklahoma', True, '7:00 PM'),
        ('Mar 20', 'Oklahoma', True, '6:30 PM'),
        ('Mar 21', 'Oklahoma', True, '2:00 PM'),
        ('Mar 24', 'Louisiana Tech', True, '6:30 PM'),
        ('Mar 27', 'Kentucky', True, '6:30 PM'),
        ('Mar 28', 'Kentucky', True, '2:00 PM'),
        ('Mar 29', 'Kentucky', True, '12:00 PM'),
        ('Mar 31', 'Southern', True, '6:30 PM'),
        ('Apr 3', 'Tennessee', False, '4:30 PM'),
        ('Apr 4', 'Tennessee', False, '5:00 PM'),
        ('Apr 5', 'Tennessee', False, '12:00 PM'),
        ('Apr 7', 'Bethune-Cookman', True, '6:30 PM'),
        ('Apr 10', 'Ole Miss', False, '6:30 PM'),
        ('Apr 11', 'Ole Miss', False, '4:00 PM'),
        ('Apr 12', 'Ole Miss', False, '1:30 PM'),
        ('Apr 14', 'Northwestern State', True, '6:30 PM'),
        ('Apr 17', 'Texas A&M', True, '6:00 PM'),
        ('Apr 18', 'Texas A&M', True, '7:00 PM'),
        ('Apr 19', 'Texas A&M', True, '1:00 PM'),
        ('Apr 21', 'New Orleans', True, '6:30 PM'),
        ('Apr 24', 'Mississippi State', False, '6:00 PM'),
        ('Apr 25', 'Mississippi State', False, '6:30 PM'),
        ('Apr 26', 'Mississippi State', False, '1:00 PM'),
        ('Apr 28', 'Southeastern Louisiana', True, '6:30 PM'),
        ('May 1', 'South Carolina', True, '6:30 PM'),
        ('May 2', 'South Carolina', True, '6:00 PM'),
        ('May 3', 'South Carolina', True, '2:00 PM'),
        ('May 5', 'Tulane', True, '6:30 PM'),
        ('May 8', 'Georgia', False, '5:00 PM'),
        ('May 9', 'Georgia', False, '7:00 PM'),
        ('May 10', 'Georgia', False, '3:00 PM'),
    ],
    'texas-am': [
        ('Feb 13', 'Tennessee Tech', True, '6:00 PM'),
        ('Feb 14', 'Tennessee Tech', True, '11:00 AM'),
        ('Feb 15', 'Tennessee Tech', True, '12:00 PM'),
        ('Feb 17', 'Texas A&M-Corpus Christi', True, '6:00 PM'),
        ('Feb 20', 'Penn', True, '6:00 PM'),
        ('Feb 21', 'Penn', True, '2:00 PM'),
        ('Feb 22', 'Penn', True, '1:00 PM'),
        ('Feb 24', 'Lamar', True, '6:00 PM'),
        ('Feb 27', 'UCLA', False, '7:00 PM'),  # Arlington
        ('Feb 28', 'UCLA', False, '7:00 PM'),
        ('Mar 1', 'UCLA', False, '6:30 PM'),
        ('Mar 3', 'Incarnate Word', True, '4:00 PM'),
        ('Mar 6', 'Oakland', True, '6:00 PM'),
        ('Mar 7', 'Oakland', True, '2:00 PM'),
        ('Mar 8', 'Oakland', True, '1:00 PM'),
        ('Mar 10', 'SFA', True, '6:00 PM'),
        ('Mar 17', 'Texas State', True, '6:00 PM'),
        ('Mar 20', 'Georgia', True, '6:00 PM'),
        ('Mar 21', 'Georgia', True, '2:00 PM'),
        ('Mar 24', 'HCU', True, '6:00 PM'),
        ('Mar 31', 'Sam Houston', True, '6:00 PM'),
        ('Apr 2', 'Vanderbilt', True, '6:00 PM'),
        ('Apr 3', 'Vanderbilt', True, '6:00 PM'),
        ('Apr 4', 'Vanderbilt', True, '2:00 PM'),
        ('Apr 10', 'Texas', True, '7:00 PM'),
        ('Apr 12', 'Texas', True, '1:00 PM'),
        ('Apr 14', 'Houston', True, '6:00 PM'),
        ('Apr 17', 'LSU', False, '6:00 PM'),
        ('Apr 18', 'LSU', False, '7:00 PM'),
        ('Apr 19', 'LSU', False, '1:00 PM'),
        ('Apr 21', 'UTSA', True, '3:00 PM'),
        ('Apr 28', 'Tarleton State', True, '6:00 PM'),
        ('May 1', 'Auburn', True, '7:00 PM'),
        ('May 2', 'Auburn', True, '2:00 PM'),
        ('May 3', 'Auburn', True, '1:00 PM'),
        ('May 5', 'Prairie View A&M', True, '6:00 PM'),
        ('May 14', 'Mississippi State', False, '6:00 PM'),
        ('May 15', 'Mississippi State', False, '6:00 PM'),
        ('May 16', 'Mississippi State', False, '2:00 PM'),
    ],
    'texas': [
        ('Feb 13', 'UC Davis', True, '6:30 PM'),
        ('Feb 14', 'UC Davis', True, '2:00 PM'),
        ('Feb 15', 'UC Davis', True, '12:00 PM'),
        ('Feb 17', 'Lamar', True, '5:00 PM'),
        ('Feb 20', 'Michigan State', True, '6:30 PM'),
        ('Feb 21', 'Michigan State', True, '2:00 PM'),
        ('Feb 22', 'Michigan State', True, '12:00 PM'),
        ('Feb 24', 'UTRGV', True, '6:30 PM'),
        ('Mar 3', 'HCU', True, '6:30 PM'),
        ('Mar 6', 'Tarleton State', True, '6:30 PM'),
        ('Mar 7', 'Tarleton State', True, '2:00 PM'),
        ('Mar 8', 'Tarleton State', True, '12:00 PM'),
        ('Mar 13', 'Ole Miss', True, '6:30 PM'),
        ('Mar 17', 'Tarleton State', True, '6:30 PM'),
        ('Mar 26', 'Oklahoma', False, '7:00 PM'),
        ('Mar 31', 'Texas State', True, '6:30 PM'),
        ('Apr 7', 'Incarnate Word', True, '6:30 PM'),
        ('Apr 14', 'Texas A&M-Corpus Christi', True, '6:30 PM'),
        ('Apr 17', 'Alabama', True, '6:30 PM'),
        ('Apr 19', 'Alabama', True, '1:00 PM'),
        ('Apr 21', 'Air Force', True, '6:30 PM'),
        ('Apr 28', 'Sam Houston', True, '6:30 PM'),
        ('May 3', 'Mississippi State', True, '1:00 PM'),
        ('May 5', 'UTSA', True, '6:30 PM'),
        ('May 14', 'Missouri', False, '6:30 PM'),
        ('May 15', 'Missouri', False, '6:30 PM'),
        ('May 16', 'Missouri', False, '2:00 PM'),
    ],
    'auburn': [
        ('Feb 13', 'North Carolina A&T', True, '5:30 PM'),
        ('Feb 14', 'North Carolina A&T', True, '6:00 PM'),
        ('Feb 15', 'North Carolina A&T', True, '2:00 PM'),
        ('Feb 17', 'ETSU', True, '6:00 PM'),
        ('Feb 20', 'Kansas State', False, '7:00 PM'),  # Arlington
        ('Feb 21', 'Florida State', False, '3:00 PM'),
        ('Feb 22', 'Louisville', False, '10:30 AM'),
        ('Feb 25', 'Samford', True, 'TBA'),
        ('Feb 27', 'UConn', True, 'TBA'),
        ('Feb 28', 'Nebraska', True, 'TBA'),
        ('Mar 1', 'Nebraska', True, 'TBA'),
        ('Mar 3', 'Samford', True, 'TBA'),
        ('Mar 6', 'Bryant', True, 'TBA'),
        ('Mar 7', 'Bryant', True, 'TBA'),
        ('Mar 8', 'Bryant', True, 'TBA'),
        ('Mar 10', 'UAB', True, 'TBA'),
        ('Mar 13', 'Missouri', False, '6:00 PM'),
        ('Mar 14', 'Missouri', False, '4:00 PM'),
        ('Mar 15', 'Missouri', False, '1:00 PM'),
        ('Mar 17', 'Jacksonville State', True, '6:00 PM'),
        ('Mar 20', 'Texas', True, '6:00 PM'),
        ('Mar 21', 'Texas', True, '6:00 PM'),
        ('Mar 22', 'Texas', True, '2:00 PM'),
        ('Mar 24', 'South Alabama', False, '6:00 PM'),
        ('Mar 27', 'Alabama', False, '6:00 PM'),
        ('Mar 28', 'Alabama', False, '7:00 PM'),
        ('Mar 29', 'Alabama', False, '1:00 PM'),
        ('Mar 31', 'Georgia Tech', False, '6:00 PM'),
        ('Apr 2', 'Arkansas', True, '6:00 PM'),
        ('Apr 3', 'Arkansas', True, '6:00 PM'),
        ('Apr 4', 'Arkansas', True, '2:00 PM'),
        ('Apr 7', 'Jacksonville State', True, '6:00 PM'),
        ('Apr 10', 'Kentucky', True, '6:00 PM'),
        ('Apr 11', 'Kentucky', True, '7:00 PM'),
        ('Apr 12', 'Kentucky', True, '2:00 PM'),
        ('Apr 14', 'Alabama State', True, '6:00 PM'),
        ('Apr 16', 'Florida', False, '6:00 PM'),
        ('Apr 17', 'Florida', False, '4:30 PM'),
        ('Apr 18', 'Florida', False, '11:00 AM'),
        ('Apr 21', 'Samford', False, '6:00 PM'),
        ('Apr 24', 'Oklahoma', True, '6:00 PM'),
        ('Apr 25', 'Oklahoma', True, '6:00 PM'),
        ('Apr 26', 'Oklahoma', True, '2:00 PM'),
        ('May 1', 'Texas A&M', False, '7:00 PM'),
        ('May 2', 'Texas A&M', False, '2:00 PM'),
        ('May 3', 'Texas A&M', False, '1:00 PM'),
        ('May 5', 'UAB', False, '6:00 PM'),
        ('May 7', 'Mississippi State', False, '7:00 PM'),
        ('May 8', 'Mississippi State', False, '7:30 PM'),
        ('May 9', 'Mississippi State', False, '3:00 PM'),
        ('May 12', 'Jacksonville State', False, '6:00 PM'),
        ('May 14', 'Georgia', True, '6:00 PM'),
        ('May 15', 'Georgia', True, '6:00 PM'),
        ('May 16', 'Georgia', True, '2:00 PM'),
    ],
    'georgia': [
        ('Feb 14', 'Wright State', True, '1:00 PM'),
        ('Feb 14', 'Wright State', True, '4:45 PM'),
        ('Feb 18', 'USC Upstate', True, '3:00 PM'),
        ('Feb 20', 'Samford', True, '3:00 PM'),
        ('Feb 21', 'Samford', True, '2:00 PM'),
        ('Feb 22', 'Samford', True, '1:00 PM'),
        ('Feb 25', 'Troy', True, '3:00 PM'),
        ('Feb 27', 'Oakland', True, '3:00 PM'),
        ('Feb 28', 'Oakland', True, '1:00 PM'),
        ('Mar 1', 'Oakland', True, '1:00 PM'),
        ('Mar 4', 'Western Carolina', True, '3:00 PM'),
        ('Mar 6', 'Queens', True, '3:00 PM'),
        ('Mar 7', 'Queens', True, '1:00 PM'),
        ('Mar 7', 'Queens', True, '5:00 PM'),
        ('Mar 8', 'Queens', True, '1:00 PM'),
        ('Mar 13', 'Tennessee', True, '6:00 PM'),
        ('Mar 14', 'Tennessee', True, '5:00 PM'),
        ('Mar 15', 'Tennessee', True, '1:00 PM'),
        ('Mar 17', 'Citadel', True, '3:00 PM'),
        ('Mar 20', 'Texas A&M', False, '6:00 PM'),
        ('Mar 21', 'Texas A&M', False, '2:00 PM'),
        ('Mar 24', 'Kennesaw State', True, '3:00 PM'),
        ('Mar 27', 'South Carolina', True, '6:00 PM'),
        ('Mar 28', 'South Carolina', True, '2:00 PM'),
        ('Mar 29', 'South Carolina', True, '1:00 PM'),
        ('Mar 31', 'Georgia State', True, '3:00 PM'),
        ('Apr 2', 'Mississippi State', False, '7:00 PM'),
        ('Apr 3', 'Mississippi State', False, '7:00 PM'),
        ('Apr 4', 'Mississippi State', False, '2:00 PM'),
        ('Apr 7', 'Presbyterian', True, '3:00 PM'),
        ('Apr 10', 'Florida', True, '6:00 PM'),
        ('Apr 11', 'Florida', True, '12:00 PM'),
        ('Apr 12', 'Florida', True, '12:00 PM'),
        ('Apr 14', 'ETSU', True, '3:00 PM'),
        ('Apr 24', 'Ole Miss', False, '7:30 PM'),
        ('Apr 26', 'Ole Miss', False, '2:30 PM'),
        ('Apr 28', 'Troy', True, '3:00 PM'),
        ('May 1', 'Missouri', True, '6:00 PM'),
        ('May 2', 'Missouri', True, '2:00 PM'),
        ('May 3', 'Missouri', True, '12:00 PM'),
        ('May 8', 'LSU', True, '6:00 PM'),
        ('May 9', 'LSU', True, '7:00 PM'),
        ('May 10', 'LSU', True, '3:00 PM'),
    ],
    'kentucky': [
        ('Feb 13', 'UNC Greensboro', False, '4:00 PM'),
        ('Feb 14', 'UNC Greensboro', False, '1:00 PM'),
        ('Feb 14', 'UNC Greensboro', False, 'TBA'),
        ('Feb 17', 'Morehead State', True, '4:00 PM'),
        ('Feb 20', 'Evansville', False, '4:00 PM'),
        ('Feb 21', 'Evansville', False, '3:00 PM'),
        ('Feb 22', 'Evansville', False, '2:00 PM'),
        ('Feb 24', 'Western Kentucky', True, '4:00 PM'),
        ('Feb 27', "St. John's", True, '4:00 PM'),
        ('Feb 28', "St. John's", True, '1:00 PM'),
        ('Mar 1', "St. John's", True, '1:00 PM'),
        ('Mar 3', 'Eastern Kentucky', False, '5:00 PM'),
        ('Mar 4', 'Eastern Kentucky', True, '4:00 PM'),
        ('Mar 6', 'The Citadel', True, '4:00 PM'),
        ('Mar 7', 'The Citadel', True, '1:00 PM'),
        ('Mar 8', 'The Citadel', True, '1:00 PM'),
        ('Mar 10', 'Ball State', True, '6:30 PM'),
        ('Mar 13', 'Alabama', True, '6:30 PM'),
        ('Mar 14', 'Alabama', True, '2:00 PM'),
        ('Mar 15', 'Alabama', True, '1:00 PM'),
        ('Mar 17', 'Marshall', True, '2:00 PM'),
        ('Mar 19', 'Ole Miss', False, '8:00 PM'),
        ('Mar 20', 'Ole Miss', False, '7:30 PM'),
        ('Mar 21', 'Ole Miss', False, '2:30 PM'),
        ('Mar 24', 'Murray State', True, '6:30 PM'),
        ('Mar 27', 'LSU', False, '7:30 PM'),
        ('Mar 28', 'LSU', False, '3:00 PM'),
        ('Mar 29', 'LSU', False, '1:00 PM'),
        ('Mar 31', 'Miami University', True, '6:30 PM'),
        ('Apr 3', 'Missouri', True, '6:30 PM'),
        ('Apr 4', 'Missouri', True, '2:00 PM'),
        ('Apr 5', 'Missouri', True, '1:00 PM'),
        ('Apr 7', 'Louisville', True, '5:30 PM'),
        ('Apr 10', 'Auburn', False, '7:00 PM'),
        ('Apr 11', 'Auburn', False, '8:00 PM'),
        ('Apr 12', 'Auburn', False, '3:00 PM'),
        ('Apr 17', 'Vanderbilt', True, '6:30 PM'),
        ('Apr 18', 'Vanderbilt', True, '2:00 PM'),
        ('Apr 19', 'Vanderbilt', True, '1:00 PM'),
        ('Apr 21', 'Louisville', False, '7:00 PM'),
        ('Apr 24', 'South Carolina', False, '6:30 PM'),
        ('Apr 25', 'South Carolina', False, '4:00 PM'),
        ('Apr 26', 'South Carolina', False, '3:00 PM'),
        ('May 1', 'Tennessee', True, '6:30 PM'),
        ('May 2', 'Tennessee', True, '2:00 PM'),
        ('May 3', 'Tennessee', True, '1:00 PM'),
        ('May 8', 'Florida', False, '6:30 PM'),
        ('May 9', 'Florida', False, '4:00 PM'),
        ('May 10', 'Florida', False, '12:00 PM'),
        ('May 12', 'Northern Kentucky', True, '6:30 PM'),
        ('May 14', 'Arkansas', True, '6:30 PM'),
        ('May 15', 'Arkansas', True, '6:30 PM'),
        ('May 16', 'Arkansas', True, '2:00 PM'),
    ],
    'vanderbilt': [
        ('Feb 13', 'TCU', False, '3:00 PM'),  # Arlington
        ('Feb 14', 'Texas Tech', False, '11:00 AM'),
        ('Feb 15', 'Oklahoma State', False, '10:30 AM'),
        ('Feb 17', 'Eastern Michigan', True, '4:30 PM'),
        ('Feb 18', 'Eastern Michigan', True, '4:30 PM'),
        ('Feb 20', 'Marist', True, '2:00 PM'),
        ('Feb 21', 'Marist', True, '2:00 PM'),
        ('Feb 22', 'Marist', True, '1:00 PM'),
        ('Feb 24', 'Evansville', True, '4:30 PM'),
        ('Feb 27', 'UC Irvine', False, '4:00 PM'),  # Las Vegas
        ('Feb 28', 'Arizona', False, '6:00 PM'),
        ('Mar 1', 'Oregon', False, '1:00 PM'),
        ('Mar 3', 'Central Arkansas', True, '4:30 PM'),
        ('Mar 4', 'Troy', True, '3:00 PM'),
        ('Mar 6', 'North Dakota State', True, '4:30 PM'),
        ('Mar 7', 'North Dakota State', True, '2:00 PM'),
        ('Mar 8', 'North Dakota State', True, '1:00 PM'),
        ('Mar 10', 'Indiana State', True, '6:00 PM'),
        ('Mar 13', 'LSU', True, '6:00 PM'),
        ('Mar 14', 'LSU', True, '7:00 PM'),
        ('Mar 15', 'LSU', True, '3:00 PM'),
        ('Mar 17', 'Indiana', True, '6:00 PM'),
        ('Mar 20', 'Mississippi State', False, '7:00 PM'),
        ('Mar 21', 'Mississippi State', False, '6:00 PM'),
        ('Mar 22', 'Mississippi State', False, '1:00 PM'),
        ('Mar 24', 'Tennessee Tech', True, '6:00 PM'),
        ('Mar 27', 'Tennessee', True, '7:00 PM'),
        ('Mar 28', 'Tennessee', True, '4:00 PM'),
        ('Mar 29', 'Tennessee', True, '11:00 AM'),
        ('Mar 31', 'Belmont', True, '6:00 PM'),
        ('Apr 2', 'Texas A&M', False, '6:00 PM'),
        ('Apr 3', 'Texas A&M', False, '6:00 PM'),
        ('Apr 4', 'Texas A&M', False, '2:00 PM'),
        ('Apr 7', 'Eastern Kentucky', True, '6:00 PM'),
        ('Apr 9', 'Oklahoma', True, '6:00 PM'),
        ('Apr 10', 'Oklahoma', True, '6:00 PM'),
        ('Apr 11', 'Oklahoma', True, '1:00 PM'),
        ('Apr 14', 'Lipscomb', False, '6:00 PM'),
        ('Apr 17', 'Kentucky', False, '5:30 PM'),
        ('Apr 18', 'Kentucky', False, '1:00 PM'),
        ('Apr 19', 'Kentucky', False, '12:00 PM'),
        ('Apr 21', 'Xavier', True, '6:00 PM'),
        ('Apr 24', 'Texas', True, '6:00 PM'),
        ('Apr 25', 'Texas', True, '7:00 PM'),
        ('Apr 26', 'Texas', True, '12:00 PM'),
        ('Apr 28', 'Middle Tennessee', True, '6:00 PM'),
        ('Apr 30', 'Alabama', False, '6:00 PM'),
        ('May 1', 'Alabama', False, '6:00 PM'),
        ('May 2', 'Alabama', False, '1:00 PM'),
        ('May 5', 'Louisville', True, '7:00 PM'),
        ('May 8', 'Missouri', False, '6:00 PM'),
        ('May 9', 'Missouri', False, '4:00 PM'),
        ('May 10', 'Missouri', False, '1:00 PM'),
        ('May 14', 'South Carolina', True, '6:00 PM'),
        ('May 15', 'South Carolina', True, '6:00 PM'),
        ('May 16', 'South Carolina', True, '1:00 PM'),
    ],
    'missouri': [
        ('Feb 13', "Mount St. Mary's", False, '5:00 PM'),  # Fort Myers
        ('Feb 14', "Mount St. Mary's", False, '3:00 PM'),
        ('Feb 15', "Mount St. Mary's", False, '12:00 PM'),
        ('Feb 17', 'Florida Atlantic', False, '5:30 PM'),
        ('Feb 20', 'New Haven', False, '5:00 PM'),
        ('Feb 21', 'New Haven', False, '3:00 PM'),
        ('Feb 22', 'New Haven', False, '12:00 PM'),
        ('Feb 24', 'Arkansas-Pine Bluff', True, '3:00 PM'),
        ('Feb 25', 'Arkansas-Pine Bluff', True, '1:00 PM'),
        ('Feb 27', 'North Dakota State', True, '6:00 PM'),
        ('Feb 28', 'North Dakota State', True, '2:00 PM'),
        ('Mar 1', 'North Dakota State', True, '1:00 PM'),
        ('Mar 5', 'UIC', True, '6:00 PM'),
        ('Mar 6', 'UIC', True, '6:00 PM'),
        ('Mar 7', 'UIC', True, '4:00 PM'),
        ('Mar 8', 'UIC', True, '1:00 PM'),
        ('Mar 10', 'Southern Indiana', True, '6:00 PM'),
        ('Mar 13', 'Auburn', True, '6:00 PM'),
        ('Mar 14', 'Auburn', True, '4:00 PM'),
        ('Mar 15', 'Auburn', True, '1:00 PM'),
        ('Mar 17', 'Kansas', False, '6:00 PM'),
        ('Mar 20', 'Tennessee', False, '5:30 PM'),
        ('Mar 21', 'Tennessee', False, '5:00 PM'),
        ('Mar 22', 'Tennessee', False, '12:00 PM'),
        ('Mar 24', 'Illinois', False, '6:00 PM'),  # O'Fallon
        ('Mar 25', 'Lindenwood', False, '5:00 PM'),
        ('Mar 27', 'Texas A&M', True, '6:00 PM'),
        ('Mar 28', 'Texas A&M', True, '4:00 PM'),
        ('Mar 29', 'Texas A&M', True, '1:00 PM'),
        ('Mar 31', 'Kansas', True, '7:00 PM'),
        ('Apr 3', 'Kentucky', False, '5:30 PM'),
        ('Apr 4', 'Kentucky', False, '1:00 PM'),
        ('Apr 5', 'Kentucky', False, '12:00 PM'),
        ('Apr 7', 'Missouri State', True, '6:00 PM'),
        ('Apr 9', 'South Carolina', True, '7:00 PM'),
        ('Apr 10', 'South Carolina', True, '6:00 PM'),
        ('Apr 11', 'South Carolina', True, '2:00 PM'),
        ('Apr 15', 'Missouri State', False, '6:30 PM'),
        ('Apr 17', 'Oklahoma', False, '6:30 PM'),
        ('Apr 18', 'Oklahoma', False, '4:00 PM'),
        ('Apr 19', 'Oklahoma', False, '2:00 PM'),
        ('Apr 21', 'SIUE', True, '6:00 PM'),
        ('Apr 23', 'Arkansas', True, '7:00 PM'),
        ('Apr 24', 'Arkansas', True, '7:00 PM'),
        ('Apr 25', 'Arkansas', True, '2:00 PM'),
        ('Apr 28', 'SEMO', False, '6:00 PM'),
        ('May 1', 'Georgia', False, '5:00 PM'),
        ('May 2', 'Georgia', False, '1:00 PM'),
        ('May 3', 'Georgia', False, '11:00 AM'),
        ('May 5', 'Arizona State', True, '6:00 PM'),
        ('May 8', 'Vanderbilt', True, '6:00 PM'),
        ('May 9', 'Vanderbilt', True, '4:00 PM'),
        ('May 10', 'Vanderbilt', True, '1:00 PM'),
        ('May 14', 'Texas', True, '6:30 PM'),
        ('May 15', 'Texas', True, '6:30 PM'),
        ('May 16', 'Texas', True, '2:00 PM'),
    ],
    'tennessee': [
        ('Feb 13', 'Nicholls State', True, '4:30 PM'),
        ('Feb 14', 'Nicholls State', True, '1:00 PM'),
        ('Feb 15', 'Nicholls State', True, '1:00 PM'),
        ('Feb 17', 'UNC-Asheville', True, '4:00 PM'),
        ('Feb 20', 'Kent State', True, '4:30 PM'),
        ('Feb 21', 'Kent State', True, '4:00 PM'),
        ('Feb 22', 'Kent State', True, '1:00 PM'),
        ('Feb 24', 'Bellarmine', True, '4:00 PM'),
        ('Feb 27', 'UCLA', False, '4:00 PM'),  # Arlington
        ('Feb 28', 'UCLA', False, '12:00 PM'),
        ('Mar 1', 'UCLA', False, '11:30 AM'),
        ('Mar 3', 'ETSU', True, '4:00 PM'),
        ('Mar 4', 'Oakland', True, '4:00 PM'),
        ('Mar 6', 'Wright State', True, '6:30 PM'),
        ('Mar 7', 'Wright State', True, '6:00 PM'),
        ('Mar 8', 'Wright State', True, '1:00 PM'),
        ('Mar 10', 'Tennessee Tech', True, '6:00 PM'),
        ('Mar 13', 'Georgia', False, '6:00 PM'),
        ('Mar 14', 'Georgia', False, '5:00 PM'),
        ('Mar 15', 'Georgia', False, '1:00 PM'),
        ('Mar 17', 'Eastern Kentucky', True, '6:00 PM'),
        ('Mar 20', 'Missouri', True, '6:30 PM'),
        ('Mar 21', 'Missouri', True, '6:00 PM'),
        ('Mar 22', 'Missouri', True, '1:00 PM'),
        ('Mar 24', 'USC Upstate', True, '6:00 PM'),
        ('Mar 27', 'Vanderbilt', False, '7:00 PM'),
        ('Mar 28', 'Vanderbilt', False, '4:00 PM'),
        ('Mar 29', 'Vanderbilt', False, '11:00 AM'),
        ('Mar 31', 'Austin Peay', True, '6:00 PM'),
        ('Apr 3', 'LSU', True, '5:30 PM'),
        ('Apr 4', 'LSU', True, '6:00 PM'),
        ('Apr 5', 'LSU', True, '1:00 PM'),
        ('Apr 7', 'Northern Kentucky', True, '6:00 PM'),
        ('Apr 14', 'UNC-Asheville', True, '6:00 PM'),
        ('Apr 17', 'Ole Miss', True, '6:30 PM'),
        ('Apr 18', 'Ole Miss', True, '6:00 PM'),
        ('Apr 19', 'Ole Miss', True, '1:00 PM'),
        ('Apr 21', 'Lipscomb', True, '6:00 PM'),
        ('Apr 23', 'Alabama', True, '7:00 PM'),
        ('Apr 24', 'Alabama', True, '6:30 PM'),
        ('Apr 25', 'Alabama', True, '1:00 PM'),
        ('Apr 28', 'West Georgia', True, '6:00 PM'),
        ('May 1', 'Kentucky', False, '6:30 PM'),
        ('May 2', 'Kentucky', False, '2:00 PM'),
        ('May 3', 'Kentucky', False, '1:00 PM'),
        ('May 5', 'Presbyterian', True, '6:00 PM'),
        ('May 8', 'Texas', True, '6:30 PM'),
        ('May 9', 'Texas', True, '6:00 PM'),
        ('May 10', 'Texas', True, '12:00 PM'),
        ('May 12', 'Belmont', True, '5:00 PM'),
    ],
    'south-carolina': [
        ('Feb 13', 'Northern Kentucky', True, '1:00 PM'),
        ('Feb 13', 'Northern Kentucky', True, '5:00 PM'),
        ('Feb 14', 'Northern Kentucky', True, '2:00 PM'),
        ('Feb 17', 'Wofford', False, '5:30 PM'),
        ('Feb 18', 'Gardner-Webb', True, '4:00 PM'),
        ('Feb 20', 'Army', True, '2:00 PM'),
        ('Feb 21', 'Navy', True, '1:00 PM'),
        ('Feb 22', 'Air Force', True, '4:00 PM'),
        ('Feb 25', 'Queens', True, '6:30 PM'),
        ('Feb 27', 'Clemson', True, '7:00 PM'),
        ('Feb 28', 'Clemson', False, '3:00 PM'),  # Segra Park
        ('Mar 1', 'Clemson', False, '3:00 PM'),
        ('Mar 3', 'USC Upstate', True, '6:30 PM'),
        ('Mar 4', 'Charleston Southern', True, '6:30 PM'),
        ('Mar 7', 'Princeton', True, '1:00 PM'),
        ('Mar 7', 'Princeton', True, '4:30 PM'),
        ('Mar 8', 'Princeton', True, '1:30 PM'),
        ('Mar 10', 'The Citadel', False, '7:00 PM'),
        ('Mar 13', 'Florida', False, '6:30 PM'),
        ('Mar 14', 'Florida', False, '6:30 PM'),
        ('Mar 15', 'Florida', False, '1:00 PM'),
        ('Mar 17', 'Charlotte', True, '6:30 PM'),
        ('Mar 20', 'Arkansas', True, '7:00 PM'),
        ('Mar 21', 'Arkansas', True, '4:00 PM'),
        ('Mar 22', 'Arkansas', True, '1:30 PM'),
        ('Mar 24', 'North Carolina', False, '6:30 PM'),  # Charlotte
        ('Mar 27', 'Georgia', False, '6:00 PM'),
        ('Mar 28', 'Georgia', False, '2:00 PM'),
        ('Mar 29', 'Georgia', False, '1:00 PM'),
        ('Mar 31', 'Wofford', True, '6:30 PM'),
        ('Apr 2', 'Texas', True, '7:00 PM'),
        ('Apr 3', 'Texas', True, '7:00 PM'),
        ('Apr 4', 'Texas', True, '2:00 PM'),
        ('Apr 7', 'College of Charleston', True, '6:30 PM'),
        ('Apr 9', 'Missouri', False, '8:00 PM'),
        ('Apr 10', 'Missouri', False, '7:00 PM'),
        ('Apr 11', 'Missouri', False, '3:00 PM'),
        ('Apr 14', 'Davidson', True, '6:30 PM'),
        ('Apr 17', 'Mississippi State', True, '7:00 PM'),
        ('Apr 18', 'Mississippi State', True, '1:00 PM'),
        ('Apr 19', 'Mississippi State', True, '1:30 PM'),
        ('Apr 21', 'Presbyterian', True, '6:30 PM'),
        ('Apr 24', 'Kentucky', True, '7:00 PM'),
        ('Apr 25', 'Kentucky', True, '4:00 PM'),
        ('Apr 26', 'Kentucky', True, '3:00 PM'),
        ('Apr 28', 'The Citadel', True, '6:30 PM'),
        ('May 1', 'LSU', False, '7:30 PM'),
        ('May 2', 'LSU', False, '7:00 PM'),
        ('May 3', 'LSU', False, '3:00 PM'),
        ('May 8', 'Alabama', True, '5:30 PM'),
        ('May 9', 'Alabama', True, '1:00 PM'),
        ('May 10', 'Alabama', True, '1:30 PM'),
        ('May 12', 'Winthrop', True, '6:30 PM'),
        ('May 14', 'Vanderbilt', False, '6:00 PM'),
        ('May 15', 'Vanderbilt', False, '6:00 PM'),
        ('May 16', 'Vanderbilt', False, '1:00 PM'),
    ],
    'alabama': [
        ('Feb 13', 'Washington State', True, '5:00 PM'),
        ('Feb 14', 'Washington State', True, '2:00 PM'),
        ('Feb 15', 'Washington State', True, '1:00 PM'),
        ('Feb 17', 'Samford', True, '5:00 PM'),
        ('Feb 20', 'Southern Illinois', True, '5:00 PM'),
        ('Feb 21', 'Southern Illinois', True, '2:00 PM'),
        ('Feb 22', 'Southern Illinois', True, '1:00 PM'),
        ('Feb 25', 'UAB', False, '6:00 PM'),
        ('Feb 27', 'Wichita State', True, '5:00 PM'),
        ('Feb 28', 'Wichita State', True, '2:00 PM'),
        ('Mar 1', 'Wichita State', True, '1:00 PM'),
        ('Mar 3', 'Jacksonville State', True, '5:00 PM'),
        ('Mar 6', 'Youngstown State', True, '5:00 PM'),
        ('Mar 7', 'Youngstown State', True, '2:00 PM'),
        ('Mar 8', 'Youngstown State', True, '1:00 PM'),
        ('Mar 10', 'Alabama State', True, '5:00 PM'),
        ('Mar 13', 'Kentucky', False, '6:30 PM'),
        ('Mar 14', 'Kentucky', False, '2:00 PM'),
        ('Mar 15', 'Kentucky', False, '1:00 PM'),
        ('Mar 17', 'Troy', True, '5:00 PM'),
        ('Mar 20', 'Arkansas', False, '6:00 PM'),
        ('Mar 21', 'Arkansas', False, '2:00 PM'),
        ('Mar 22', 'Arkansas', False, '1:00 PM'),
        ('Mar 24', 'Samford', False, '6:00 PM'),
        ('Mar 27', 'Auburn', True, '6:00 PM'),
        ('Mar 28', 'Auburn', True, '7:00 PM'),
        ('Mar 29', 'Auburn', True, '1:00 PM'),
        ('Mar 31', 'UAB', True, '6:00 PM'),
        ('Apr 3', 'Ole Miss', True, '6:00 PM'),
        ('Apr 4', 'Ole Miss', True, '7:00 PM'),
        ('Apr 5', 'Ole Miss', True, '1:00 PM'),
        ('Apr 8', 'South Alabama', True, '6:00 PM'),
        ('Apr 10', 'Tennessee', False, '6:00 PM'),
        ('Apr 11', 'Tennessee', False, '6:00 PM'),
        ('Apr 12', 'Tennessee', False, '1:00 PM'),
        ('Apr 15', 'Jacksonville State', False, '6:00 PM'),
        ('Apr 17', 'Texas', False, '6:30 PM'),
        ('Apr 19', 'Texas', False, '1:00 PM'),
        ('Apr 22', 'Troy', False, '6:00 PM'),
        ('Apr 23', 'Tennessee', False, '7:00 PM'),
        ('Apr 24', 'Tennessee', False, '6:30 PM'),
        ('Apr 25', 'Tennessee', False, '1:00 PM'),
        ('Apr 28', 'South Alabama', False, '6:00 PM'),
        ('Apr 30', 'Vanderbilt', True, '6:00 PM'),
        ('May 1', 'Vanderbilt', True, '6:00 PM'),
        ('May 2', 'Vanderbilt', True, '1:00 PM'),
        ('May 5', 'Jacksonville State', True, '6:00 PM'),
        ('May 8', 'South Carolina', False, '5:30 PM'),
        ('May 9', 'South Carolina', False, '1:00 PM'),
        ('May 10', 'South Carolina', False, '1:30 PM'),
        ('May 12', 'UAB', True, '6:00 PM'),
        ('May 14', 'Florida', True, '6:00 PM'),
        ('May 15', 'Florida', True, '6:00 PM'),
        ('May 16', 'Florida', True, '1:00 PM'),
    ],
    'arkansas': [
        ('Feb 13', 'Wright State', True, '3:00 PM'),
        ('Feb 14', 'Wright State', True, '2:00 PM'),
        ('Feb 15', 'Wright State', True, '1:00 PM'),
        ('Feb 17', 'UALR', True, '4:00 PM'),
        ('Feb 20', 'Belmont', True, '3:00 PM'),
        ('Feb 21', 'Belmont', True, '2:00 PM'),
        ('Feb 22', 'Belmont', True, '1:00 PM'),
        ('Feb 24', 'Oral Roberts', True, '4:00 PM'),
        ('Feb 27', 'San Diego State', True, '6:00 PM'),
        ('Feb 28', 'San Diego State', True, '2:00 PM'),
        ('Mar 1', 'San Diego State', True, '1:00 PM'),
        ('Mar 3', 'Illinois State', True, '4:00 PM'),
        ('Mar 6', 'UConn', True, '6:00 PM'),
        ('Mar 7', 'UConn', True, '2:00 PM'),
        ('Mar 8', 'UConn', True, '1:00 PM'),
        ('Mar 10', 'Central Arkansas', True, '4:00 PM'),
        ('Mar 13', 'Florida', True, '6:00 PM'),
        ('Mar 14', 'Florida', True, '7:00 PM'),
        ('Mar 15', 'Florida', True, '1:00 PM'),
        ('Mar 17', 'UALR', False, '6:00 PM'),
        ('Mar 20', 'Alabama', True, '6:00 PM'),
        ('Mar 21', 'Alabama', True, '2:00 PM'),
        ('Mar 22', 'Alabama', True, '1:00 PM'),
        ('Mar 24', 'Oral Roberts', False, '6:00 PM'),
        ('Mar 27', 'Oklahoma', True, '6:00 PM'),
        ('Mar 28', 'Oklahoma', True, '2:00 PM'),
        ('Mar 29', 'Oklahoma', True, '1:00 PM'),
        ('Mar 31', 'UAPB', True, '4:00 PM'),
        ('Apr 2', 'Auburn', False, '6:00 PM'),
        ('Apr 3', 'Auburn', False, '6:00 PM'),
        ('Apr 4', 'Auburn', False, '2:00 PM'),
        ('Apr 7', 'Arkansas State', True, '6:00 PM'),
        ('Apr 10', 'Mississippi State', True, '6:00 PM'),
        ('Apr 11', 'Mississippi State', True, '6:00 PM'),
        ('Apr 12', 'Mississippi State', True, '1:00 PM'),
        ('Apr 14', 'UALR', True, '6:00 PM'),
        ('Apr 17', 'Florida', False, '6:00 PM'),
        ('Apr 18', 'Florida', False, '4:00 PM'),
        ('Apr 19', 'Florida', False, '12:00 PM'),
        ('Apr 21', 'Missouri State', True, '6:00 PM'),
        ('Apr 23', 'Missouri', False, '7:00 PM'),
        ('Apr 24', 'Missouri', False, '7:00 PM'),
        ('Apr 25', 'Missouri', False, '2:00 PM'),
        ('Apr 29', 'Arkansas State', False, '6:00 PM'),
        ('May 1', 'Ole Miss', True, '6:00 PM'),
        ('May 2', 'Ole Miss', True, '7:00 PM'),
        ('May 3', 'Ole Miss', True, '1:00 PM'),
        ('May 6', 'UAPB', True, '6:00 PM'),
        ('May 8', 'Texas A&M', False, '6:00 PM'),
        ('May 9', 'Texas A&M', False, '2:00 PM'),
        ('May 10', 'Texas A&M', False, '1:00 PM'),
        ('May 14', 'Kentucky', False, '6:30 PM'),
        ('May 15', 'Kentucky', False, '6:30 PM'),
        ('May 16', 'Kentucky', False, '2:00 PM'),
    ],
    'florida': [
        ('Feb 13', 'UAB', True, '6:30 PM'),
        ('Feb 14', 'UAB', True, 'TBA'),
        ('Feb 17', 'Stetson', False, '6:30 PM'),
        ('Feb 20', 'Kennesaw State', True, '6:30 PM'),
        ('Feb 21', 'Kennesaw State', True, '5:30 PM'),
        ('Feb 22', 'Kennesaw State', True, '1:00 PM'),
        ('Feb 24', 'Jacksonville', True, '6:00 PM'),
        ('Feb 27', 'Cincinnati', True, '6:30 PM'),
        ('Feb 28', 'Cincinnati', True, '2:00 PM'),
        ('Mar 1', 'Cincinnati', True, '1:00 PM'),
        ('Mar 3', 'Miami', True, '6:00 PM'),
        ('Mar 6', 'UConn', True, '6:30 PM'),
        ('Mar 7', 'UConn', True, '2:00 PM'),
        ('Mar 8', 'UConn', True, '1:00 PM'),
        ('Mar 10', 'Jacksonville', False, '6:00 PM'),
        ('Mar 13', 'South Carolina', True, '6:30 PM'),
        ('Mar 14', 'South Carolina', True, '6:30 PM'),
        ('Mar 15', 'South Carolina', True, '1:00 PM'),
        ('Mar 17', 'Bethune-Cookman', True, '6:00 PM'),
        ('Mar 20', 'Ole Miss', False, '7:00 PM'),
        ('Mar 21', 'Ole Miss', False, '6:30 PM'),
        ('Mar 22', 'Ole Miss', False, '1:30 PM'),
        ('Mar 24', 'Jacksonville', True, '6:00 PM'),
        ('Mar 27', 'Texas A&M', False, '6:00 PM'),
        ('Mar 28', 'Texas A&M', False, '2:00 PM'),
        ('Mar 29', 'Texas A&M', False, '1:00 PM'),
        ('Mar 31', 'Florida State', True, '6:00 PM'),
        ('Apr 3', 'Arkansas', False, '6:00 PM'),
        ('Apr 4', 'Arkansas', False, '7:00 PM'),
        ('Apr 5', 'Arkansas', False, '1:00 PM'),
        ('Apr 7', 'Stetson', True, '6:00 PM'),
        ('Apr 10', 'Georgia', False, '6:00 PM'),
        ('Apr 11', 'Georgia', False, '12:00 PM'),
        ('Apr 12', 'Georgia', False, '12:00 PM'),
        ('Apr 14', 'Florida A&M', True, '6:00 PM'),
        ('Apr 16', 'Auburn', True, '6:00 PM'),
        ('Apr 17', 'Auburn', True, '4:30 PM'),
        ('Apr 18', 'Auburn', True, '11:00 AM'),
        ('Apr 21', 'Bethune-Cookman', True, '6:00 PM'),
        ('Apr 24', 'Oklahoma', False, '6:30 PM'),
        ('Apr 25', 'Oklahoma', False, '2:00 PM'),
        ('Apr 26', 'Oklahoma', False, '1:00 PM'),
        ('Apr 28', 'Florida A&M', False, '6:00 PM'),
        ('May 1', 'Mississippi State', True, '6:30 PM'),
        ('May 2', 'Mississippi State', True, '6:00 PM'),
        ('May 3', 'Mississippi State', True, '12:00 PM'),
        ('May 5', 'USF', True, '6:00 PM'),
        ('May 8', 'Kentucky', True, '6:30 PM'),
        ('May 9', 'Kentucky', True, '4:00 PM'),
        ('May 10', 'Kentucky', True, '12:00 PM'),
        ('May 12', 'Miami', False, '6:00 PM'),
        ('May 14', 'Alabama', False, '6:00 PM'),
        ('May 15', 'Alabama', False, '6:00 PM'),
        ('May 16', 'Alabama', False, '1:00 PM'),
    ],
    'oklahoma': [
        ('Feb 13', 'Oregon State', True, '6:00 PM'),
        ('Feb 14', 'Oregon State', True, '2:00 PM'),
        ('Feb 15', 'Oregon State', True, '1:00 PM'),
        ('Feb 17', 'Wichita State', True, '4:00 PM'),
        ('Feb 20', 'Cal State Fullerton', True, '6:00 PM'),
        ('Feb 21', 'Cal State Fullerton', True, '2:00 PM'),
        ('Feb 22', 'Cal State Fullerton', True, '1:00 PM'),
        ('Feb 24', 'ORU', False, '4:00 PM'),
        ('Feb 27', 'Long Beach State', True, '6:00 PM'),
        ('Feb 28', 'Long Beach State', True, '2:00 PM'),
        ('Mar 1', 'Long Beach State', True, '1:00 PM'),
        ('Mar 3', 'Dallas Baptist', True, '4:00 PM'),
        ('Mar 6', 'Hawaii', True, '6:00 PM'),
        ('Mar 7', 'Hawaii', True, '2:00 PM'),
        ('Mar 8', 'Hawaii', True, '1:00 PM'),
        ('Mar 10', 'Kansas', True, '4:00 PM'),
        ('Mar 13', 'Texas', True, '7:00 PM'),
        ('Mar 14', 'Texas', True, '2:00 PM'),
        ('Mar 15', 'Texas', True, '1:00 PM'),
        ('Mar 17', 'Wichita State', False, '4:00 PM'),
        ('Mar 19', 'LSU', False, '7:00 PM'),
        ('Mar 20', 'LSU', False, '6:30 PM'),
        ('Mar 21', 'LSU', False, '2:00 PM'),
        ('Mar 24', 'ORU', True, '6:00 PM'),
        ('Mar 26', 'Texas', True, '7:00 PM'),
        ('Mar 27', 'Arkansas', False, '6:00 PM'),
        ('Mar 28', 'Arkansas', False, '2:00 PM'),
        ('Mar 29', 'Arkansas', False, '1:00 PM'),
        ('Mar 31', 'Kansas', False, '4:00 PM'),
        ('Apr 3', 'Mississippi State', False, '6:00 PM'),
        ('Apr 4', 'Mississippi State', False, '6:00 PM'),
        ('Apr 5', 'Mississippi State', False, '1:00 PM'),
        ('Apr 7', 'Tulsa', True, '6:00 PM'),
        ('Apr 9', 'Vanderbilt', False, '6:00 PM'),
        ('Apr 10', 'Vanderbilt', False, '6:00 PM'),
        ('Apr 11', 'Vanderbilt', False, '1:00 PM'),
        ('Apr 14', 'Dallas Baptist', False, '6:00 PM'),
        ('Apr 17', 'Missouri', True, '6:30 PM'),
        ('Apr 18', 'Missouri', True, '4:00 PM'),
        ('Apr 19', 'Missouri', True, '2:00 PM'),
        ('Apr 21', 'Tulsa', False, '6:00 PM'),
        ('Apr 24', 'Florida', True, '6:30 PM'),
        ('Apr 25', 'Florida', True, '2:00 PM'),
        ('Apr 26', 'Florida', True, '1:00 PM'),
        ('Apr 28', 'OSU', True, '6:00 PM'),
        ('May 1', 'Ole Miss', False, '6:30 PM'),
        ('May 2', 'Ole Miss', False, '6:00 PM'),
        ('May 3', 'Ole Miss', False, '1:00 PM'),
        ('May 5', 'OSU', False, '6:00 PM'),
        ('May 8', 'Texas A&M', True, '6:00 PM'),
        ('May 9', 'Texas A&M', True, '2:00 PM'),
        ('May 10', 'Texas A&M', True, '1:00 PM'),
        ('May 12', 'Tulsa', True, '6:00 PM'),
        ('May 14', 'Auburn', False, '6:00 PM'),
        ('May 15', 'Auburn', False, '6:00 PM'),
        ('May 16', 'Auburn', False, '2:00 PM'),
    ],
    'ole-miss': [
        ('Feb 13', 'Maryland', True, '4:00 PM'),
        ('Feb 14', 'Maryland', True, '2:00 PM'),
        ('Feb 15', 'Maryland', True, '1:00 PM'),
        ('Feb 17', 'Jacksonville State', True, '4:00 PM'),
        ('Feb 20', 'East Carolina', True, '4:00 PM'),
        ('Feb 21', 'East Carolina', True, '2:00 PM'),
        ('Feb 22', 'East Carolina', True, '1:00 PM'),
        ('Feb 27', 'Michigan', False, '3:05 PM'),  # Bruce Bolt Classic
        ('Feb 28', 'Michigan', False, '11:05 AM'),
        ('Mar 1', 'Michigan', False, '10:05 AM'),
        ('Mar 3', 'Southern Miss', True, '4:00 PM'),
        ('Mar 6', 'Indiana State', True, '4:00 PM'),
        ('Mar 7', 'Indiana State', True, '2:00 PM'),
        ('Mar 8', 'Indiana State', True, '1:00 PM'),
        ('Mar 10', 'ULM', True, '4:00 PM'),
        ('Mar 13', 'Texas A&M', True, '6:30 PM'),
        ('Mar 14', 'Texas A&M', True, '2:00 PM'),
        ('Mar 15', 'Texas A&M', True, '1:00 PM'),
        ('Mar 17', 'Memphis', True, '4:00 PM'),
        ('Mar 19', 'Kentucky', True, '8:00 PM'),
        ('Mar 20', 'Kentucky', True, '7:30 PM'),
        ('Mar 21', 'Kentucky', True, '2:30 PM'),
        ('Mar 24', 'Southern Miss', False, '6:00 PM'),
        ('Mar 27', 'Mississippi State', False, '6:00 PM'),
        ('Mar 28', 'Mississippi State', False, '6:00 PM'),
        ('Mar 29', 'Mississippi State', False, '1:00 PM'),
        ('Mar 31', 'Memphis', False, '6:00 PM'),
        ('Apr 3', 'Alabama', False, '6:00 PM'),
        ('Apr 4', 'Alabama', False, '7:00 PM'),
        ('Apr 5', 'Alabama', False, '1:00 PM'),
        ('Apr 7', 'ULM', False, '6:00 PM'),
        ('Apr 10', 'LSU', True, '6:30 PM'),
        ('Apr 11', 'LSU', True, '4:00 PM'),
        ('Apr 12', 'LSU', True, '1:30 PM'),
        ('Apr 14', 'Jacksonville State', False, '6:00 PM'),
        ('Apr 17', 'Tennessee', False, '6:30 PM'),
        ('Apr 18', 'Tennessee', False, '6:00 PM'),
        ('Apr 19', 'Tennessee', False, '1:00 PM'),
        ('Apr 21', 'Southern Miss', True, '6:00 PM'),
        ('Apr 24', 'Georgia', True, '7:30 PM'),
        ('Apr 26', 'Georgia', True, '2:30 PM'),
        ('Apr 28', 'Memphis', True, '6:00 PM'),
        ('May 1', 'Oklahoma', True, '6:30 PM'),
        ('May 2', 'Oklahoma', True, '6:00 PM'),
        ('May 3', 'Oklahoma', True, '1:00 PM'),
        ('May 5', 'ULM', True, '6:00 PM'),
        ('May 8', 'Arkansas', False, '6:00 PM'),
        ('May 9', 'Arkansas', False, '7:00 PM'),
        ('May 10', 'Arkansas', False, '1:00 PM'),
        ('May 12', 'Jacksonville State', True, '6:00 PM'),
        ('May 14', 'Texas', False, '6:30 PM'),
        ('May 15', 'Texas', False, '2:00 PM'),
        ('May 16', 'Texas', False, '12:00 PM'),
    ],
}

def main():
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    # First, update all SEC teams to have conference='SEC'
    print("Setting conference='SEC' for all SEC teams...")
    for team_id, team_name in SEC_TEAMS.items():
        cursor.execute("""
            INSERT INTO teams (id, name, conference) VALUES (?, ?, 'SEC')
            ON CONFLICT(id) DO UPDATE SET conference = 'SEC', name = ?
        """, (team_id, team_name, team_name))
    
    games_added = {}
    teams_added = set()
    
    # Process each team's schedule
    for team_id, games in SCHEDULES.items():
        team_games = 0
        for game in games:
            date_str, opponent_name, is_home, time = game
            
            date = parse_date(date_str)
            if not date:
                print(f"  Warning: Could not parse date '{date_str}' for {team_id}")
                continue
            
            opponent_id = normalize_team_name(opponent_name)
            if not opponent_id:
                print(f"  Warning: Could not normalize opponent '{opponent_name}'")
                continue
            
            # Ensure opponent team exists
            cursor.execute("SELECT id FROM teams WHERE id = ?", (opponent_id,))
            if not cursor.fetchone():
                teams_added.add(opponent_id)
                cursor.execute("""
                    INSERT OR IGNORE INTO teams (id, name) VALUES (?, ?)
                """, (opponent_id, opponent_name))
            
            # Determine home/away
            if is_home:
                home_team_id = team_id
                away_team_id = opponent_id
            else:
                home_team_id = opponent_id
                away_team_id = team_id
            
            # Create game ID
            game_id = f"{date}_{away_team_id}_{home_team_id}"
            
            # Check if it's a conference game (both teams in SEC)
            is_conference = 1 if opponent_id in SEC_TEAMS else 0
            
            # Insert game (INSERT OR IGNORE to avoid duplicates)
            try:
                cursor.execute("""
                    INSERT OR IGNORE INTO games 
                    (id, date, time, home_team_id, away_team_id, is_conference_game, status)
                    VALUES (?, ?, ?, ?, ?, ?, 'scheduled')
                """, (game_id, date, time, home_team_id, away_team_id, is_conference))
                
                if cursor.rowcount > 0:
                    team_games += 1
            except sqlite3.IntegrityError:
                pass  # Game already exists
        
        games_added[team_id] = team_games
        print(f"  {SEC_TEAMS.get(team_id, team_id)}: {team_games} games added")
    
    conn.commit()
    
    # Summary
    total_new = sum(games_added.values())
    print(f"\n=== SUMMARY ===")
    print(f"Teams with new games: {len([k for k,v in games_added.items() if v > 0])}")
    print(f"Total new games added: {total_new}")
    print(f"New opponent teams added: {len(teams_added)}")
    
    # Count total games now
    cursor.execute("SELECT COUNT(*) FROM games")
    total_games = cursor.fetchone()[0]
    print(f"Total games in database: {total_games}")
    
    # Count SEC teams with games
    cursor.execute("""
        SELECT t.name, COUNT(DISTINCT g.id) as game_count
        FROM teams t
        LEFT JOIN games g ON t.id = g.home_team_id OR t.id = g.away_team_id
        WHERE t.conference = 'SEC'
        GROUP BY t.id
        ORDER BY game_count DESC
    """)
    print("\nGames per SEC team:")
    for row in cursor.fetchall():
        print(f"  {row[0]}: {row[1]} games")
    
    conn.close()

if __name__ == '__main__':
    main()
